### ISSUE TITLE
[Bug] Changing text on a Label on macOS resets font color to Black

### ISSUE THREAD

**Issue by maxim-saplin** [xamarin/Xamarin.Forms#10101]
### Description
The Issue started appearing in XF 4.5, 4.4 is OK

### Steps to Reproduce

1. Define a Label on a page with some text in it
2. Define Label style in app.xaml
```
        <!-- FONTS -->
        <OnPlatform x:TypeArguments="Font" x:Key="FontNormal">
            <On Platform="macOS" Value="IBM Plex Mono, 15" />
            <On Platform="iOS" Value="IBM Plex Mono, 15" />
            <On Platform="WPF" Value="./Fonts/IBMPlexMono-Regular.ttf#IBM Plex Mono, 15" />
            <On Platform="Android, iOS" Value="IBMPlexMono-Regular.ttf#IBMPlexMono-Regular, 15" />
        </OnPlatform>
        <!-- LABELS -->
        <Style TargetType="Label" ApplyToDerivedTypes="True">
            <Setter Property="Font" Value="{StaticResource FontNormal}" />
            <Setter Property="TextColor" Value="Red" />
        </Style>
```
3. Run the app, see the color of text is applied
4. Change the text of the Label in code behind (e.g. on button click)

### Expected Behavior

The text color stays as it is defined in Style

### Actual Behavior

The color is set to black

**Comment by maxim-saplin** [comment]
There's a problem with Button as well. If Text is updated in code behind the font get's corrupted.
![macOS Button](https://user-images.githubusercontent.com/7947027/81017419-1b5dd300-8e6b-11ea-83ee-829f34a4d24d.gif)

**Comment by maxim-saplin** [comment]
Any news? XF 4.5 and up is barely useful for macOS with even basic UI being corrupted.

**Comment by nor0x** [comment]
+1

**Comment by sady4850** [comment]
I'm also waiting for the fix with the fingers crossed.

**Comment by chamchum** [comment]
Seems that there was commit https://github.com/xamarin/Xamarin.Forms/pull/8206/files
Motivation was to AddCharacterSpacing by using AttributedStringValue.
For maintaining this attribute `UpdateTextColor()` was modified to change color in AttributedStringValue but not in NSLabel.TextColor.
But `UpdateTextPlainText()` is not using attributed string, thus it sets usual StringValue with default value in NSLabel.TextColor.

Workaround is to implement own LabelRenderer and override there OnElementPropertyChanged

`[assembly: ExportRenderer(typeof(Label), typeof(MacLabelRenderer))]
namespace MyProject.Renderers
{
    public class MacLabelRenderer : LabelRenderer
    {
        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == Label.TextProperty.PropertyName)
            {
                Control.TextColor = Element.TextColor.ToNSColor();
            }

            base.OnElementPropertyChanged(sender, e);
        }
    }
}`

**Comment by jfversluis** [comment]
@nor0x would you by any chance be able to test the NuGets resulting from #10120 on your reproduction? See [here](https://blog.verslu.is/xamarin/xamarin-forms-xamarin/test-xamarin-forms-bugfixes/) how to do that.

@maxim-saplin could you maybe add a reproduction for the button one? Thank you :)

**Comment by maxim-saplin** [comment]
@jfversluis https://github.com/maxim-saplin/TimeSeries-Xamarin - that's the repo with button text bug. The steps are quite straightforward, changing button text in code behind breaks button font:

```
            if (collectionTypeButton.Text == showingRandom)
                collectionTypeButton.Text = showingParabola;
            else collectionTypeButton.Text = showingRandom;
```

**Comment by jfversluis** [comment]
I only see you setting a custom font on a label in a custom control, right?

Could you please point me where you are setting some custom things on your button? Or even better, lift that code to a separate repro project

**Comment by maxim-saplin** [comment]
Right, custom font is only used with Labels. Buttons get font jumps without any customizations, simple changes of Text value in code behind leads to buttons' font size increase.

**Comment by jfversluis** [comment]
Yep definitely see that happening!

**Comment by nor0x** [comment]
@jfversluis just tested the repro with the NuGets from #10120 and color changing is working as expected

**Comment by nor0x** [comment]
Hi @jfversluis 👋 do you have an update on this or do you need more repro info?

**Comment by jfversluis** [comment]
@maxim-saplin according to @nor0x this is fixed as of 4.7.0.1239 would you be able to confirm?

If so, #10120 can be closed and we can move on 🎉

**Comment by maxim-saplin** [comment]
@jfversluis sorry, can't test it. I've removed VS and Xamarin from my laptop.

**Comment by HelgeKeck** [comment]
sorry to jump in uninvited, i still have this problem and im on 4.8.0.1451.

**Comment by kmcclive** [comment]
I can confirm that this is still a problem on 5.0.0.1874.

**Comment by maxim-saplin** [comment]
Just check my old app on 5.0.0.2012, labels' font is still reverted when Text property is changed

**Comment by Spamm3r** [comment]
Still problem on 5.0.0.2083
Is there any chance for fix in near future?

**Comment by Spamm3r** [comment]
Okay, there is more to this problem than I have imagined and no-one from here have found this so far. There are 2 case of this problem. They are both dependent on Dark Mode setting on your MacOS. So if you have light mode enabled then Label color will be reverted to black color but if you have black mode enabled the value of color property will be reverted to white. So imagine my surprise when I have rewritten my whole project to be light mode and then it stopped working all of sudden cuz Night Shift has changed from Light Mode to Dark Mode. I am curious if this problem persists on iOS as well.

**Comment by nor0x** [comment]
@jfversluis 👋 good to hear that you are back at XF / MAUI. This issue could use some love ;-)

**Comment by jfversluis** [comment]
Hey @nor0x ! Thanks! :D Glad to see this is still left here for me to fix... I'll add it on the list, can't make any promises!
