### ISSUE TITLE
[Bug] Sleep causes ArgumentNullException (iOS)

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#10752]
### Description

Even with a fresh project the app crashes when entering the sleep mode. 

### Steps to Reproduce

1. Create new project
2. Update Xamarin.Forms and Essentials
3. Start the app 
4. Use the Home button / bring the App to sleep mode 
5. Crash happens

### Expected Behavior

No crash.

### Actual Behavior

Crash with the following details: 
```
2020-05-18 14:22:35.596126+0200 CrashOnSleep.iOS[19236:6888460] 
Unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: enumerable
  at Xamarin.Forms.Internals.EnumerableExtensions.IndexOf[T] (System.Collections.Generic.IEnumerable`1[T] enumerable, T item) [0x00003] in D:\a\1\s\Xamarin.Forms.Core\EnumerableExtensions.cs:79 
  at Xamarin.Forms.Application.OnRequestedThemeChanged (Xamarin.Forms.AppThemeChangedEventArgs args) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:172 
  at Xamarin.Forms.Platform.iOS.PageRenderer.TraitCollectionDidChange (UIKit.UITraitCollection previousTraitCollection) [0x00021] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:373 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at CrashOnSleep.iOS.Application.Main (System.String[] args) [0x00001] in /Users/sebastian/WorkingCopy/local/CrashOnSleep/CrashOnSleep.iOS/Main.cs:17
2020-05-18 14:22:35.596975+0200 CrashOnSleep.iOS[19236:6888460] Unhandled managed exception: Value cannot be null.
Parameter name: enumerable (System.ArgumentNullException)
  at Xamarin.Forms.Internals.EnumerableExtensions.IndexOf[T] (System.Collections.Generic.IEnumerable`1[T] enumerable, T item) [0x00003] in D:\a\1\s\Xamarin.Forms.Core\EnumerableExtensions.cs:79 
  at Xamarin.Forms.Application.OnRequestedThemeChanged (Xamarin.Forms.AppThemeChangedEventArgs args) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:172 
  at Xamarin.Forms.Platform.iOS.PageRenderer.TraitCollectionDidChange (UIKit.UITraitCollection previousTraitCollection) [0x00021] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:373 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at CrashOnSleep.iOS.Application.Main (System.String[] args) [0x00001] in /Users/sebastian/WorkingCopy/local/CrashOnSleep/CrashOnSleep.iOS/Main.cs:17

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10d04fde5 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_dump_native_crash_info
	0x10d044755 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_handle_native_crash
	0x10d04f40b - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : sigabrt_signal_handler
	0x7fff51b2f5fd - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x7f8c4e205130 - Unknown
	0x7fff51a1fb7c - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x10d26bb1f - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : xamarin_unhandled_exception_handler
	0x10d0f90d5 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_invoke_unhandled_exception_hook
	0x10d044309 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_handle_exception_internal
	0x10d0427f9 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_handle_exception
	0x10cfc6149 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_amd64_throw_exception
	0x10f75e5b0 - Unknown
	0x11b4afc13 - Unknown
	0x11b4acc4b - Unknown
	0x10d059651 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_jit_runtime_invoke
	0x10d16f478 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_runtime_invoke_checked
	0x10d172a7e - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_runtime_invoke
	0x10d275ab7 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : xamarin_invoke_trampoline
	0x10d27cdb9 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : xamarin_arch_trampoline
	0x10d27dfbe - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : xamarin_x86_64_common_trampoline
	0x7fff4851daf0 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIViewController _traitCollectionDidChange:]
	0x7fff4851dda3 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIViewController _updateTraitsIfNecessary]
	0x7fff490c937a - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
	0x7fff2b4ae3f0 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/QuartzCore.framework/QuartzCore : -[CALayer layoutSublayers]
	0x7fff2b4b457b - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/QuartzCore.framework/QuartzCore : _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE
	0x7fff2b4bfc12 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/QuartzCore.framework/QuartzCore : _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE
	0x7fff2b408c84 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/QuartzCore.framework/QuartzCore : _ZN2CA7Context18commit_transactionEPNS_11TransactionEd
	0x7fff2b43c65f - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/QuartzCore.framework/QuartzCore : _ZN2CA11Transaction6commitEv
	0x7fff48bd0ff9 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __83-[UIApplication _createSnapshotContextForScene:withName:performLayoutWithSettings:]_block_invoke_4
	0x7fff48bd0346 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication _performWithUICACommitStateSnapshotting:]
	0x7fff48bd0f49 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __83-[UIApplication _createSnapshotContextForScene:withName:performLayoutWithSettings:]_block_invoke_2
	0x7fff490bb8a8 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : +[UIView(Animation) performWithoutAnimation:]
	0x7fff48bd0c7c - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __83-[UIApplication _createSnapshotContextForScene:withName:performLayoutWithSettings:]_block_invoke
	0x7fff48128d04 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIScene _applyOverrideSettings:forActions:]
	0x7fff48e3660f - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIWindowScene _applySnapshotSettings:forActions:]
	0x7fff48bd0b3b - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication _createSnapshotContextForScene:withName:performLayoutWithSettings:]
	0x7fff48bd26df - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __65-[UIApplication _performSnapshotsWithAction:forScene:completion:]_block_invoke_3
	0x7fff36c7f337 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSSceneSnapshotAction _executeNextRequest]
	0x7fff36c7f381 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSSceneSnapshotAction _executeNextRequest]
	0x7fff36c7ef5d - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSSceneSnapshotAction executeRequestsWithHandler:completionHandler:expirationHandler:]
	0x7fff48bd2615 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __65-[UIApplication _performSnapshotsWithAction:forScene:completion:]_block_invoke_2
	0x7fff48bd1af9 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication _beginSnapshotSessionForScene:withSnapshotBlock:]
	0x7fff48bd24bd - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __65-[UIApplication _performSnapshotsWithAction:forScene:completion:]_block_invoke
	0x7fff48128c0c - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIScene _enableOverrideSettingsForActions:]
	0x7fff48128e61 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIScene _performSystemSnapshotWithActions:]
	0x7fff48bd220b - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication _performSnapshotsWithAction:forScene:completion:]
	0x7fff49163a8c - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __98-[_UISceneSnapshotBSActionsHandler _respondToActions:forFBSScene:inUIScene:fromTransitionContext:]_block_invoke_3
	0x7fff49163910 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __98-[_UISceneSnapshotBSActionsHandler _respondToActions:forFBSScene:inUIScene:fromTransitionContext:]_block_invoke_2
	0x7fff48128467 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
	0x7fff481293e2 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
	0x7fff48719331 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:]
	0x7fff36c367be - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]
	0x7fff36c5c27f - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke_2
	0x7fff36c40757 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
	0x7fff36c5c1bc - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke
	0x7fff519128cb - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_client_callout
	0x7fff51915292 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_block_invoke_direct
	0x7fff36c816e9 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
	0x7fff36c813d7 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSSerialQueue _queue_performNextIfPossible]
	0x7fff36c818e6 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSSerialQueue _performNextFromRunLoopSource]
	0x7fff23d9deb1 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
	0x7fff23d9dddc - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSource0
	0x7fff23d9d5b4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSources0
	0x7fff23d981ae - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopRun
	0x7fff23d97ac4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x7fff38b2fc1a - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x7fff48bc7f80 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x113b80d8a - Unknown
	0x113ace573 - Unknown
	0x1138d72f3 - Unknown
	0x10d059651 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_jit_runtime_invoke
	0x10d16f478 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_runtime_invoke_checked
	0x10d174a65 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_runtime_exec_main_checked
	0x10cfc5c0c - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : mono_jit_exec
	0x10d27c2ad - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : xamarin_main
	0x10cf9ce77 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/FECE1991-0CDE-4790-8381-296834F58416/CrashOnSleep.iOS.app/CrashOnSleep.iOS : main
	0x7fff519521fd - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdyld.dylib : start
	0x3 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fff51a9033a):0x7fff51a9032a  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x7fff51a9033a  73 08 48 89 c7 e9 e5 a2 ff ff c3 90 90 90 b8 53  s.H............S
0x7fff51a9034a  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 cd a2  ...I....s.H.....
0x7fff51a9035a  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================


```

### Basic Information

- Version with issue: 4.6.0.772
- Last known good version: Unknown / not tested
- IDE: Visual Studio for Mac Enterprise 
- Platform Target Frameworks: 
  - iOS: 13.16.0.13

### Reproduction Link

[CrashOnSleep.zip](https://github.com/xamarin/Xamarin.Forms/files/4644069/CrashOnSleep.zip)

**Comment by jsuarezruiz** [comment]
@PureWeen This issue should have been fixed with https://github.com/xamarin/Xamarin.Forms/pull/10714?

**Comment by rmarinho** [comment]
This is fixed on 4.6.0.800

**Comment by TybbyAce** [comment]
It is still happening on 4.7.0.968

System.ArgumentNullException: Value cannot be null.
Parameter name: enumerable
  at Xamarin.Forms.Internals.EnumerableExtensions.IndexOf[T] (System.Collections.Generic.IEnumerable`1[T] enumerable, T item) [0x00003] in D:\a\1\s\Xamarin.Forms.Core\EnumerableExtensions.cs:79
  at Xamarin.Forms.Application.OnRequestedThemeChanged (Xamarin.Forms.AppThemeChangedEventArgs args) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:172
  at Xamarin.Forms.Platform.iOS.PageRenderer.TraitCollectionDidChange (UIKit.UITraitCollection previousTraitCollection) [0x00021] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:373
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.2.1/src/Xamarin.iOS/UIKit/UIApplication.cs:86
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.2.1/src/Xamarin.iOS/UIKit/UIApplication.cs:65

**Comment by rmarinho** [comment]
@TybbyAce do you have a sample? this should be fixed on 4.7.0.968, if i use the example repo above it's fixed. 

Can you give me a sample code?

**Comment by TybbyAce** [comment]
Sorry Rui, I can't. It's the app I'm developing. It may not happen in a sample I'd put together. But if you give me some pointers where to look, I can debug my app, maybe I am doing something stupid - highly likely :)) -  that causes your code crash unexpectedly.

**Comment by Sebastian1989101** [comment]
@TybbyAce this problem is fixed for sure so it's currently a issue on your end. I would suggest closing down Visual Studio and deleting all _obj_ and _bin_ folders (both of them exist in every project in your solution). Sometimes the compiler does not update old references so it is possible that you have some sort of old Xamarin.Forms version in it - or in worse case multiple versions and you can't even make sure which one gets loaded. If you are on macOS you can setup intelligent folders in Finder to show all _obj_ and _bin_ folders on one "location" to delete all at once easily. And no, the "Clean" in VS does not work to clear this up, so a manual delete is your best bet to make sure you don't have this kind of issue.

**Comment by rmarinho** [comment]
Thanks @Sebastian1989101 . Yeah @TybbyAce make sure you clean the sln and update all projects with the latest version. Remove the bin and obc folders :

please get back to us to see if we can close this or we are missing something. 

Thanks

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
