### ISSUE TITLE
[Bug] UWP: Page with CollectionView is not displayed until the window is resized.

### ISSUE THREAD

**Issue by holecekp** [xamarin/Xamarin.Forms#10977]
###  Description
In some situations, only blank page is rendered when the application starts. After the window is resized by the user, all the content suddenly appears. I have prepared a simplified version of my project:

[UwpBug-2020-06-06.zip](https://github.com/xamarin/Xamarin.Forms/files/4740020/UwpBug-2020-06-06.zip)

There is a page with a SearchBar, CollectionView and a Button. When the app is started, only blank page is displayed. When I resize the window, all the content (SearchBar, CollectionView and a Button) becomes visible.

This is even more complicated as this bug is present about 90% of times, but sometimes when I run the app, the content is visible immediately (usually when I delete bin and obj folders manually). When I rerun the app, the bug is there.

Another complication is that depending on Xamarin.Forms version, the behavior seems to be sometimes different depending on if you use Debug or Release versions! I have found the bug when just before uploading my app to Microsoft Store. I have used only Debug version during development. Before uploading the final version I wanted to try also the Release version just to be sure. And I have found out that it is not working. In my case, version 4.6.0.726 worked correctly in Debug but not in the Release mode. Upgrading to 4.6.0.847 made things even worse and the bug was there in both Debug and Release modes. However, I am not able to reproduce this difference in by repro solution.

Just creating the repro solution took me a few hours because I started with my app and removed one thing by another and tested if the bug is still there (both in debug and release; and UWP release build is ridiculously slow). I needed to make sure that the bug is not caused by some other Nuget.

This bug might be connected to the Issue #10862. However, there is no need to click and navigate in this case (compared to the situation mentioned in #10862). So it can be a different problem.

### Steps to Reproduce

1. Download the attached solution.
2. Run the UWP project. The page is blank (if it is not, close the app and run it again).
3. Resize the window. Now the content is visible.
4. I have included also Android project for comparison to make sure there is no problem in the code. If you try the Android project, it is displayed correctly. The bug is only in UWP.

### Expected Behavior
The content (SearchBar, CollectionView and a Button) is visible right after the start. Also the behavior should be deterministic and it should be the same for Debug and Release versions.

### Actual Behavior
The content is hidden (most of the times) until the window is resized.

### Basic Information

- Version with issue: Xamarin.Forms 4.6.0.847
- Last known good version: unknown
- IDE: VS 2019 (16.6.1)
- Platform Target Frameworks:
  - UWP:  1903
- Nuget Packages: Only basic packages that are included when new Xamarin.Forms project is created in VS (Xamarin.Forms, Essentials, etc.).

### Screenshots
When the app is started, nothing is there:
![UWPBug-release-after start](https://user-images.githubusercontent.com/24872113/83944547-7b49ef80-a804-11ea-9cb9-86c6ac7f3c32.png)

When I resize the window, all content become visible:
![UWPBug-release-after resize](https://user-images.githubusercontent.com/24872113/83944549-7f760d00-a804-11ea-8b2f-6570ac07f5f2.png)

**Comment by bmacombe** [comment]
Just to note here, things not showing up or sized correctly until a window resize, etc seems to be a consistent theme in the UWP backend especially related to Labels or Entries.  I suspect there are still some underlying issues that we are all trying to bandaid, but I haven't been able to track it down.

Below are some open and closed issues and PRs on related items.

#8787
#8214
#2172
#5711

**Comment by hartez** [comment]
Verified - I got the blank screen on the first try. 

I'm on a single monitor, so at the very least we know this isn't another instance of a UWP second monitor bug.

**Comment by hartez** [comment]
I wonder if this is an issue with the Device display metrics not being initialized. We have had at least one bug previously where uninitialized display size values caused CollectionView problems, and a window resize will force the display size values to update.

**Comment by velocitysystems** [comment]
We too can confirm this issue and see it intermittently on UWP in both debug and release builds.

**Comment by bmacombe** [comment]
@hartez I didn't have much success searching for info about the Device Display Metrics.  Is that a collection view thing or UWP?  Just looking for a pointer, I was thinking about looking into the entry/editor text not showing until resize as it's starting to be a real pain!

**Comment by hartez** [comment]
@bmacombe For UWP, that stuff would be in the WindowsDeviceInfo class. It's a long shot, but I know that a while back we had a CollectionView bug where it didn't display at all in Shell; the culprit turned out to be that the DeviceInfo stuff on Android wasn't being initialized properly on startup.

Which Entry/Editor thing were you looking at? I know there's one where if you set a height, it doesn't display the text (or vice versa, can't remember right now) - is that what you're investigating?

**Comment by bmacombe** [comment]
@hartez Here are a couple
#8214 Merged PR I did dealing with entry/editor hight in a scroll view 

issues
#8787 
#8503
#5711

I just get the feeling there has to be something common to all these problems and my gut thinks it's in the FormsTextBox or the control template.  My PR just used a hack already in place in the editor to try to fix the entry also.  It seems to work on the height issue, but not the text showing.  The entry/editor getting focus or a window resize seems to do the trick.  I've wondered if it's a timing issue on when the UWP text property is being set or something like that.

Thinking about starting with what is in PR #8536 that @WayaFlyfeather was working on, I think it fixed the text not showing, but when combined with my PR broke other behavior.

**Comment by hartez** [comment]
> my gut thinks it's in the FormsTextBox or the control template
You're probably right. I spent some time looking at this one evening, and the issue seemed to be related to the ScrollViewer in the template. But I didn't have time to dig any deeper than that.

**Comment by holecekp** [comment]
If you are desperate to get this working, here is my "workaround" - hide the CollectionView on UWP and use a ListView instead. It will not look nice and it is probably not efficient but the page is displayed at least.

```xml
        <CollectionView
            ItemTemplate="{StaticResource ItemsDataTemplate}"
            ItemsSource="{Binding Items}"
            IsVisible="{OnPlatform Default=True, UWP=False}" />

        <ListView
            ItemTemplate="{StaticResource ItemsDataTemplateUwp}"
            ItemsSource="{Binding Items}"
            IsVisible="{OnPlatform Default=False, UWP=True}" />
```

**Comment by velocitysystems** [comment]
@hartez Do you have any recommendations on how we can assist with this issue? We can confirm the behaviour in the repro project.

Looking at `WindowsDeviceInfo`:
- There is a todo comment there, has this been addressed?
- What is the context when this class is initialized?
- I'm guessing this doesn't blow up, but is the information returned by `DisplayInformation.GetForCurrentView()` valid at the time when the `CollectionView` is drawn? Is there any _difference_ in the params before and after a window resize?

https://github.com/xamarin/Xamarin.Forms/blob/f11d0993545f71668a62f46dab4223664ce17063/Xamarin.Forms.Platform.UAP/WindowsDeviceInfo.cs#L15-L21

**Comment by EmilAlipiev** [comment]
I have this issue when i load the data in OnAppearing, if i use Constructor or Init method to load data, everything is fine. is your problem related to that? I found the root cause and I will send a PR for that one also.

**Comment by velocitysystems** [comment]
Thanks Emil, I’d be really interested in seeing your research into this problem.

**Comment by velocitysystems** [comment]
I wonder if #11351 is a possible fix?

**Comment by bmacombe** [comment]
> @hartez Do you have any recommendations on how we can assist with this issue? We can confirm the behaviour in the repro project.
> 
> Looking at `WindowsDeviceInfo`:
> 
> * There is a todo comment there, has this been addressed?
> * What is the context when this class is initialized?
> * I'm guessing this doesn't blow up, but is the information returned by `DisplayInformation.GetForCurrentView()` valid at the time when the `CollectionView` is drawn? Is there any _difference_ in the params before and after a window resize?
> 
> https://github.com/xamarin/Xamarin.Forms/blob/f11d0993545f71668a62f46dab4223664ce17063/Xamarin.Forms.Platform.UAP/WindowsDeviceInfo.cs#L15-L21

@velocitysystems I wonder if something like this what is meant by that todo.  Doesn't do anything to help with this issue though unfortunately

![image](https://user-images.githubusercontent.com/15127788/87114274-cb6a0680-c235-11ea-8d31-3489ff7058ec.png)

**Comment by bmacombe** [comment]
> I wonder if #11351 is a possible fix?

Doesn't fix 😞

**Comment by bmacombe** [comment]
Just an observation, while stepping through VisualElementPackager.  All the controls were visible on the initial load when I ran out of code to step through.  Maybe there is a timing issue in play here?

**Comment by bmacombe** [comment]
Other observation...on the initial load, only the renderers for the labels inside the collection view templates are having their GetDesiredSizecalled.  After you resize the window, everything gets GetDesiredSize called.

**Comment by bmacombe** [comment]
![image](https://user-images.githubusercontent.com/15127788/87168728-8c1ed280-c294-11ea-93f4-2d48d6f932ec.png)

It seems setting the ItemsSource of the CollectionView during the hosting page's OnAppearing might be causing this.  Just commenting that out makes everything show on the first load (minus the items)

![image](https://user-images.githubusercontent.com/15127788/87168882-c1c3bb80-c294-11ea-88e0-95bedf2be4d5.png)

**Comment by bmacombe** [comment]
Even adding a minor delay in OnAppearing causes them to load fine.
![image](https://user-images.githubusercontent.com/15127788/87169534-c2108680-c295-11ea-8d6d-78579cec4acf.png)

**Comment by pwillies** [comment]
@bmacombe @hartez @samhouts Hi XF Team, This is on our critical list. We cannot ship a product that displays a blank page half the time.

**Comment by bmacombe** [comment]
@pwillies I'm just a contributor that got sucked into this issue out of curiosity while working on a PR for another UWP issue.  But #11394  PR is ready for review by the team when they can get to it.

If you really need a temp workaround, adding a delay before setting the ItemSource of maybe 10ms or so seemed to work in most cases.  2-3ms was normally plenty, but my machines are pretty fast so a longer one would be best.

**Comment by Jouna77** [comment]
Is this going to be included in the  nugget of Xamarin forms?
We cant wait until MAUI is released.

**Comment by hartez** [comment]
The original repro project from @holecekp works fine if I update it to 5.0.0 pre2. The layout timing/update issue appears to have been fixed by https://github.com/xamarin/Xamarin.Forms/pull/12017.

**Comment by holecekp** [comment]
@hartez I have tried my application with XF 5.0 pre-5 and the problem is still there. There is a blank page instead of the CollectionView. So maybe, the issue was fixed for simpler cases such as the original repro project but not for all of them.

It seems that another pull request related to this issue (https://github.com/xamarin/Xamarin.Forms/pull/13081] is on the way so I will wait for the next pre-relase containing that pull request and I will test it again.

**Comment by Jouna77** [comment]
@hartez I remeber I managed to solve this issue by calling Layout and ForceLayout on main thread take a  look at https://github.com/rotorgames/Rg.Plugins.Popup/pull/579

**Comment by holecekp** [comment]
I have tried XF 5.0 pre-6, which contains another changes related to this issue (https://github.com/xamarin/Xamarin.Forms/pull/13081). I have tested that version in my application and the problem with the CollectionView visibility has been fixed.

There are still some measurement bugs on UWP. For example, one page that changes ItemsLayout after the items are loaded is not displayed correctly and the last item is outside the visible area of the page. I will file a new issue for this on January.

Nevertheless, the CollectionView is much more reliable now and it works for me for most of scenarios on UWP.

**Comment by MasterSigmar** [comment]
XF 5.0.0.2012 here
Issue still there for me but only for the EmtpyView

If I start the app and init my ItemsSource with content in the ViewModel's ctor everything is fine.
But if I leave it empty it displays a blank page untill it gets resized and then the page is displayed with the CollectionView's EmptyView.

IE : if i comment this out, everything is fine but RIP my EmptyView
![image](https://user-images.githubusercontent.com/15975367/118998863-c8f93280-b957-11eb-8b7a-8c084e48b637.png)

**Comment by pabloat81** [comment]
> Even adding a minor delay in OnAppearing causes them to load fine. ![image](https://user-images.githubusercontent.com/15127788/87169534-c2108680-c295-11ea-8d6d-78579cec4acf.png)

Hello. I am having the same problem on a recently created project on VS2019.
I tried all but de CV not rendering till resize.
I load the data async. I Tried something like this, but i cant make it work:

 protected override void OnAppearing()
        {
            base.OnAppearing();
            Task.Run(async () => await vm.InitialLoad());
        }

**Comment by pabloat81** [comment]
I made the load syncronous and worked, but would like to maintain it async.

**Comment by FabriBertani** [comment]
> XF 5.0.0.2012 here Issue still there for me but only for the EmtpyView
> 
> If I start the app and init my ItemsSource with content in the ViewModel's ctor everything is fine. But if I leave it empty it displays a blank page untill it gets resized and then the page is displayed with the CollectionView's EmptyView.
> 
> Kind wierd it only still does it only when trying to display an EmptyView /shrug
> 
> IE : If I comment this out, everything is fine but RIP my EmptyView ![image](https://user-images.githubusercontent.com/15975367/118998863-c8f93280-b957-11eb-8b7a-8c084e48b637.png)

Apparently this is the issue, I have removed the EmptyView from my CollectionView too and now the page renders correctly.
As a workaround I had to use a converter to check if the list is empty and show/hide another view with the content of the  EmptyView.

I hope they fix this issue in MAUI, because it seems that XF is completely abandoned by Microsoft.

**Comment by acaliaro** [comment]
Today I have the same problem!
