### ISSUE TITLE
[Bug] [iOS] Ignores Label properties e.g. FontSize, FontAttributes and Color when TextType set to html 

### ISSUE THREAD

**Issue by darrabam** [xamarin/Xamarin.Forms#11039]
### Description
Only on iOS, it ignores Label properties e.g. FontSize, FontAttributes and Color when TextType set to html. This works fine on Android. 

This is related to 
https://github.com/xamarin/Xamarin.Forms/issues/10588
https://github.com/xamarin/Xamarin.Forms/issues/8157
  
### Expected Behavior
If the html text doesn't override the label properties with inline style, the provided properties should be respected and applied. 
### Actual Behavior
Ignores all properties and renders the text as normal black text. 

### Basic Information

IDE: Microsoft Visual Studio Community 2019 (Version 16.5.4)

Platform Target Frameworks: iOS (13.5)

Nuget Packages:
Xamarin.Forms 4.6.0.8
Xamarin.Essentials 1.5.3.2

### Screenshots
![image](https://user-images.githubusercontent.com/33980667/84561699-4cc59a80-ad57-11ea-8ec6-6f35868a5fb6.png)
### Reproduction Link

![image](https://user-images.githubusercontent.com/33980667/84561717-6f57b380-ad57-11ea-83bb-1839179d3ca3.png)

Code is available in https://github.com/darrabam/HTMLLabelBug

### Workaround
none.

**Comment by GalaxiaGuy** [comment]
This is a limitation of the underlying mechanism used to implement the HTML text type on iOS.

To workaround it, I believe it would be necessary to generate some appropriate CSS and prepend a `<style> ... </style>` tag to the beginning of the HTML.

I'm not sure if it could be done in a way that will work in every situation.

**Comment by hartez** [comment]
This is basically a duplicate of #10588 - is there anything in this report that's not covered by that one?

Also, #10989 should fix this.

**Comment by darrabam** [comment]
@GalaxiaGuy the documentation in MS website doesn’t mention this limitation, so I consider this as a bug. Besides the workaround (in-line styling) doesn’t work/not supported on Android as far as I can see.  

@hartez #10588 doesn't mention font color, size ... etc, so I want to be exclusive.
And yes, hopefully #10989 should fix this issue, and I’ll test it as soon as it is merged.

Thanks,

**Comment by hartez** [comment]
@darrabam My bad, #10588 doesn't mention those in the original issue; they're brought up in comments further down (https://github.com/xamarin/Xamarin.Forms/issues/10588#issuecomment-639936223). 

Hopefully the #10989 fix can close both issues :)

**Comment by rachelkang** [comment]
Closing this issue as it seems to have been fixed in XF 4.8 :)

**Comment by Daniel0b1b** [comment]
On XF 5 it seems this issue is back. Html text is not shown correctly if FontFamily, FontSize or TextColor is set.
