### ISSUE TITLE
Overlapping labels

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11266]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1090550/overlapping-labels.html)._

---
<p>I have updated to the latest version of xamarin form (4.7.0.968) and all the labels are overlapping on iOS.</p> <p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/143201-simulator-screen-shot-iphone-11-pro-max-2020-06-24.png"> Image:143201-simulator-screen-shot-iphone-11-pro-max-2020-06-24.png</a></p><p></p>

---
#### Visual Studio Feedback System on 6/27/2020, 10:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### Reproduction
[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/4893291/Archive.zip)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by adrielmsantos** [comment]
I have the same issue only on iOS
This issue begins after update to XF 4.7

![listview issue](https://user-images.githubusercontent.com/29964329/86301654-c32e1d80-bbdc-11ea-803a-7827f80225f6.png)

**Comment by hartez** [comment]
@adrielmsantos Does your DataTemplate include a Frame?

**Comment by adrielmsantos** [comment]
@hartez Yes. Inside a Frame

**Comment by Chasyl** [comment]
@samhouts 
You can reproduce this issue in this xamarin forms sample: [ListViewColors](https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/boxview-listviewcolors)

**Comment by thomasgalliker** [comment]
Same issue here. Is happens if I create a ListView with an ItemTemplate which places a Label inside a Frame. The ListView is rendered fine but as soon as you start to scroll, the Labels start to overlap with eachother.

**Comment by gregersen79** [comment]
Same issue here. It works on XF 4.6.0.847, but all newer versions has this issue.
My DataTemplate looks like this:

```
<DataTemplate>
	<ViewCell>
		<Frame BorderColor="Gray" HasShadow="True" Margin="15,10,15,10">
			<StackLayout Orientation="Horizontal" Spacing="20">
				<ffimageloading:CachedImage HorizontalOptions="Start" VerticalOptions="Center"
					WidthRequest="100" HeightRequest="100"
					DownsampleToViewSize="true"
					FadeAnimationEnabled="True"
					Source = "{Binding ImageUrl}">
				</ffimageloading:CachedImage>
				<StackLayout Orientation="Vertical" VerticalOptions="Center" HorizontalOptions="Center" Spacing="0">
					<Label Text="{Binding Title}" FontSize="Medium" FontFamily="Roboto-Bold" Margin="0,0,0,0"/>
					<Label TextType="Html" Text="{Binding SubText}" FontSize="Small" TextColor="LightGray"/>
				</StackLayout>
			</StackLayout>
		 </Frame>
	</ViewCell>
</DataTemplate>
```

If I remove the Labels text bindings, and hardcode the text, it works. 


![zc5Tr](https://user-images.githubusercontent.com/20276206/86914222-375a4b00-c120-11ea-88d8-45149e3cd71b.png)

**Comment by PureWeen** [comment]
[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/4893291/Archive.zip)

From a bisect

The merge base de38e1d79c9d1daf7668f8f566504dbeda46bdd2 is bad.
This means the bug has been fixed between de38e1d79c9d1daf7668f8f566504dbeda46bdd2 and [b4a6a7cec76e4ac255198353d726c27603fcaf72 ba337c66d06b45842d84703d77e60b032312ff66].

It looks like this commit caused the issue
https://github.com/xamarin/Xamarin.Forms/commit/de38e1d79c9d1daf7668f8f566504dbeda46bdd2#

**Comment by ndastur** [comment]
Is there a timeframe on a fix. Been in the wild for a month or so now. Preventing our production release

**Comment by vignatov** [comment]
Any news? I tried 4.7.0.1142 and pre-release of 4.8.0.1143. The problem is still there. What version will it be fixed in?

**Comment by samhouts** [comment]
Please try 4.6.0.1180 or 4.7.0.1179 or 4.8.0-pre2. Thanks!
