### ISSUE TITLE
[Bug] Shell absolute navigation to modal page can lead to the page constructor being called two times

### ISSUE THREAD

**Issue by skorpsim** [xamarin/Xamarin.Forms#11521]
### Description
An absolute navigation to a modal page using  Shell.Current.GoToAsync() can lead to the modal page constructor being called twice. This happens when the NavigationStack already contains stacked up pages.

### Steps to Reproduce

1. See attached demo

or use absolute routing to a registered modal page when the NavigationStack already contains stacked up pages

```
string currentRoute = Shell.Current.CurrentState.Location.OriginalString;
await Shell.Current.GoToAsync(currentRoute + '/' + ModalRoute);
```

### Expected Behavior
constructor of modal page is called once

### Actual Behavior
constructor of modal page is called twice

### Basic Information

- Version with issue: Xamarin.Forms v4.7.0.1179
- Last known good version: unknown
- IDE: Visual Studio Community 2019 16.6.5
- Platform Target Frameworks: 
  - iOS:  not tested
  - Android: 9.0
  - UWP:  not tested

### Reproduction Link
[ModalStackB.zip](https://github.com/xamarin/Xamarin.Forms/files/4965304/ModalStackB.zip)

### Workaround
Use relative navigation instead of absolute

**Comment by PureWeen** [comment]
This is fixed on 5.0 pre3

**Comment by GovindRulz** [comment]
Its not yet fixed , Im on version 5.0.0.2196. Any work around for this issue ?
