### ISSUE TITLE
[Bug] NavigationPage.BarBackground doesn't do anything on Android

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11630]
Setting NavigationPage.BarBackground to a LinearGradientBrush gives a nice gradient effect on iOS, but does nothing on Android. I am setting this through XAML.

Is this feature intended to work on Android?

Thanks.

**Comment by StephaneDelcroix** [comment]
@jsuarezruiz ?

**Comment by Tommigun1980** [comment]
Hello. Is this intended to work on Android? I don't think anything in the documents said it was iOS only, but if it is I'd need to know so I can plan accordingly. Thanks.

**Comment by PureWeen** [comment]
This should be fixed on the stable release of 4.8 coming out soon. I had mentioned this to @jsuarezruiz when testing and he fixed it.

I just tested against the nightly and it's working there

**Comment by Tommigun1980** [comment]
Thanks guys! Appreciate it.

**Comment by shashikantsejwar** [comment]
Has this been fixed? I can still see no effect on BarBackground on the Android 10 emulator
