### ISSUE TITLE
[Bug] Xamarin Forms Theme Don't Changed

### ISSUE THREAD

**Issue by bsglinux16** [xamarin/Xamarin.Forms#12298]
### Description
Xamarin Forms Theme Dont Change
On Xamarin Forms 4.6 and 4.8
UserAppTheme and ResourceDictionary Colors Not Working.

Application Opens with Default Theme Don't Apply Custom Theme.

Tried in Versions 4.6 and 4.8 The result is the same.
### Steps to Reproduce

1. UserAppTheme = OSAppTheme.Dark or Light Not Working.
2.  Setted Color and Setters on App.Xaml But App Opening Default Light Theme
3.  If System Theme Dark Then App Opening Default Dark Theme 

### Basic Information

- Version with issue: Xamarin Forms 4.8 Latest
- Last known good version: ??
- IDE: Visual Studio 2019 16.7
- Platform Target Frameworks: 
  - iOS:  none
  - Android: Mono 9.0 or 10.0
  - UWP:  none
- Android Support Library Version: ??
- Nuget Packages: 
- Affected Devices:

**Comment by hartez** [comment]
@bsglinux16 Can you include a repro project? Or show us your code for changing the app theme?

**Comment by bsglinux16** [comment]
> @bsglinux16 Can you include a repro project? Or show us your code for changing the app theme?

Firstly
UserAppTheme = OSAppTheme.Dark;


I Tried This But It Didn't Work. If the device's Theme is Light, it stays as Light again.

Later
I Created a Grain ResourceDictionary and Specified Styles did not work at first but it got fixed.

The problem is UserAppTheme Not Interfering with Application Theme.

**Comment by jsuarezruiz** [comment]
I have created a sample:
[Issue12298.zip](https://github.com/xamarin/Xamarin.Forms/files/5347361/Issue12298.zip)

Where use a ResourceDictionary with styles and then, set:

`UserAppTheme = OSAppTheme.Dark;`

The behavior:

![issue12298](https://user-images.githubusercontent.com/6755973/95451307-e39e0e80-0967-11eb-90f1-157be1acd9f3.gif)

Could you take a look to the sample, to check if we are we trying to do the same?

**Comment by bsglinux16** [comment]
> I have created a sample:
> [Issue12298.zip](https://github.com/xamarin/Xamarin.Forms/files/5347361/Issue12298.zip)
> 
> Where use a ResourceDictionary with styles and then, set:
> 
> `UserAppTheme = OSAppTheme.Dark;`
> 
> The behavior:
> 
> ![issue12298](https://user-images.githubusercontent.com/6755973/95451307-e39e0e80-0967-11eb-90f1-157be1acd9f3.gif)
> 
> Could you take a look to the sample, to check if we are we trying to do the same?

I am Not Used Style Properties

Does the theme need to change without using a Style with User AppTheme?

**Comment by bsglinux16** [comment]
Fixed with Styles thanks

**Comment by ajtruckle** [comment]
I still don't get this. According to the documentation the MacOS app should honor the current setting and should render accordingly. We should not need these static resources and manual colour choices. I just don't get it.

I simply want my dialog to render light or dark using system colours. Even though my system is dark, the app says it is "Unspecified".

**Comment by ajtruckle** [comment]
I had to update to xamarin.forms 5.x Now I am seeing dark theme window. :) But why doesn't button text change colour? I can override with appthemebinding but when just using defaults it stays the same and only background changes.
