### ISSUE TITLE
[Bug] Grid size not properly calculated in inside the item template 

### ISSUE THREAD

**Issue by KarthikRaja26** [xamarin/Xamarin.Forms#12384]
### Description
The Grid children's size not properly calculated if the Row height set as Auto with two columns in Inside the item template.

### Steps to Reproduce

1. Run the sample 
2. Note the text is goes outside of the view.

### Expected Behavior 

The grid and label inside it needs to layout with the proper size

### Actual Behavior

The Grid and its children does not properly layout.

### Basic Information

- Version with issue: 4.8+
- Last known good version: No
- IDE: VS2019
- Platform Target Frameworks:
  - iOS:  13.1
- Nuget Packages: Xamarin Forms

### Screenshots

![Screenshot 2020-10-06 at 11 22 59 PM](https://user-images.githubusercontent.com/46777511/95241134-fced7080-082a-11eb-8fd9-e10d72f39c7c.png)

### Reproduction Link

[SyncfusionChat 2.zip](https://github.com/xamarin/Xamarin.Forms/files/5335720/SyncfusionChat.2.zip)

### Workaround

If we remove the one column from the grid. It resolves the issue.

**Comment by jsuarezruiz** [comment]
@KarthikRaja26 Did it work as expected in previous versions? Does it happen on all platforms or only on iOS?

**Comment by KarthikRaja26** [comment]
Hi @jsuarezruiz ,

Thanks for the update.  Yes, it was working fine in 4.7 version in my custom control. So, I have tested with the same scenario in ListView and found that the same issue occurs in ListView. Additionally, i have tested the ListView with 4.7 versions but the issue still persists. I have checked the issues in iOS platform only. 


Regards,
Karthik Raja

**Comment by KarthikRaja26** [comment]
Hi @Redth ,

Any updates on this ?

Regards,
Karthik Raja

**Comment by jsuarezruiz** [comment]
@hartez Could this be related/fixed by https://github.com/xamarin/Xamarin.Forms/pull/12475?

**Comment by KarthikRaja26** [comment]
Hi @hartez , 

Could you please confirm on this?

Regards,
karthik Raja

**Comment by PureWeen** [comment]
@KarthikRaja26 

I tested on the latest nightly and it looks like it's been corrected

![image](https://user-images.githubusercontent.com/5375137/97784874-a9dbb480-1b6f-11eb-8be4-735e19ab379d.png)


https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds

I'm going to close for now but let me know if I'm mistaken and we can reopen

**Comment by KarthikRaja26** [comment]
Hi @PureWeen ,

I have checked with Xamarin Forms version 5.0.0.1558-pre3 and the issue persists in this version. Could you please check in mentioned XF version. Also, the second item getting cut off in the screenshot that you provided.

**Comment by KarthikRaja26** [comment]
Hi @PureWeen ,

Any update on this ?

**Comment by Sivaraman761** [comment]
Hi @PureWeen 

Any update on this?

**Comment by Chansardrake** [comment]
Hi @PureWeen ,

Any update on this?

**Comment by KarthikRaja26** [comment]
Hi @PureWeen ,

please reopen this issue. it is not fixed

**Comment by HUBBER12** [comment]
Syncfusion is referring this issue as a problem with one of their controls (critical for my use) - so I to need this to be fixed or i will be stuck on 4.7 unable to update to later versions of Xamarin Forms

**Comment by snoova** [comment]
Hi @PureWeen 

same problem here. Stuck on 4.7 because of this issue.
Any updates on this?

**Comment by hartez** [comment]
@KarthikRaja26 

> I have checked with Xamarin Forms version 5.0.0.1558-pre3 and the issue persists in this version. Could you please check in mentioned XF version. 

This is fixed in 4.8.0.1687. 

> Also, the second item getting cut off in the screenshot that you provided.

It's not being cut off, it's wrapping the text. That's because the attached repro project uses `Start` for `HorizontalOptions` for two of the controls. The Grid named 'fullMesssageView' should have `HorizontalOptions="Fill"`, not `Start`. And the `MyView1` control named 'textMessageBorder' should also be `HorizontalOptions="Fill"`, not `Start`.

**Comment by Alextorres950325** [comment]
> @KarthikRaja26
> 
> > I have checked with Xamarin Forms version 5.0.0.1558-pre3 and the issue persists in this version. Could you please check in mentioned XF version.
> 
> This is fixed in 4.8.0.1687.
> 
> > Also, the second item getting cut off in the screenshot that you provided.
> 
> It's not being cut off, it's wrapping the text. That's because the attached repro project uses for for two of the controls. The Grid named 'fullMesssageView' should have , not . And the control named 'textMessageBorder' should also be , not .`Start``HorizontalOptions``HorizontalOptions="Fill"``Start``MyView1``HorizontalOptions="Fill"``Start`

@KarthikRaja26 Syncfusion knows that?

**Comment by KarthikRaja26** [comment]
Hi @Alextorres950325 , 

If we set HorizontalOptions as fill the issue not fixed in our source. Currently we are checking other possible way to overcome this issue. we will update here.

Regards,
Karthik Raja

**Comment by KarthikRaja26** [comment]
Hi @hartez ,

Can you please reopen the issue and fix the issue in xamarin forms source level ?. 

Regards,
Karthik Raja
