### ISSUE TITLE
[Bug] Setting a Button's BorderWidth, CornerRadius to zero and BorderColor to Color.Transparent, does NOT work on MacOS.

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Xamarin.Forms#12757]
### Description
I am building a cross-platform app that targets iOS, Android and MacOS.

I'm using...
- latest Visual Studio for Mac v8.7.9.9
- latest Xamarin.Forms v4.8.1560

### Steps to Reproduce
I have a custom Button class as follows...
`    public class CustomButton : Button
    {
        public CustomButton ()
        {
            BorderWidth = 0;
            CornerRadius = 0;
            BorderColor = Color.Transparent;
            SetDynamicResource (Label.TextColorProperty, "ClickableTextColor");
        }
    }`

### Expected Behavior
Setting Button's  BorderWidth, CornerRadius to zero and BorderColor to Color.Transparent  should be respected/applied.

### Actual Behavior
on iOS and Android setting the Button's BorderWidth, CornerRadius to zero and BorderColor to Color.Transparent appears to be respected correctly, but on MacOS they seem to be ignored. 

### Basic Information

- Version with issue: 4.8.1560
- Last known good version: N/A
- IDE: Visual Studio for Mac v8.7.9.9
- Platform Target Frameworks: 
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.7.9 (build 9)
Installation UUID: 60c7c193-36a0-40cb-a1f6-65589da22877
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Roslyn (Language Service) ===

3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.403/Sdks
SDK Versions:
	3.1.403
	3.1.302
	3.1.301
	3.1.200
	2.1.302
	2.1.301
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.9
	3.1.6
	3.1.5
	3.1.2
	2.1.23
	2.1.20
	2.1.19
	2.1.17
	2.1.2
	2.1.1
	2.0.5
	2.0.3
	2.0.0

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.1 (17222)
Build 12A7403

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Enterprise)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 14.2.0.12 (Visual Studio Enterprise)
Hash: e0ce49680
Branch: xcode12.1
Build date: 2020-10-20 09:52:06-0400

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Enterprise)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/dominique/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/dominique/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

=== Build Information ===

Release ID: 807090009
Git revision: d29d54665a1fc79986687a540a7a4676f97ad3da
Build date: 2020-10-21 15:05:18-04
Build branch: release-8.7
Xamarin extensions: d29d54665a1fc79986687a540a7a4676f97ad3da

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

- Android Support Library Version: 
- Nuget Packages:  5.7.0.6702
- Affected Devices: Mac

### Screenshots
MacOS Screenies - 

<img width="600" alt="Screenshot 2020-11-05 at 19 24 43" src="https://user-images.githubusercontent.com/271363/98364607-fff59f80-2028-11eb-83f5-2c7f924ab2aa.png">

and also

<img width="148" alt="Screenshot 2020-11-05 at 19 24 56" src="https://user-images.githubusercontent.com/271363/98364640-0a179e00-2029-11eb-873c-83c697465cbe.png">

### Workaround

I could use a clickable label, but the point is setting those Button properties works correctly on iOS/Android but not on MacOS.

**Comment by CartBlanche** [comment]
Could this line be the issue...

https://github.com/xamarin/Xamarin.Forms/blob/4.8.0/Xamarin.Forms.Platform.MacOS/Renderers/ButtonRenderer.cs#L184

??

**Comment by rmarinho** [comment]
Hello Dominique :) can you try 5.0.0-pre3 i think we fixed this in 5.0.0. 

Thanks

**Comment by CartBlanche** [comment]
Hi @rmarinho . The problem is still there in 5.x. This screenshot looks identical to 4.8, but it is actually running on 5.0.pre3.

<img width="134" alt="Screenshot 2020-11-07 at 13 04 27" src="https://user-images.githubusercontent.com/271363/98442022-0f90e900-20fa-11eb-9546-4ba69e899c23.png">

**Comment by CartBlanche** [comment]
Hi @rmarinho any updates a rough time frame?

**Comment by rmarinho** [comment]
@CartBlanche sorry the delay, ok,  I investigate a bit and yeah that commit didn't reached the 5.0.0-pre3, you will need -pre4

Also after some testing, seems you have to add BackgroundColor to `CustomButton` something like : `BackgroundColor = Color.Transparent`

```
 public class CustomButton : Button
 {
      public CustomButton()
      {
         BorderWidth = 0;
         CornerRadius = 0;
         BorderColor = Color.Transparent;
         BackgroundColor = Color.Transparent;
         TextColor = Color.Blue;
      }
}
```

Can you try these nugets :
[debug.zip](https://github.com/xamarin/Xamarin.Forms/files/5525792/debug.zip)

<img width="1147" alt="Screenshot 2020-11-11 at 17 42 04" src="https://user-images.githubusercontent.com/1235097/98845709-02e7fa00-2446-11eb-89ed-de2b503b2f8a.png">

**Comment by CartBlanche** [comment]
@rmarinho Yes the *.5991 build works for me. WooT! Thanks for fixing it!

**Comment by CartBlanche** [comment]
Any ETA when this will hit preview or stable?

**Comment by CartBlanche** [comment]
@rmarinho any ETA on when this will be in preview or Stable?

**Comment by rmarinho** [comment]
hey @CartBlanche  it should be on pre5

**Comment by CartBlanche** [comment]
@rmarinho I'll give it a try shortly.

**Comment by CartBlanche** [comment]
This appears to be fixed in 5.0.0.1874, latest stable, so closing this issue.
