### ISSUE TITLE
[Bug] Shell.TitleView broken in v5.0.0.1874 when using multiple Views

### ISSUE THREAD

**Issue by liammc44** [xamarin/Xamarin.Forms#13420]
### Description
Functionality has been broken inside the Shell.TitleView for version 5.0.0.1874.

I have a Grid within the Shell.TitleView for a ContentPage. Within that Grid is an ImageButton and a Label.
When using version 4.8.0.1451, the ImageButton and Label show perfectly fine.
When I update to version 5.0.0.1874, the ImageButton and Label **no longer show**.

Again, this should work fine (as it was working in the previous release) - but this is now an issue.
I have been able to verify that I did not make any changes around this code, and could replicate the issue by creating a new project - which means the problem is in v5.0.0.1874.
The github project can be seen here [https://github.com/liammc44/XamarinError](url)

### Steps to Reproduce

1. Create a new Xamarin.Forms project, using the Shell navigation template
2. Add an image to the iOS project's resources folder (my image size was 128x128px)
3. Add the same image to the Android project's Resources > Drawable folder
3. Go to the Views folder, and edit the "AboutPage" XAML file
4. Add the following code (make sure to include your imageFileName within the ImageButton.Source attribute):

`<Shell.TitleView>
        <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition />
                <ColumnDefinition />
                <ColumnDefinition />
            </Grid.ColumnDefinitions>

            <ImageButton Source="yourFileNameHere.png" Margin="0,5,0,5" Grid.Column="0"/>
            <Label Text="Home" TextColor="White" HorizontalOptions="Center" VerticalOptions="Center" Grid.Column="0" Grid.ColumnSpan="3"/>

        </Grid>
    </Shell.TitleView>`

5. Run the iOS project for the iPhone 8 Plus device (iOS 14.3)
6. Notice how you can see the top part of the image only. You should be able to see the full image, not part of it. Notice how you can't see any "Home" text.
7. Run the iOS project for the iPhone 12 Pro device (iOS 14.3)
8. Notice how you can't see either the image or "Home" text on this device.

### Expected Behavior
The ImageButton & Label should show in the top navigation bar, as this code worked for the previous release.

### Actual Behavior
For iPhone 8 Plus (iOS 14.3), the image is very big and only part of it is visible. No "Home" text can be seen.
For iPhone 12 Pro (iOS 14.3), neither the image or the "Home" text can be seen.

### Basic Information

- Version with issue: 5.0.0.1874
- Last known good version: 4.8.0.1451
- Platform Target Frameworks: 
  - iOS:  14.3
  - Android: 10
  - UWP:  N/A
- Android Support Library / AndroidX Version: N/A
- NuGet Packages: Xamarin.Forms 5.0.0.1874, Xamarin.Essentials 1.6.0, NETStandardLibrary 2.0.3 (part of the VS Template)
- Affected Devices: iPhone 8 Plus, iPhone 12 Pro, Android Pixel 3 (+store) - affects all the other devices but I mainly tested these three

### Environment
<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.8.4 (build 30)
Installation UUID: 83e881c4-0337-47a0-8e5d-06eec2334f52
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	3.1.301
	3.1.300
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	3.1.5
	3.1.4
	2.1.23
	2.1.19
	2.1.18

=== .NET Core 3.1 SDK ===

SDK: 3.1.301

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.8.0.3 (Visual Studio Community)
Hash: c51fabee8
Branch: xcode12.3
Build date: 2020-12-10 21:05:05-0500

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/liammccormick/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/liammccormick/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808040030
Git revision: eaa21a8983aa5c4bcf6a665892478b4f3d413418
Build date: 2020-12-10 11:06:12-05
Build branch: release-8.8
Xamarin extensions: eaa21a8983aa5c4bcf6a665892478b4f3d413418

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Sat Oct 31 00:07:11 PDT 2020
    root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
```

</details>

### Build Logs
None

### Screenshots
Version 4.8.0.1451 and iPhone 12 Pro - working as expected
<img width="393" alt="iPhone12Pro_xamarin_version_4 8 0 1451" src="https://user-images.githubusercontent.com/36994658/104765663-250d3980-5761-11eb-9228-91a282cd9339.png">

Version 4.8.0.1451 and iPhone 8 Plus - working as expected
<img width="398" alt="iPhone8Plus_xamarin_version_4 8 0 1451" src="https://user-images.githubusercontent.com/36994658/104765757-4ec66080-5761-11eb-82a0-bdb2035391f1.png">

Version 5.0.0.1874 and iPhone 12 Pro - **not working as expected**
<img width="385" alt="iPhone12Pro_xamarin_version_5 0 0 1874" src="https://user-images.githubusercontent.com/36994658/104765805-64d42100-5761-11eb-959b-e016e14eb64f.png">

Version 5.0.0.1874 and iPhone 8 Plus - **not working as expected**
<img width="384" alt="iPhone8Plus_xamarin_version_5 0 0 1874" src="https://user-images.githubusercontent.com/36994658/104765849-7b7a7800-5761-11eb-938e-3e0e3c19c0b9.png">

### Reproduction Link
[https://github.com/liammc44/XamarinError](url)

### Workaround
None

**Comment by liammc44** [comment]
Workaround - the **temporary fix** is to downgrade back to Xamarin.Forms v4.8.0.1451, but obviously the issue still needs fixed so that I can eventually use 5.0

**Comment by PureWeen** [comment]
Fixed here
https://github.com/xamarin/Xamarin.Forms/pull/13319

You can test via the nightlies
https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds

**Comment by shalinasanga** [comment]
v4.8.0.1821 also good

**Comment by bcaceiro** [comment]
I've downloaded the latest SR form V5 and the problem remains. TitleView does not show up.

**Comment by MelissaW990** [comment]
Still encountering this issue on XF version 5.0.0.1905

**Comment by NunoBem** [comment]
The only workaround is downgrade?? in the new XF 5.0.0.1905 still persists.

**Comment by shalinasanga** [comment]
This is partly fixed in xamarin forms version 5.0.0.2012.
In 5.0.1.1965-nightly same UI working fine, but not in 5.0.1.2008-nightly

**xaml for UI**
` <Shell.TitleView>
        <Grid ColumnDefinitions="20,*,30">
            <Image x:Name="FilterImg" Source="icn_filter_white.png">               
            </Image>
            <Frame x:Name="SearchFrame" Grid.Column="1" 
                   CornerRadius="15" Padding="5" HasShadow="False" VerticalOptions="Center">
                <StackLayout Orientation="Horizontal"  VerticalOptions="Center"
                         HorizontalOptions="CenterAndExpand" >
                    <Image Source="icn_search_white.png" VerticalOptions="Center" />
                    <Label Text="{Binding SelectedResource.Name}" HorizontalOptions="CenterAndExpand"
                           VerticalOptions="Center" TextColor="White"
                            LineBreakMode="TailTruncation" />
                </StackLayout>
            </Frame>
            <Image Grid.Column="2" Source="icn_add_reservation_white.png">
            </Image>
        </Grid>
    </Shell.TitleView>`

**version 5.0.0.2012 Screen shot**

![Screenshot 2021-02-16 at 8 20 04 AM](https://user-images.githubusercontent.com/6724310/108014568-2bc6ef00-7034-11eb-8e9e-a1eb1ca0551d.png)

**version 5.0.1.1965-nightly screen shot**

![Screenshot 2021-02-16 at 8 30 29 AM](https://user-images.githubusercontent.com/6724310/108014612-4305dc80-7034-11eb-8fad-2002da26da9e.png)

**Comment by bcaceiro** [comment]
I can confirm, I have the same issue using a Grid, the last column isn't correctly calculated.

**Comment by davidaramantSEP** [comment]
Is there another bug currently open for this? We are still stuck on Xamarin Forms 4.8 because of these `TitleView` issues. @PureWeen

**Comment by davidaramantSEP** [comment]
Opened a brand new bug that points back to this one: https://github.com/xamarin/Xamarin.Forms/issues/13949
