### ISSUE TITLE
[Bug] CarouselView System.ArgumentOutOfRangeException when adding and removing at same time

### ISSUE THREAD

**Issue by ichijikuibo** [xamarin/Xamarin.Forms#13458]
### Description

When both adding a removing to a ObservableCollection bound to a CarouselView the application crashes. I have tested it on a blank application too.

I spent that much time trying to determine exactly what was causing it I eventually downloaded the Xamarin.Forms source code to help locate the problem. The problem is in the Xamarin.Forms.Platform.Android.CarouselViewRender method CollectionItemsSourceChanged.

			Device.BeginInvokeOnMainThread(() =>
			{

				SetCurrentItem(carouselPosition);
				UpdatePosition(carouselPosition);

With the steps mentioned below carouselPosition is 1 when there is only 1 item in the collection. When stepping through the method is called 3 times before the SetCurrentItem is called for the first time because it is unable to use the main thread untill my code finishes by then its already changed the collection to a single item. Code above that means that position is reset to 0 when removing first which is why the problem only happens when adding first the removing.

### Steps to Reproduce

1. Add 2 items to a CarouselView's bound ObservableCollection 
2. Move the CarouselView to the 2nd item
3. Add a third item and remove the first 2 within the same method

### Expected Behavior
Single item to be displayed

### Actual Behavior
Crash with error System.ArgumentOutOfRangeException

### Basic Information

- Version with issue: 5.0.0.1874
- Last known good version: 4.8.1821 but not tested very well
- Platform Target Frameworks: Android
  - Android: 11
- NuGet Packages: several but none affect it
- Affected Devices: At least the android emulator(unable to test on phone due to it using gps and not currently able to test properly) 

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA828
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.557.25636
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.557.25636
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.557.25636
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.557.25636
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.8.20241.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.8.20241.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.8.20241.2
Conda support for Python projects.

Python - Django support   16.8.20241.2
Provides templates and integration for the Django web framework.

Python - IronPython support   16.8.20241.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.8.20241.2
Profiling support for Python projects.

SQL Server Data Tools   16.0.62012.31170
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.30608.117
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   16.0.30608.117
Visual C++ for Cross Platform Mobile Development (iOS)

Visual C++ for Linux Development   1.0.9.30608
Visual C++ for Linux Development

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   4.8.2.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.261 (d16-8@bb99248)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.8.0.3 (c51fabee8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```

</details>

### Workaround

Remove from the collection first then add(still think it might still be posible to crash like this but it is better)

**Comment by ichijikuibo** [comment]
That work around isn't very good it can still happen seems time it takes to free up the main thread affects it too.

**Comment by PureWeen** [comment]
@ichijikuibo can you attach your `I have tested it on a blank application too.` ?

**Comment by PureWeen** [comment]
Also @ichijikuibo can you test on the latest SR release of Xamarin.Forms?

**Comment by ichijikuibo** [comment]
[CarouselView Crash.zip](https://github.com/xamarin/Xamarin.Forms/files/5845855/CarouselView.Crash.zip)
I tested on version 1905 today and it still happens

**Comment by ichijikuibo** [comment]
Just discovered this also happens in iOS as well as in Android

**Comment by jsuarezruiz** [comment]
```
[mono] Unhandled Exception:
[mono] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
[mono] Parameter name: index
[mono]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.61(intptr,intptr,intptr)
[mono]   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.61(intptr,intptr,intptr)
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
[mono-rt] Parameter name: index
[mono-rt]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.61(intptr,intptr,intptr)
[mono-rt]   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.61(intptr,intptr,intptr)
[HostConnection] HostConnection::get() New Host Connection established 0xe9f167c0, tid 8476
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
```

**Comment by rmarinho** [comment]
This is fixed on 5.0.0.1931

**Comment by ichijikuibo** [comment]
It still happens on version 5.0.0.2012
[CarouselView Crash.zip](https://github.com/xamarin/Xamarin.Forms/files/5977461/CarouselView.Crash.zip)

https://user-images.githubusercontent.com/61333434/107873875-9ac60b80-6ead-11eb-8913-48bbd7412758.mp4

**Comment by AimedNuu** [comment]
Getting these crashes with 5.0.0.2012 on both Android and iOS

**Comment by ichijikuibo** [comment]
I don't think they are going to see these comments I think I will open up a new one and copy the details.
