### ISSUE TITLE
[Bug] Xamarin Shell: Android java.lang.RuntimeException

### ISSUE THREAD

**Issue by breetzn** [xamarin/Xamarin.Forms#14063]
### Description
After updating to Xamarin Forms 5.0 and releasing a new build of my app, I am seeing this stack trace show up in the google play console. I haven’t been able to reproduce it locally. The end of the stack trace leads me to believe there might be an issue with Xamarin Shell in XF 5.0.0.

### Steps to Reproduce
I'm unsure. Seems to be happening on multiple SDKs. I have not been able to reproduce locally.

### Expected Behavior
No crash

### Actual Behavior
Seems to be crashing pretty frequently on a wide variety of devices.

### Basic Information
Stack trace from google play console:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3792)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3968)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2307)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8506)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: androidx.fragment.app.Fragment$InstantiationException: 
  at androidx.fragment.app.Fragment.instantiate (Fragment.java:628)
  at androidx.fragment.app.FragmentContainer.instantiate (FragmentContainer.java:57)
  at androidx.fragment.app.FragmentManager$3.instantiate (FragmentManager.java:483)
  at androidx.fragment.app.FragmentStateManager.<init> (FragmentStateManager.java:85)
  at androidx.fragment.app.FragmentManager.restoreSaveState (FragmentManager.java:2714)
  at androidx.fragment.app.FragmentController.restoreSaveState (FragmentController.java:198)
  at androidx.fragment.app.FragmentActivity$2.onContextAvailable (FragmentActivity.java:149)
  at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable (ContextAwareHelper.java:99)
  at androidx.activity.ComponentActivity.onCreate (ComponentActivity.java:307)
  at androidx.fragment.app.FragmentActivity.onCreate (FragmentActivity.java:269)
  at androidx.appcompat.app.AppCompatActivity.onCreate (AppCompatActivity.java:115)
  at crc647afa4e63b6630bdc.MainActivity.n_onCreate (Native Method)
  at crc647afa4e63b6630bdc.MainActivity.onCreate (MainActivity.java:38)
  at android.app.Activity.performCreate (Activity.java:8198)
  at android.app.Activity.performCreate (Activity.java:8182)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1309)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3765)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Constructor.newInstance0 (Native Method)
  at java.lang.reflect.Constructor.newInstance (Constructor.java:343)
  at androidx.fragment.app.Fragment.instantiate (Fragment.java:610)
  at Caused
  at Java.Interop.TypeManager.n_Activate
  at mono.android.TypeManager.n_activate (Native Method)
  at mono.android.TypeManager.Activate (TypeManager.java:7)
  at crc643f46942d9dd1fff9.ShellItemRenderer.<init> (ShellItemRenderer.java:26)
```

- Version with issue: 5.0.0
- Platform Target Frameworks:
  - Android: SDK 28
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

**Comment by jsuarezruiz** [comment]
@breetzn It happens in several SDKs, could you indicate those that appear in logs (28, etc)?
For trying to obtain more information, it seems according to logs and exception when initializing `ShellItemRenderer`, could you indicate the visual structure used in Shell (flyout, etc)?

**Comment by breetzn** [comment]
@jsuarezruiz I can see that it happens for SDKs 30, 29 and 28.

For the Shell structure I am just using the `<TabBar>`, no Flyout. Would it help to see my AppShell.xaml?

**Comment by fmorrill** [comment]
Ok si es algo general pedir al usuario reiniciar la app, pero que grabe el inventario. No lo veo grave. Solo indicar en un manual que va a cerrar la app

**Comment by Jouna77** [comment]
it's also happening to me in different projects with Shell .
After a while, I finally managed to replicate this on a clean xamarin flyout demo:
![Untitled Project](https://user-images.githubusercontent.com/24820069/113496872-3aba1180-94bb-11eb-80ca-cc9688e5fd9d.gif)
https://github.com/Jouna77/AppShellBug_14063
What i did to replicate this was:

1. Adding the nugget package: Xamarin.AndroidX.Legacy.Support.V4 Ver. 1.0.0.7
2. Change any system setting like:
* Day time  
* Language

Since the error says "Unavailable to find default constructor" may be missing some overloaded or empty constructor on ShellItemRender?

**Comment by fmorrill** [comment]
Que bien Jon, investigue un poco a la competencia y mañana te comento porque no se inmuta el programa cuando pones el lector, sigue funcionando.SaludosIng. Fernando Morrill
-------- Mensaje original --------De: Jonathan Eduardo García García ***@***.***> Fecha: 3/4/2021  8:44 p. m.  (GMT-06:00) A: "xamarin/Xamarin.Forms" ***@***.***> CC: fmorrill ***@***.***>, Comment ***@***.***> Asunto: Re: [xamarin/Xamarin.Forms] [Bug] Xamarin Shell: Android java.lang.RuntimeException (#14063) 
it's also happening to me in different projects with Shell .
After a while, I finally managed to replicate this on a clean xamarin flyout demo:

https://github.com/Jouna77/AppShellBug_14063
What i did to replicate this was:

Adding the nugget package: Xamarin.AndroidX.Legacy.Support.V4 Ver. 1.0.0.7
Change any system setting like:


Day time
Language

Since the error says "Unavailable to find default constructor" may be missing some overloaded or empty constructor on ShellItemRender?

**Comment by santoshpmca** [comment]
facing exact same stack trace in appcenter since releasing latest Android build today morning.

@Jouna77 , could you please downgrade XF from 5.0.0.2012 to 5.0.0.1931 in your https://github.com/Jouna77/AppShellBug_14063 and check? it's a hunch though.

**Comment by Jouna77** [comment]
@santoshpmca  Already tried downgrading to 5.0.0.1931 with no luck.
I remember they used to be a parameterless constructor in custom renders nut it got deprecated. 
Maybe that's what is missing since ShellItemRenderer has no parameterless constructor.
For example:
```
[System.Obsolete]
public BorderlessDatePickerRenderer()  //is this missing?
{
}

public BorderlessDatePickerRenderer(Context context) : base(context) //new context constructor
{
}
```

**Comment by ouma** [comment]
Facing the same issue here after update

**Comment by PureWeen** [comment]
Can you try the nugets referenced here?

https://github.com/xamarin/Xamarin.Forms/issues/13843#issuecomment-819121845

**Comment by happyonee** [comment]
> Can you try the nugets referenced here?
> 
> [#13843 (comment)](https://github.com/xamarin/Xamarin.Forms/issues/13843#issuecomment-819121845)

I have the same problem.
I try your way，but no effect.

**Comment by happyonee** [comment]
> 自今天早晨发布最新的Android版本以来，在应用中心面临完全相同的堆栈跟踪。
> 
> @Jouna77，请您在 https://github.com/Jouna77/AppShellBug_14063[和检查](https://github.com/Jouna77/AppShellBug_14063)中将XF从5.0.0.20.2012降级为5.0.0.1931？不过这是个预感


The same thing happens when I change the theme.
In your way, the problem is solved.

Thanks!

**Comment by happyonee** [comment]
> facing exact same stack trace in appcenter since releasing latest Android build today morning.
> 
> @Jouna77 , could you please downgrade XF from 5.0.0.2012 to 5.0.0.1931 in your https://github.com/Jouna77/AppShellBug_14063 and check? it's a hunch though.

The same thing happens when I change the theme.
In your way, the problem is solved.

Thanks!

**Comment by ouma** [comment]
> Facing the same issue here after update

I unistalled  Xamarin.Google.Android.Material 1.3.0.1  leaving the XF dependency of 1.2.1.1.
No longer facing the issue.

**Comment by ChristopherStephan** [comment]
Why was this issue closed? We can still reproduce it in our Shell app, after changing the system language and reopen the app.

> System.NotSupportedException: Unable to find the default constructor on type Xamarin.Forms.Platform.Android.ShellItemRenderer.  Please provide the missing constructor. ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
  at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
  at java.lang.Error: Java callstack:
  at at mono.android.TypeManager.n_activate(Native Method)
  at at mono.android.TypeManager.Activate(TypeManager.java:7)
  at at crc643f46942d9dd1fff9.ShellItemRenderer.<init>(ShellItemRenderer.java:26)
  at at java.lang.reflect.Constructor.newInstance0(Native Method)
  at at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
  at at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
  at at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
  at at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
  at at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
  at at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
  at at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
  at at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
  at at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
  at at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:297)
  at at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
  at at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
  at at crc64a26300b8fa2d9892.MainActivity.n_onCreate(Native Method)
  at at crc64a26300b8fa2d9892.MainActivity.onCreate(MainActivity.java:38)
  at at android.app.Activity.performCreate(Activity.java:7136)
  at at android.app.Activity.performCreate(Activity.java:7127)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
  at at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4784)
  at at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4693)
  at at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loop(Looper.java:193)
  at at android.app.ActivityThread.main(ActivityThread.java:6669)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
  --- End of inner exception stack trace ---
  at Java.Interop.TypeManager.n_Activate (System.IntPtr jnienv, System.IntPtr jclass, System.IntPtr typename_ptr, System.IntPtr signature_ptr, System.IntPtr jobject, System.IntPtr parameters_ptr) [0x000be] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:163
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.2(intptr,intptr,intptr,intptr,intptr,intptr)

**Comment by MaxFelinger** [comment]
@ChristopherStephan and I updated Xamarin.Forms from 5.0.0.1931 to 5.0.0.2083 and the issue was gone.

PS: We also updated Xamarin.AndroidX.ConstraintLayout from 1.1.3.2 to 2.1.1.2
