### ISSUE TITLE
NavigationPage.SetHasNavigationBar false doesn't work inside MasterDetailPage

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1437]
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=51509

### Steps to Reproduce

```
Page masterContent = new ContentPage() { Title = "Master", BackgroundColor = Color.Red };
Page detailContent = new ContentPage() { BackgroundColor = Color.Blue };

NavigationPage.SetHasNavigationBar(detailContent, false);

MasterDetailPage masterDetail = new MasterDetailPage()
{
	Master = masterContent,
	Detail = new NavigationPage(detailContent)
};

MainPage = masterDetail;
```

### Expected Behavior
NavigatonBar shouldn't be visible.

### Actual Behavior
NavigatonBar is visible.

### Basic Information

- Version with issue: 2.3.4

### Reproduction Link

https://github.com/jkastner/XamFormsBugSample_51509

**Comment by rmarinho** [comment]
This is fixed on the latests

**Comment by ikerhg** [comment]
Hi,

We have updated to the latest version of Xamarin Forms (2.5.0.122203) but we still have the same error with the navigation bar.

We have set:

NavigationPage.SetHasNavigationBar(detailContent, false);

But same error.

![image](https://user-images.githubusercontent.com/29597397/34772754-74e0c416-f609-11e7-9e81-b511e35f9f78.png)


Is there any other property to set?

Thank you.

Regards,
Iker

**Comment by rmarinho** [comment]
@ikerhg can you upload a test case i used this one here https://github.com/jkastner/XamFormsBugSample_51509 and this works fine

**Comment by ikerhg** [comment]
Hi @rmarinho ,

We are trying to use a custom bar and open menu (so we need popover) when clicking a custom button in our bar. So we need to hide default from the start. This custom bar is only a stacklayout located in the top of the page with a button.

If we set Title to empty string and navigation bar to false in "BrowseEntriesPage.xaml" we still continue seeing the menu bar:

![2629eda3](https://user-images.githubusercontent.com/29597397/34777973-3d7ca2d4-f61c-11e7-9d9d-c38ce9c6a938.PNG)

![d9bb0348](https://user-images.githubusercontent.com/29597397/34777979-4156fbd4-f61c-11e7-8d7b-1bad1d852992.PNG)

Is there any way to hide the navigation bar always and show popover menu when clicking a button.

Thank you very much.

Regards,
Iker

**Comment by ikerhg** [comment]
Hi again @rmarinho ,

If we downgrade Xamarin.Forms to 2.3.2.127, it is working as we want, navigation bar is hidden from the begining and we can show popover menu when we want:

![217c7096](https://user-images.githubusercontent.com/29597397/34778985-340e3d7c-f61f-11e7-9b83-09e944f9398e.PNG)

![46d37b9f](https://user-images.githubusercontent.com/29597397/34778988-3654cb6e-f61f-11e7-938c-d72ec94bd934.PNG)

Thank you.

Regards,
Iker

**Comment by rmarinho** [comment]
Please upload a short sample so we can look at it. 

Thanks

**Comment by ibonsanvicente** [comment]
Hi @rmarinho,

I've tested this. You can check with your own project:

Change BrowseEntriesPage xaml from this:

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             Title="Browse Entries Page"
             BackgroundColor="DarkGray"
             x:Class="Test_NavPage.BrowseEntriesPage">

to this:

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             Title=""
             NavigationPage.HasNavigationBar="False"
             BackgroundColor="DarkGray"
             x:Class="Test_NavPage.BrowseEntriesPage">

When you launch the project you'll see how the top bar appears with empty title.

But if you downgrade Xamarin.Forms to the last working version before the bug appeared (2.3.2.127), with the same code the top bar won't appear (as expected since we are setting it that way).

Do you need me to upload your project with doengraded Xamarin version and those changes in BrowseEntriesPage?

**Comment by ibonsanvicente** [comment]
Hi again @rmarinho,

Here you have the downgraded (working) version. Check how the bar does not appear on first page with this Xamarin Forms version.

I haven't added any custom bar or means to show menu, it is not necessary dor the bug reproduction proposal.

[XamFormsBugSample_51509-master-2.3.2.127.zip](https://github.com/xamarin/Xamarin.Forms/files/1619484/XamFormsBugSample_51509-master-2.3.2.127.zip)

**Comment by ibonsanvicente** [comment]
Hi @rmarinho,

Shouldn't this bug be reopened?

Thanks,
Ibon

**Comment by 949f45ac** [comment]
Stumbled upon this same bug just now. It’s working fine on Android and iOS, but on UWP it’s broken. Please reopen and fix.

**Comment by DennisWelu** [comment]
I can confirm I still see this in our UWP app with the very latest Xamarin Forms update.

**Comment by rmarinho** [comment]
@ibonsanvicente this bug is about not being able to hide the bar, but seems your are complaining the oposite. that it doesn't show the bar?!

**Comment by rmarinho** [comment]
Oh ok this is 2.3.2 .. gotcha.

**Comment by DennisWelu** [comment]
Just a reminder of more background where this came from: https://bugzilla.xamarin.com/show_bug.cgi?id=51509. It is an issue in UWP where the bar does not hide but it should be hidden. It seems to hide properly after toggling the master view on/off.

**Comment by rmarinho** [comment]
@ibonsanvicente seems this only happens when using    MasterBehavior="Popover" right? 

@DennisWelu @ikerhg  are you using Popover too ?

**Comment by ibonsanvicente** [comment]
Hi @rmarinho,

Seems so: in our project we use Popover. If I change to Default then the bar does not appear, though Popover is the menu behaviour we need.

Cheers,
Ibon

**Comment by DennisWelu** [comment]
@rmarinho Yes true, Popover is what we are using as well.

**Comment by DennisWelu** [comment]
Behavior has changed but...anyone else still not seeing it all work right? My MasterDetailPage.MasterBehavior is set to ```MasterBehavior.Popover```...but with XF 3.1 out of the box for me SetHasNavigationBar(..., false) is still leaving a blank space at the top.  Then if I toggle the popover menu open/closed the space at the top goes away and is now replaced by a space at the bottom.  (The bottom space showing up is new behavior from previous... ) Almost as if the page content layout was not redone but it shifts up the height of the removed bar...

**Comment by charlesroddie** [comment]
This is not working for me in the latest XF 3.3.0.912540 . @rmarinho can you reopen pls?

```fsharp
let w  = new MainWindowV()
let np = new NavigationPage(w)
do  NavigationPage.SetHasNavigationBar(np, false)
do  base.MainPage <-
    MasterDetailPage(Master = new ContentPage(Title = "Master"), Detail = np, MasterBehavior = MasterBehavior.Popover)
```

![image](https://user-images.githubusercontent.com/19760720/48411757-6c8b7b80-e73a-11e8-849f-bc39cbc1ab76.png)

Also, it's odd that to remove a titlebar we need to wrap a ContentPage in a NavigationPage.

**Comment by ibonsanvicente** [comment]
Same behaviour for us with XF 3.3.0.967583

![screenshot_1](https://user-images.githubusercontent.com/34705594/48412639-8a121280-e745-11e8-82d4-00580939cc15.png)

**Comment by nicovos** [comment]
Please reopen this issue. On UWP this is still not working. To prevent flashing of navigation bar on Android I'm using XAML instead of code behind.

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Actemium.SCS.FieldForce.MobileClient.Views.AlertPage"
             Title="Error"
             NavigationPage.HasNavigationBar="False">

This work perfect in Android, but UWP has the issue that it does not remember the setting. Each time that I navigate back the navigation bar is displayed including the title and hamburger icon. When I navigate to a child page, then a blank navigation bar is displayed.

I can call code NavigationPage.SetHasNavigationBar(this, false); each time a page is created, but this does not fix the back button press scenario. Then the full navigation bar is still displayed. Till now I can not find a workaround to get this fixed.

This bug prevents me from building a custom navigation bar. So please reopen.

Thanks.

**Comment by AntonEmelyancev** [comment]
+1 @nicovos 
Actually setting SetHasNavigationBar false/true doesn't help if navigation page is a child of TabbedPage: in UWP navigating back to tab with NavigationPage (which nav bar is hidden) still preserves space for that hidden nav bar. Haven't found workaround  for this issue on TabbedPage so far.

**Comment by AntonEmelyancev** [comment]
I've created separate [issue](https://github.com/xamarin/Xamarin.Forms/issues/4531) since there is no attention here.

**Comment by joseluisct** [comment]
This issue also happens in WPF with Xamarin.Forms 3.4
