### ISSUE TITLE
[iOS] Device.OpenUri does not use AbsoluteUri anymore

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1651]
### Description

migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=60691

I'm loading a phone number with Device.OpenUri, in commit [72699e34b2f4b3e8a939eebe03240ca7511b50e7](https://github.com/xamarin/Xamarin.Forms/commit/72699e34b2f4b3e8a939eebe03240ca7511b50e7#diff-9473374f7bd43cfcfc1edd0566fbda94) the way URLs are loaded was changed.

It used to do

`UIApplication.SharedApplication.OpenUrl(new NSUrl(uri.AbsoluteUri));`

it was changed to

`var url = NSUrl.FromString(uri.ToString()) ?? new NSUrl(uri.Scheme, uri.Host, uri.LocalPath);`

and forms currently uses `uri.OriginalString`

The current implementation makes the call fail with

```
"NSInvalidArgumentException"
"*** -[NSURL initWithScheme:host:path:]: path (555)%20555-5511 is not absolute."
```

Using uri.AbsoluteUri works.

Why was that changed?
Can it be changed back?

### Steps to Reproduce

Run 

```
try
{
Device.OpenUri(new Uri("telprompt:(555) 555-5511"));
}
catch (Exception ex)
{
System.Diagnostics.Debug.WriteLine(ex.ToString());
}
```

### Expected Behavior
Phone is brought up with that number inputted.

### Actual Behavior
Exception is hit

### Basic Information

- Version with issue: Latest 2.5.0.122203
- Last known good version: w/e the version was before commit 72699e34b2f4b3e8a939eebe03240ca7511b50e7 ](https://github.com/xamarin/Xamarin.Forms/commit/72699e34b2f4b3e8a939eebe03240ca7511b50e7#diff-9473374f7bd43cfcfc1edd0566fbda94)
- IDE: VS 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android: No
  - UWP:  No
- Android Support Library Version: No
- Nuget Packages: Just Forms
- Affected Devices: iPhone 6

### Reproduction Link
Not needed

**Comment by DavideSiav** [comment]
I've a serious problem with Device.OpenUri command and redirect URL in query string after updating to the last Xamarin Forms version.
In my application I've integrated an authentication to an OAuth server that at application start opens the browser on a specific page passing parameters in GET.

Among these parameters there is a redirect URL to my application which the authentication server invokes passing the result of the login operation.
Up to version 2.1 everything worked correctly, and after upgrading to version 2.5 of Xamarin the opening of the browser no longer works correctly.

The page opened with Device.OpenUri is like this:
https://myauthenticationserver?param_1=01234&param_2=56789&redirect_uri=myapplication://authentication

With Xamarin 2.1 Device.OpenUri works fine but in Xamarin 2.5 the URL passed to Device.OpenUri is changes in this
https://myauthenticationserver?param_1=01234&param_2=56789&redirect_uri=myapplication:/authentication

The "redirect_uri" parameter is changed and one of the "/" is deleted.
This problem occurs only in iOS while in Android it works correctly.

Can someone help me?

**Comment by rmarinho** [comment]
fixed by #1311

**Comment by Microdec** [comment]
Am still getting this exact issue with Xamarin Forms 3.4.0 and iOS 11. 
Has this issue come back (assuming it was ever really fixed)?

**Comment by johnshardman** [comment]
Also seeing this with XF 3.4 with iOS 12
