### ISSUE TITLE
ListView.ItemTemplate = new DataTemplate(...); is not working... in uwp only (Xamarin.Forms 3.0)

### ISSUE THREAD

**Issue by Legolas87** [xamarin/Xamarin.Forms#2624]

**Comment by Legolas87** [comment]
What kind of information do you need? DataTemplate's constructor is just not executed

**Comment by PureWeen** [comment]
@Legolas87  a repro is useful because we're not really sure what you're referring to.  Especially in your last comment because the constructor is executed when you instantiate a DataTemplate like

*new DataTemplate()*

So I'm not really sure what you are referring to
Here's a quick repro I did that runs in UWP 

If you can modify this to demonstrate your issue that would be really helpful

[DataTemplate.zip](https://github.com/xamarin/Xamarin.Forms/files/2033320/DataTemplate.zip)

**Comment by bmacombe** [comment]
It's not just a codebehind vs xaml declaration issue.  I just found one page where UWP won't load any items and then an almost identical page will load them.

**Comment by bmacombe** [comment]
I just tried 3.1 pre 3, issue is present there also

**Comment by Legolas87** [comment]
I agree with @bmacombe , have same problem!

**Comment by bmacombe** [comment]
I wonder if 2976 is related to this problem.  I see code was just checked in recently

**Comment by bmacombe** [comment]
ListView = new ListView(); - fails

ListView = new ListView() {ItemsSource = new List<string>()}; - works as expected.  I think #2976 will resolve this.  @samhouts  @rmarinho

**Comment by bmacombe** [comment]
Setting the items source works in the code behind, but I haven't found a good work around for when the ListView is declared in Xaml and rendered before the ItemSource binding isn't null.

Do you have any idea when the fix in #2976 might make it into a release?

**Comment by linnkrb** [comment]
@bmacombe  I´m having the same problem as you, but I solved with ensuring that binded object never returns null. 

<ListView x:Name="BrandList"  ItemsSource="{Binding FilteredBrands}" ">
      
In my Viewmodel
      
private List<KeyValuePair<string, string>> filteredBrands;
        public List<KeyValuePair<string, string>> FilteredBrands
        {
            get
            {
                    if (filteredBrands == null)
                       { 
                        var temp = new List<KeyValuePair<string, string>>();
                        temp.Add(new KeyValuePair<string, string>(" ", " "));
                        return temp;
                       }
else
return filteredBrands;
 
                    }

  ...

**Comment by bmacombe** [comment]
@linnkrb Thanks, I might try something like that.  I did try a couple similar methods, but I think things were happening out of sequence so the first binding was still happening while it was null.

I think the fix from #2976 will resolve this...just need for it to get into a build, thought about switching to the nightly, but that probably has other risks :)

**Comment by samhouts** [comment]
#2976 is in 3.0.0.561731, available now on NuGet. Please give it a try and let us know if it does, in fact, resolve the issue. Thank you!

**Comment by bmacombe** [comment]
Well, bad news then..I'm already on  3.0.0.561731 and I still see the issue.  It sounds exactly like #2976 though.  I might try to put some more thought into how to create a simple repro.

I can confirm the following though, so it has something to do with the ItemSource being null

ListView = new ListView(); - fails
ListView = new ListView() {ItemsSource = new List()}; - works.

**Comment by PureWeen** [comment]
@bmacombe   your issue should be fixed by this PR
https://github.com/xamarin/Xamarin.Forms/pull/3023

Which will be part of 3.1

There were a few issues that are fixed in that PR that sound like what you are talking about

**Comment by bmacombe** [comment]
@PureWeen Thanks, I have been walking down the trail of related Issues, I don't think I made it to that one.

**Comment by bmacombe** [comment]
@PureWeen, I switched to the nightly build and can confirm this appears fixed!  There were other minor layout issues in UWP, but I'm going assume that is just from 3.2 not being ready.

**Comment by PureWeen** [comment]
@bmacombe  Possibly.....  Do the minor layout issues seem like regressions? So once you updated to nightly your layouts changed in a negative way?   

If the answer to all of that is yes and it's easy for you to tell me how I can see these issues that would be helpful.

**Comment by bmacombe** [comment]
@PureWeen yes, I didn't spend a lot of time looking at it other then verifying that the ListView was acting correctly.  I will switch a branch back over to the nightly and do a more complete review, hopefully tonight or tomorrow and get back with you.

**Comment by PureWeen** [comment]
Awesome thank you @bmacombe !!! Just trying to get ahead of any possible issues

**Comment by bmacombe** [comment]
@PureWeen 

I'm not sure this is ListView related, but it could be, it may be a nested layout issue.  Those items are in a ListView, using a DataTemplate.  The icon, title and bar are in a Grid, which hosts a content control that has the label and button below the bar in it.

I've only been able to test this in UWP, don't have a Mac with me to build iOS or an Android device.


3.2 Nightly

![image](https://user-images.githubusercontent.com/15127788/41629447-22ea8ef8-73ef-11e8-8752-f9ac12ee1213.png)

3.0 Latest on Nuget
![image](https://user-images.githubusercontent.com/15127788/41629571-c695345e-73ef-11e8-9d86-cc624bd12145.png)

This is the root control

 ```
<Grid Style="{StaticResource GridContent}" Margin="2,15" Padding="5">
        <Grid.Resources>
            <ResourceDictionary>
                <actionItems:ActionItemDataTemplateSelector x:Key="ActionItemDataTemplateSelector"></actionItems:ActionItemDataTemplateSelector>
            </ResourceDictionary>
        </Grid.Resources>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="0" />
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"></RowDefinition>
            <RowDefinition Height="Auto"></RowDefinition>
            <RowDefinition Height="Auto"></RowDefinition>
            <RowDefinition Height="Auto"></RowDefinition>
        </Grid.RowDefinitions>
        <images:ASCachedImage Grid.Column="0" Grid.RowSpan="3" Source="{Binding Source={x:Reference Self}, Path=ImageSource}"
                                  Style="{StaticResource ThumbnailCachedImageMicro}" VerticalOptions="Start">
            <images:ASCachedImage.GestureRecognizers>
                <TapGestureRecognizer Command="{Binding CommandAction}"></TapGestureRecognizer>
            </images:ASCachedImage.GestureRecognizers>
        </images:ASCachedImage>

        <!-- Title -->
        <Label Grid.Row="0" Grid.Column="1" Grid.ColumnSpan="2" Text="{Binding Title}" Style="{StaticResource LabelMediumBold}">
            <Label.GestureRecognizers>
                <TapGestureRecognizer Command="{Binding CommandAction}"></TapGestureRecognizer>
            </Label.GestureRecognizers>
        </Label>
        
        <BoxView Grid.Column="1" Grid.Row="1" Style="{StaticResource SeperatorBoxStandard}"></BoxView>

        <!-- Action Item Controls -->
        <StackLayout Grid.Column="1" Grid.Row="2" Grid.ColumnSpan="2" Style="{StaticResource StackLayoutStandard}" BindingContext="{Binding Source={x:Reference Self}, Path=ActionItemViewModel}"
                     Orientation="Horizontal">
            <Button Text="{Binding SnoozeText}" IsVisible="{Binding CanSnooze}"
                    Command="{Binding CommandSnooze}"></Button>
            <Button Text="{Binding DismissText}" IsVisible="{Binding CanDismiss}"
                    Command="{Binding CommandDismiss}"></Button>
        </StackLayout>

        <!-- Content -->
        <ui:ASItemControl Grid.Column="1" Grid.Row="3" Grid.ColumnSpan="2" 
                              ItemTemplate="{StaticResource ActionItemDataTemplateSelector}" Item="{Binding Source={x:Reference Self}, Path=ActionItemViewModel}">
            <ui:ASItemControl.GestureRecognizers>
                <TapGestureRecognizer Command="{Binding CommandAction}"></TapGestureRecognizer>
            </ui:ASItemControl.GestureRecognizers>
        </ui:ASItemControl>

      
    </Grid>
```

This is the XAML being loaded into the ASItemsControl...which is just a content control with a data template selector

```
<ContentView xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="AS.Mobile.DealerTools.Clients.Certification.ActionItems.ClientCertificationApprovalActionItemDetailsView">
    <StackLayout Orientation="Vertical">
        <Label Text="{Binding ClientDescription}" Style="{StaticResource LabelSmall}"></Label>
        <Button Text="Review Request" Command="{Binding CommandAction}"></Button>
    </StackLayout>
</ContentView>

```

**Comment by PureWeen** [comment]
@bmacombe   can you try the 3.1 release that was just pushed to nuget?

If you're still seeing a layout difference there between 3.0 and 3.1 can you open up a new issue?

**Comment by bmacombe** [comment]
@PureWeen Looks good in 3.1.0.583944!

![image](https://user-images.githubusercontent.com/15127788/41692632-e6c66464-74c6-11e8-96ce-8fab9751b1e7.png)

**Comment by SudeepSingh1502** [comment]
This bug is resolved in latest xamarin forms version 3.1 :)

**Comment by PureWeen** [comment]
Closing for now @Legolas87  let me know if the issue isn't resolved for you

**Comment by Legolas87** [comment]
I confirm, the bug is fixed.
