### ISSUE TITLE
[iOS] Secondary Toolbar Items overlapping

### ISSUE THREAD

**Issue by crazynolde** [xamarin/Xamarin.Forms#2798]
### Description
As originally reported at https://bugzilla.xamarin.com/show_bug.cgi?id=59868, toolbar items are still overlapping.

### Steps to Reproduce
1. Create a Xamarin Forms App
2. Create a Page with 3 or more Toolbar Items that have images
3. Run it on iOS 11 Simulator or iPhone

### Expected Behavior
The Toolbar Items are shown side by side

### Actual Behavior
The Toolbar Items are overlapping

### Basic Information
- Version with issue: 2.5 and newer
- Last known good version: unknown
- IDE: Visual Studio 15.7.2
- Platform Target Frameworks: 
  - iOS: 11
- Nuget Packages:
  - Xamarin.Forms: 3.0.0.482510
- Affected Devices:
  - iOS 11 Devices

### Screenshots
![image](https://user-images.githubusercontent.com/29125873/40353475-e2c5ed70-5db1-11e8-9939-a3ef0e980544.png)

### Reproduction Link
```
var page = new ContentPage()
			{
				ToolbarItems =
				{
					new ToolbarItem{Icon = "bank.png"},
					new ToolbarItem{Icon = "calculator.png"},
					new ToolbarItem{Icon = "coffee.png"},
					new ToolbarItem{Icon = "bank.png", Order = ToolbarItemOrder.Secondary},
					new ToolbarItem{Icon = "calculator.png", Order = ToolbarItemOrder.Secondary},
					new ToolbarItem{Icon = "coffee.png", Order = ToolbarItemOrder.Secondary},
				}
			};

			return new NavigationPage( page);
```
https://bugzilla.xamarin.com/show_bug.cgi?id=59868
https://github.com/xamarin/Xamarin.Forms/pull/1208

**Comment by timrisi** [comment]
The same thing happens with text secondary toolbar items, so it doesn't have to have images.

**Comment by crazynolde** [comment]
does anyone know a workaround?

**Comment by timrisi** [comment]
So far my workaround has been to not use the secondary toolbar items and just do 3 buttons across the top, which is rather less than ideal since it means I get the buttons on android as well instead of the normal secondaries.

**Comment by crazynolde** [comment]
@rmarinho @samhouts Today i updated my app to Xamarin.Forms version 3.1.0.550168-pre3 but unfortunately, the bug is still not fixed, as you can see on my sample screenshots. As before, the toolbar renders well after i do a portrait / landscape rotation. The initial rendering is a little bit different as the items are one above the other now.

![sample 1](https://user-images.githubusercontent.com/29125873/41109680-ddec247c-6a77-11e8-88c8-1d92208f11be.png)

![sample 2](https://user-images.githubusercontent.com/29125873/41109681-de19dff2-6a77-11e8-99f2-494abc2f4f7d.png)

**Comment by volcano619** [comment]
Still remains Unsolved in 15.7.3 and Forms v3.0.0.550146

**Comment by rmarinho** [comment]
Hi @volcano619 can you try 3.1.1-pre3 or pre4 should be fixed there.

@crazynolde ohh that's bad... :/ but I just tried and seems fixed on 3.1.0 with the repro you provided , can you send me a project I can look. 

Thanks.


![simulator screen shot - iphone x - 2018-06-11 at 14 03 24](https://user-images.githubusercontent.com/1235097/41233155-74cdaec8-6d80-11e8-87d9-6c08ac86782c.png)

**Comment by volcano619** [comment]
@rmarinho Hey thanks a lot for a quick response,that actually did the trick,updating to the pre-release :D

**Comment by crazynolde** [comment]
@rmarinho I will try to extract a sample application that still reproduces the issue… otherwise i send you the application itself to me@ruimarinho.net, would that be okay?

**Comment by rmarinho** [comment]
sure, thanks for taking thetime to help us.

**Comment by crazynolde** [comment]
@rmarinho Fortunately i was able to reproduce the issue within a simple demo project. The First Screenshot shows the initial presentation, after the app pops up, with a faulty toolbar. The second screenshot shows the app after a landscape / portrait rotation, with a fixed presentation. Here is the sample project: 
[Overlapping.zip](https://github.com/xamarin/Xamarin.Forms/files/2119996/Overlapping.zip)

![faulty](https://user-images.githubusercontent.com/29125873/41668180-0eb259b4-74af-11e8-9bfa-55825670a855.png)

![okay](https://user-images.githubusercontent.com/29125873/41668191-129f932a-74af-11e8-8604-43317ba2cf7d.png)

**Comment by rmarinho** [comment]
Hi @crazynolde just had a look with your sample and it works fine in all devices and sims i tested.

make sure you clean the bin/obj folders and remove the old app from the device before testing
<img width="907" alt="capture_toolbar_items" src="https://user-images.githubusercontent.com/1235097/41713023-f11453d6-7543-11e8-9073-580c206364a0.PNG">

**Comment by crazynolde** [comment]
Hey @rmarinho thank you for checking my demo project.

As it turns out, my instructions to reproduce the issue were not correct. First you have to switch the tab page, then the toolbar turns overlapping. Sorry about that inaccuracy. I made a video to clarify the steps. I hope you can now reproduce the issue as well.

[video.zip](https://github.com/xamarin/Xamarin.Forms/files/2124367/video.zip)

**Comment by timrisi** [comment]
So I updated to 3.1.0.583944 and it PARTLY fixes the issue, but not entirely.  Similar to crazynolde, it appears fine when I first load up the app on the starting page, but as soon as I navigate to another page, it breaks.  If I push a new page with the view controller, I get completely blank toolbar items on the new page, though navigating back to the original page that one still looks fine.  On the othre hand, if I navigate to another tab on a tab bar similar to his video above, I get the same blank tool bars on the new page AND if I navigate back to the original page it's blank as well.

**Comment by rmarinho** [comment]
thanks guys for your patience, seems my fix didn't catch the real issue, I will try to find a better fix.

**Comment by crazynolde** [comment]
@rmarinho Did you try out your new fix with my reproduction demo?

**Comment by rmarinho** [comment]
@crazynolde  yes, 
@crazynolde  @volcano619  @timrisi  do you mind trying these packages..

[win.zip](https://github.com/xamarin/Xamarin.Forms/files/2133784/win.zip)

**Comment by crazynolde** [comment]
@rmarinho @samhouts it seems like we are getting closer to a fix ;)

As you can see on my new video, the separators are missing on first appearance. After you switch tabs, the separators will appear but the tools are not correctly centered anymore.

I hope the bug will be resolved with the necessary care.
[bandicam 2018-06-26 14-38-00-445.zip](https://github.com/xamarin/Xamarin.Forms/files/2138125/bandicam.2018-06-26.14-38-00-445.zip)

**Comment by volcano619** [comment]
i'm sorry i wasn't tracking this issue,do you guys still have an issue in this ?

**Comment by timrisi** [comment]
I see the same result as @crazynolde.  When the first view is displayed, there are no separators showing.  Switching to a new tab shows the separators but the toolbar items Arne't centered.  They ARE all at least showing in the right section now instead of overlapping each other.

**Comment by bruzkovsky** [comment]
@rmarinho I can confirm that your custom package fixed the issue for me. I still had it with the latest 3.1.0.583944, then updating to 3.2.0.606565 resolved it.

**Comment by crazynolde** [comment]
@rmarinho @timrisi @samhouts The bug itself has now been fixed. 

If you look at the toolbar meticulously, the centering would have to be corrected, as you can see on the screenshot. I know, xamarin forms is not intended to be a pixel perfect solution, but a discrepancy of 64 px is far away from pixel perfect. As this is immediately flashy for a detail-loving user, i would expect an correction.

Let me know what you think about that.

![2018-06-29_02-41-53](https://user-images.githubusercontent.com/29125873/42106259-ba7f9dda-7bd3-11e8-840c-66b8cf500f29.png)

**Comment by timrisi** [comment]
As @crazynolde said, it now is consistent and doesn't change from screen to screen, nor are any of the toolbar items overlapping, but they aren't centered.  The right item of the 3 seems centered, with the other 2 being offset to the right

**Comment by volcano619** [comment]
This is still open right ??

**Comment by samhouts** [comment]
To make it easier to track this new problem, we've created a new issue https://github.com/xamarin/Xamarin.Forms/issues/3457. Please follow that issue for updates. Thanks!
