### ISSUE TITLE
[UWP] ListView with null ItemsSource does not updates value if List is set to bound source

### ISSUE THREAD

**Issue by xxMUROxx** [xamarin/Xamarin.Forms#2981]
### Description

UWP List dos not show entries if initial source is `null`

### Steps to Reproduce

Create a ListView with a Binding to a source. The source must initially be `null`. During the OnNavigatedTo method, set the Source to some list.

If the source is initialized to new `List<sometype>()` then everything works.

### Expected Behavior
ListView shows entries
### Actual Behavior
ListView does not show entries
### Basic Information

- Version with issue: > 3.0.0.530893
- Last known good version: 3.0.0.482510
- IDE: VS2017
- Platform Target Frameworks:
  - UWP:  17134

I think this issue is somehow related with #2929

**Comment by mattrichnz** [comment]
@xxMUROxx #2929 fixed the crash if ItemsSource is null, but it seems #2512 introduced a regression.

We have found the same problem in XF 3.0.0-sr3, the issue does not occur in XF 3.0.0-sr1.
- Create a page with a ListView bound to an ObservableCollection with an item count = 0.
- Replace the ObservableCollection in the VM with a collection with items in it.
- **Bug: The ListView is not updated/reloaded with the new items.**

**Comment by mattrichnz** [comment]
@rmarinho @xxMUROxx  I have created a repro project which demonstrates this regression.

- Compare functionality in 3.0.0-sr1 and 3.0.0-sr3.
- Tapping the "Load Items" button replaces ItemsSource with a new ObservableCollection.
- Result? 3 items are added to the ListView in SR1 vs. no items added in SR3.

[ListViewRegressionUWP_3.0.0-sr3-Broken.zip](https://github.com/xamarin/Xamarin.Forms/files/2084933/ListViewRegressionUWP_3.0.0-sr3-Broken.zip)
[ListViewRegressionUWP_3.0.0-sr1-Working.zip](https://github.com/xamarin/Xamarin.Forms/files/2084934/ListViewRegressionUWP_3.0.0-sr1-Working.zip)

**Comment by activa** [comment]
This was fixed in PR #2976

**Comment by mattrichnz** [comment]
@activa @rmarinho @xxMUROxx No, I can confirm this is not yet fixed.
If you download the repro project above and update to XF 3.0.0-sr4 the issue still exists.
(Note: Release notes show #2976 is included in sr4, I am assuming this is correct?)

**Comment by mattrichnz** [comment]
@activa @rmarinho @samhouts Confirming this is still a problem in XF 3.0.0-sr4 on NuGet.

**Comment by PureWeen** [comment]
@mattrichnz   working on a similar issue over here https://github.com/xamarin/Xamarin.Forms/issues/3008

I'll test the use cases above as well

**Comment by mattrichnz** [comment]
@PureWeen Brilliant - Let me know if you need anything from me.
