### ISSUE TITLE
[UWP] : App crash when Loader and Alert popup collide.

### ISSUE THREAD

**Issue by ashishm29** [xamarin/Xamarin.Forms#3015]
### Description

If Loader is running and Any Alert pop's up app crashes with following error message
When multiple alerts are opened at the same time, UWP crashes with "Only a single ContentDialog can be open at any time."

   at Windows.UI.Xaml.Controls.ContentDialog.ShowAsync()
   at Xamarin.Forms.Platform.UWP.Platform.<ShowAlert>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Forms.Platform.UWP.Platform.<OnPageAlert>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

### Bugs Fixed
fixes #2369 - getting same error message.

### Steps to Reproduce

1.  Try to open Alert PopUp  while loader is running. 
2. App will not crash every time but if do fast process it will crash.

For Loader i am using
 Acr.UserDialogs - v7.0.1.

 private async void ButtonClickCommandReceiver()
        {
            try
            {
                UserDialogs.Instance.ShowLoading("Loading...");
                // Service call 
                await Application.Current.MainPage.DisplayAlert("Alert", "Add Item ?", "Yes", "No");
            }
            catch (System.Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }

### Expected Behavior
 - App should not crash

### Actual Behavior
 - App crashes with  following error message:

When multiple alerts are opened at the same time, UWP crashes with "Only a single ContentDialog can be open at any time."

### Basic Information

- Version with issue: 
Issue was their in XF 2.4.0.275 - pre3 version and now i am using XF - 3.0.0.482510 issue still exist.
- Last known good version: NA
- IDE: Microsoft Visual Studio Community 2017 
- Platform Target Frameworks: 
  - UWP: 16299
- Android Support Library Version: 
- Nuget Packages:
  Acr.UserDialogs - v7.0.1.
   XF - 3.0.0.482510
- Affected Devices: UWP

**Comment by samhouts** [comment]
This is likely fixed by #2526. Are you able to test with a nightly build? https://blog.xamarin.com/try-the-latest-in-xamarin-forms-with-nightly-builds/

**Comment by ashishm29** [comment]
Hi @samhouts 

As you said I have tried below Versions but issue still exist.
3.1.0.506097 - nightly
3.1.0.498643 - nightly
2.6.0.251661 

Please guide  me on this.

**Comment by samhouts** [comment]
Can you please attach a sample project that exhibits the issue? Thank you!

**Comment by ashishm29** [comment]
Hi @samhouts ,

please download sample project from below link :
https://github.com/ashishm29/Xam.MvvmSolution

Steps to Reproduce : 
1. Run Project.
2. Click on Add More Button.
3. App will crash.

Thanks.

**Comment by hartez** [comment]
This is a general issue with UWP; multiple `ContentDialog`s cannot be on the screen at the same time. The third-party component you're using (Acr.UserDialogs) )for displaying the Loading dialog is using a `ContentDialog`, and the Forms `AlertDialog` is a subclass of `ContentDialog`. There is simply no way to show an `AlertDialog` while the Loading dialog is displayed. 

One option for you might be to use the confirmation mechanism in Acr.UserDialogs; replace

`result = await Application.Current.MainPage.DisplayAlert("Alert", "Add Item ?", "Yes", "No");`
with
` result = await UserDialogs.Instance.ConfirmAsync("Alert", "Add Item ?", "Yes", "No" );`

Acr.UserDialogs uses the older `MessageDialog` class for confirmation dialogs, so there's no `ContentDialog` conflict.

**Comment by ashishm29** [comment]
@hartez 
**The code you suggested i have already tried this works fine.**
_result = await Application.Current.MainPage.DisplayAlert("Alert", "Add Item ?", "Yes", "No");
with
result = await UserDialogs.Instance.ConfirmAsync("Alert", "Add Item ?", "Yes", "No" );_

**But, UserDialogs has issue with this ActionSheetAsync.**
 _var res = await Application.Current.MainPage.DisplayActionSheet("Add Item ?", "Cancel", "", "YES", "NO");
with
_var res = await UserDialogs.Instance.ActionSheetAsync("Add Item ?", "Cancel", "",null, "YES","NO");__

**Above code doesn't work with UserDialogs.**

Please suggest.
Thanks.
