### ISSUE TITLE
[Android] Image on Button is not centered with text

### ISSUE THREAD

**Issue by clovs** [xamarin/Xamarin.Forms#3527]
### Description
The Image is not in the center on Button when displaying with a text.

### Steps to Reproduce

1. Create a Button with an image & text.
2. Set thee HorizontalOption to Fill&Expand.
3. You can see that the image is stick to the left border
4. If you change the position(Top,Right...) of the image it will stick on the position selected, not centered with the text

### Expected Behavior
The image have to stick the text on the center.

### Actual Behavior
The Image is stick to the border depends of the selected position.
I was searching a way to make a correction on UpdateBitmap
But PropertyName "Image" never pass to UpdateBitmap
```
        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == Button.TextProperty.PropertyName)
                UpdateBitmap();

            base.OnElementPropertyChanged(sender, e);
        }
```
### Basic Information
- Xamarin.Forms: 3.1.0.697729
  - Android: 8.1

**Comment by samhouts** [comment]
`OnElementPropertChanged` only fires when you change a property on an Element after it has been rendered on the screen. When are you setting the `Image` property? If you're setting it in the constructor, that will be handled by `OnElementChanged`. If you still need assistance with this issue, please reopen it and attach a small reproduction project. Thank you!

**Comment by clovs** [comment]
First thanks for your time,

Forget about the PropertyChanged (my bad, I was expected ImageProperty not TextProperty in sample)

The issue is about the image stick close to the border, depending of Button.ContentLayout.Position

The image is not centered and it's caused by:
- The SetCompoundDrawablesWithIntrinsicBounds function in [ButtonRenderer](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs) ligne 216 
when switching position.
- And the default Draw function.

-> [Here](https://gist.github.com/rajivnarayana/5224881) an implementation in Java of a Custom drawn Android button which aligns left drawable and its text to center.

Regards,

**Comment by kingces95** [comment]
@clovs If you have a small reproduction handing, would you mind attaching it?

**Comment by vecalion** [comment]
Does anyone have a workaround?

**Comment by jveltd** [comment]
> Does anyone have a workaround?

You could use the option of 'padding' on the button itself as a work around?

**Comment by vecalion** [comment]
> > Does anyone have a workaround?
> 
> You could use the option of 'padding' on the button itself as a work around?

Yep, that's what I've ended up with (I'm lucky to have a fixed width buttons in this project). Thanks

**Comment by mattleibow** [comment]
So, I have fixed this for Material, and encapsulated all the logic for button layout into a single place: https://github.com/xamarin/Xamarin.Forms/pull/4967

Right now, all that is needed to get the image in either place is a boolean flag. However, as this is a breaking change for the older renderers, we will probably not be able to change the behaviour.

However, there are some things we can do:
 - use material for your buttons
 - create a custom renderer and set that flag (if this is an option, then I can add a hook)
 - create an android specific (which you can set with styles)

**Comment by mattleibow** [comment]
To get this behaviour on Android, I added a platform specific (just like the `UseDefaultShadow` and `UseDefaultPadding`). The image next to the text will be the default for material buttons, so it will be consistent from the start.

**Comment by xamiell** [comment]
I'm having this issue on Android but on iOS works fine.
Xamarin.Forms Version: 4.8.0.1560
Seems like an old issue that still happening.

**Comment by Huaba93** [comment]
@mattleibow could you provide us with sample code of what we need to change in a custom renderer/android specific to fix this?

A fix is absolutely necessary, otherwise the "Image" feature cannot be used.

imho there are some related issues:
#6632
#9227

**Comment by xamiell** [comment]
Hi!
Any update?

**Comment by xamiell** [comment]
Any update?

**Comment by vmp1r3** [comment]
This is still not fixed for such a long period?

**Comment by Huaba93** [comment]
I don't think this will be resolved yet. I worked around it with my custom button and touch effect.

**Comment by vmp1r3** [comment]
Probably we will not see any updates on Xamarin, since MAUI is released

**Comment by Bohdandn** [comment]
Ability to align icon with text is there but it is disabled by default. You can change it with custom renderer:
```
public class CustomButtonRenderer : Xamarin.Forms.Platform.Android.AppCompat.ButtonRenderer
{
	public CustomButtonRenderer(Context context)
		: base(context)
	{
		typeof(ButtonRenderer).GetField("_buttonLayoutManager", BindingFlags.Instance | BindingFlags.NonPublic)!
			.SetValue(this, new ButtonLayoutManager(this, true, false, false, true));
	}
}
```
Note second ctor arg of ButtonLayoutManager.
