### ISSUE TITLE
[Android/iOS] MasterDetail back button accessibility

### ISSUE THREAD

**Issue by BioTurboNick** [xamarin/Xamarin.Forms#3795]
Google now detects accessibility issues with applications in its pre-launch testing.

One that it detected in mine was that the back button "may not have a label readable by screen readers".

**Comment by Francis-D** [comment]
I'm trying to understand the process flow for bugs. Should this be resolved in version 3.6? If so, is this set automatically, or do you have to explicitly set AutomationProperties.Name for the back button?

Also, how do I view the code changes for something like this?

**Comment by albertotirla** [comment]
it is still not working, running android 10 and talkback over here, it constantly says unlabeled button when on the back button. I tryed both with commentary(a chinese screen reader) and with the now dead samsung voice assistant, no luck, unfortunately all of them act the same, so it must be something in xamarin.  
# How to fix it?  
You can try one of the following:  
* make it so that every page that is popped on the screen, in stead of being shown with the help of fragments, to be displayed in it's own, separate activity. This way, xamarin.forms developers can more easely make it behave like a native android app to accessibility services users, like talkback. One more thing regarding this, when using fragments, it might not affect the visual layout in any way, however for tb users it's kinda frustrating, since the screen reader doesn't move focus to the first view on the page, however it sits somewhere undefined, having to manually swipe to see that something indeed changed on the screen at all. As a xamarin dev and a visually empaired person, I find it a bit frustrating I can't at least find an attribute or project-level property or something that would allow me to switch to the above described mode, the one where each page is in its own activity.  
* if not, then you can add content_description on the back button, preferably something I as a dev can modify within code, as I may need to localise that string as well. If you can't manage the text to be able to be modifyed from code, at least please add the content_description attribute to that button, as we can't do it programatically.
