### ISSUE TITLE
[Shell] Adding ShellContent directly under ShellItem causes XAML editor warning in VS

### ISSUE THREAD

**Issue by kzu** [xamarin/Xamarin.Forms#3864]
Using [Gastropods](https://github.com/davidortinau/Gastropods) sample and XF version `3.2.0.599850`:

![image](https://user-images.githubusercontent.com/169707/45887638-9f487180-bd92-11e8-8bfa-dbe1bef4dd9a.png)

`ShellSectionCollection` may need an overload receiving a `ShellContent` or something like that.

Likely same issue, but at the Shell level:

![image](https://user-images.githubusercontent.com/169707/45888436-67dac480-bd94-11e8-8b79-1d257cfea333.png)
Parent: #2415

**Comment by jassmith** [comment]
Yeah it seems we dont know how to deal with implicit conversion operators yet

**Comment by anthcool** [comment]
This is still cropping up in 4.0 stable but with MenuItems when you take them out of MenuItemCollection,  

![image](https://user-images.githubusercontent.com/5133304/58191264-6a6f2000-7c7b-11e9-9e87-8671780c77cb.png)

It builds and runs fine, but there are squigglies and XLS0503 errors...

**Comment by mgoertz-msft** [comment]
@anthcool  Could you please share a small repro project that illustrates the problem?

**Comment by PureWeen** [comment]
[Triage.zip](https://github.com/xamarin/Xamarin.Forms/files/3209216/Triage.zip)

@mgoertz-msft  here's a sample you can use that demonstrates a few different permutations of the problem

**Comment by anthcool** [comment]
Thanks for your help @PureWeen  Really appreciate your help on the live-stream as well today.  Is that SmartHotel360 example you were sharing at the end publicly available yet?  I went to go check for it on the repo but doesn't look like it.  Would love to take a look at that.

**Comment by Mikilll94** [comment]
Is it going to be solved?

**Comment by anthcool** [comment]
> Is it going to be solved?

I hope so.  I'm still seeing the errors on my end as well.  Using the latest version of VS 2019 and Xamarin.Forms 4.1...

**Comment by linda-dge** [comment]
I hope so too.  It would be different if it were a warning.

**Comment by gceaser** [comment]
Downloading the example from this page:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout

and loading the project in VS 2019 with XF V 4.1.0.581479, the XAML editor still displays the warnings though the project does compile and run.

**Comment by mgoertz-msft** [comment]
Please open a VS Feedback Ticket through Visual Studio's "Send Feedback" functionality. That way we can track this issue internally, and you will be able to get notified through the Developer Community site when it is fixed. Once created please post the URL here so people can upvote the issue. Thank you!

**Comment by mgoertz-msft** [comment]
No feedback ticket that I know of but I have fixed this in VS anyway. The fix will be part of 16.3 Preview 2.

**Comment by linda-dge** [comment]
Thank you!

I have been on vacation and haven't had time.

*Linda Rawson*


ᐧ

**Comment by quiary** [comment]
Just updated to vs community 16.2 and xamarin 4.1, the issue is still there. Can anyone fix this? Though the sample app compiles and runs, it's still verry frustrating to see thses err msgs, I mean, I download this sample from the xamarin official site, shouldn't it be run err free? Warnings, I can understand, cuz xamarin is in rapid dev, but see a list of errs really shook my faith in xamarin developement.

**Comment by mgoertz-msft** [comment]
@quiary I understand your frustration and I'm sorry for the inconvenience but it was too late for inclusion in 16.2.

As I said above, the fix will be part of **16.3 Preview 2**.

**Comment by PureWeen** [comment]
This appears to be fixed on the latest version of VS

If that is inaccurate let me know and we can reopen

**Comment by softlion** [comment]
It is back

![image](https://user-images.githubusercontent.com/190756/93660083-c3a3bb00-fa4b-11ea-84b6-9f4e934b75ee.png)

**Comment by mgoertz-msft** [comment]
@softlion Please open a feedback ticket from VS and, if possible, attach a little repro project. Thank you.
