### ISSUE TITLE
ImageCell ImageSource Issue: Images Not Showing After Latest Update (3.4.0.1008975).

### ISSUE THREAD

**Issue by CannoliSquid** [xamarin/Xamarin.Forms#4584]
### Description

The issue that is occurring in my project is very similar to the issue featured in the link below (Not my SO post, but as I said, the conditions are very similar. I cannot post my exact project, but if necessary I can create a whole new project to re-create the issue and post it here):

https://stackoverflow.com/questions/53337250/xamarin-forms-imagecell-not-displaying-the-image

No changes were made to my code or the files except for upgrading Visual Studio from 15.9.2 to 15.9.3 and upgrading Xamarin.Forms from 3.3.0.967583 to 3.4.0.1008975. Rolling back to Xamarin.Forms 3.3.0.967583 remedied the issue, alluding to an issue with 3.4.0.1008975.

### Steps to Reproduce

1. Have a Xamarin.Forms 3.3.0.967583 project with a ListView with ItemSource binding, made of up ImageCell components with text and ImageSource properties that are filled using bindings. My ListView is in the Master page of a MasterDetailPage. Opening the Master page shows the ListView filled with ImageCell objects that have images for icons and text.
2. Upgrade to Xamarin.Forms release 3.4.0.1008975.
3. Icon images in the ImageCells no longer appear in the ListView. The text does still appear however.

### Expected Behavior

The Images in the ImageCells (in the ListView) should appear.

### Actual Behavior

The Images in the ImageCells (in the ListView) do not appear any longer.

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version:  3.3.0.967583
- IDE: Microsoft Visual Studio Professional 2017; Version 15.9.3
- Platform Target Frameworks:
  - Android: 8.1
  - iOS: Not Tested
  - UWP: Not Tested
- Nuget Packages:
- Affected Devices: Android Emulators in Visual Studio

### Screenshots

See StackOverflow Link

### Reproduction Link

See StackOverflow Link

**Comment by samhouts** [comment]
[Issue4584.zip](https://github.com/xamarin/Xamarin.Forms/files/2631435/Issue4584.zip)

**Comment by matteozoni** [comment]
I have the same issue in masterdetail menu 

`                    this.Master = new ContentPage
                    {
                        Title = "Basic Setup",
                        Padding = new Thickness(0, tPadding, 0, 0),
                        Content = new TableView
                        {
                            Intent = TableIntent.Menu,
                            Root = new TableRoot
                    {
                        new TableSection("Basic (Wizard)")
                        {
                            new ImageCell
                            {
                                ImageSource =
                                    ImageSource.FromFile("BasicImage1.png"),
                                    Text = "1. " + Resource.MenuInstructions,
                                    Detail = Resource.Step1,
                                    Command = navigateCommand,
                                    CommandParameter = typeof(Views.Basic.Instruction),
                                    TextColor = Color.Black
                            },
......
`

**Comment by matteozoni** [comment]
sorry but lost carriage returns

**Comment by erickconcepcion** [comment]
Same problem from ver. 3.2.0.839982 (visible) -> ver.  3.4.0.1008975 (not visible).

**Comment by offbyoneBB** [comment]
For me, this issue still exists with 3.4 sr1 (also 3.5 pre2 and 4.0 pre2).
It works on UWP and iOS, but not Android. Images in the ImageCell of a ListView do not show.
Lastest working version is 3.3.0.967583

**Comment by Magendanz** [comment]
Also seeing this on v3.5.0.1006868

**Comment by g4mb10r** [comment]
Also seeing this issue in v3.5.0.129452. Please fix!

**Comment by PureWeen** [comment]
@offbyoneBB  @Magendanz  @g4mb10r  Can you create a new issue with a repro? I just tested in our control gallery and it's working for me. There's something about your combined experience that I'm obviously not testing for correctly.

**Comment by TheRubble** [comment]
> Also seeing this issue in v3.5.0.129452. Please fix!
I'm also seeing it on this version.

**Comment by ianthetechie** [comment]
I finally upgraded from v3.3.x to v3.5.x (after finally figuring out that I had to enable MultiDex cuz all these blasted deps skyrocket past some bizarre 16-bit limit... another problem Xamarin needs to address). I was delighted to find that recycling elements in list views finally works as advertised so you don't have to retain every single freaking element! At least on iOS...

My excitement on the Android side was predictably short-lived. How the heck can something so simple as this be broken?!? I fail to understand the Xamarin release engineering process. It's worse than Windows Update. Something breaks nearly every time. I don't understand why this issue is closed. Our app isn't even that complicated. This view in particular is just a simple view model-bound list...

**Comment by TheRubble** [comment]
Slight update, the latest version of forms where this isn't a bug for me is v3.3.0.912540 anything after that results in an empty image cell.

The URL that I'm loading is : https://via.placeholder.com/150

**Comment by PureWeen** [comment]
@TheRubble this will be fixed in the next SR of forms

**Comment by g4mb10r** [comment]
@PureWeen Thanks!!!!!!

**Comment by sassy224** [comment]
FYI, I updated to XF 3.5.0.169047 and the issue with ImageCell on Android is fixed.

**Comment by ianthetechie** [comment]
This is still not fixed. Using the latest VS 2019 Community for Mac + Xamarin.Forms 3.6.0.293080.
