### ISSUE TITLE
[Shell] Route navigation doesn't seem to work

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4970]
### Description

I'm trying to register a route and navigate to it, but it doesn't work.

Register the route in the Shell.xaml.cs:
```
Routing.RegisterRoute("takephoto", typeof(CameraPage));
```

Then navigate to that named route:
```
Shell.CurrentShell.GoToAsync("app:///gastropod/a/b/takephoto?payload=4.0", true);
```

This just returns  me to the home page. I can use other paths  before the "takephoto" route and it'll  put me on those pages, but never takes me to the `CameraPage` as desired.

I **can** navigate  to a route named in the Shell.xaml like this:

```
<ShellItem Route="toptabs" Title="Top Tabs" FlyoutIcon="iconXamarin.png" Style="{StaticResource QuaternaryShell}">
        <ShellSection Route="activity" Title="Activity" Icon="iconXamarin.png" >
            <ShellContent Route="shared" Title="Shared" ContentTemplate="{DataTemplate local:ActivityPage}" />
            <ShellContent Route="notifications" Title="Notifications" ContentTemplate="{DataTemplate local:NotificationsPage}" />
            <ShellContent Route="photo" Title="Photo" ContentTemplate="{DataTemplate local:CameraPage}" />
        </ShellSection>
    </ShellItem>
```

And then:

```
Shell.CurrentShell.GoToAsync("app:///gastropod/toptabs/activity/photo?payload=4.0", true);
```

### Basic Information

- Version with issue: 4.0-pre2

### Reproduction Link

Based on https://github.com/davidortinau/Gastropods
Parent: #2415

**Comment by Kelvinkins** [comment]
Any update on this issue?

**Comment by MSiccDev** [comment]
same here, the only way to navigate to pages outside of Shell in the current iteration is to use "old school" navigation. Even the TailwindTraders sample uses this approach, while the docs state navigation is possible using the Routing.RegisterRoute approach. Any update on this would be great as I recently started a new app with Shell (hoping it will be final until release).

**Comment by CliffAgius** [comment]
I am seeing the same thing I am also not able to pass any parameters I am trying the same as in the Gastropods sample by @davidortinau but nothing arrives.

call to navigate:
`await Shell.CurrentShell.GoToAsync($"app:///ncchub/safety/documents/pdf?url=test", true);`

Then a normal Property stub in the VM:
```
[QueryProperty("DownloadUrl", "url")]
public class PDFViewModel : BaseViewModel


 private string _downloadUrl;
        
 public string DownloadUrl
    {
       get { return _downloadUrl; }
       set { SetProperty(ref _downloadUrl, 
    }
```

The Navigation happens as I have had to copy the hack @davidortinau has done and place the page inside the Shell.Xaml even though it's registered, but the passed in url of test is not passed.

**Comment by kennethbernstrom** [comment]
I am experiencing the same problem! I cant navigate to any pages that is not declared in the shell file!

**Comment by MSiccDev** [comment]
In the meantime, I am using another hack...

Once the Shell is initialized, I extract the current ShellSection to get a reference to the INavigation (NavigableElement). I pass this reference to my existing INavigationService and navigate like I do in non-shell apps.  This way, I am at least able to break out of the Shell.

**Comment by PureWeen** [comment]
fixed by https://github.com/xamarin/Xamarin.Forms/pull/5852

**Comment by aloptrbl** [comment]
is this has fixed?

**Comment by muhammadghani** [comment]
It looks like this issue is still there in XF 4.4 to 4.5 pre-2
