### ISSUE TITLE
Using Compiled Bindings with Xamarin.Forms 3.5.0.129452 causes a Runtime Exception and Terminates the Application

### ISSUE THREAD

**Issue by inforithmics** [xamarin/Xamarin.Forms#5270]
### Description
following XAML compiles and throws a runtime exception

UWP:
System.ExecutionEngineException: 'Exception of type 'System.ExecutionEngineException' was thrown.'

WPF:
Managed Debugging Assistant 'FatalExecutionEngineError' : 'The runtime has encountered a fatal error. 
The address of the error was at 0x731a8f42, on thread 0x28a8. 
The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. 
Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:app21="clr-namespace:App21;assembly=App21"
             x:Class="App21.MainPage"
             x:DataType="app21:TestViewModel">        
    <StackLayout>
        <Entry IsEnabled="{Binding CanEdit}"/>                                                      
        <Label Text="{Binding Text}"/>
    </StackLayout>        
</ContentPage>
```
Text is a Property that is although in a Interface that is implemented by TestViewModel.
Somhow the Compiled Binding is generating IL that is not valid and crashes the runtime. In UWP it simply throws an exception and stops the application.

In WPF there is some more information but the Application is although stopped.

CodeBehind:

```
  [XamlCompilation(XamlCompilationOptions.Compile)]    
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            this.BindingContext = new TestViewModel();
        }
    }
```

Code:

```
    public sealed class TestViewModel : ITestViewModel
    { 
        public bool CanEdit { get; set; }
     
        public string Text { get; set; }
    }

    public interface ITestViewModel
    {         
        string Text { get; set; }
    }

```

### Steps to Reproduce

Run the attached Project and see the exception:

### Expected Behavior

No Exception during execution

### Actual Behavior

Exception that stops the Application:
On this Code Line

`this.BindingContext = new TestViewModel();`

### Basic Information

- Version with issue: 3.5.0.129452
- Last known good version: 3.4.0.1029999
- IDE: Visual Studio 2017 15.9.6, Visual Studio 2019 Preview 3
- Platform Target Frameworks: 
  - UWP:   16299 
- Nuget Packages: Xamarin.Forms
- Affected Devices: Simulator on Windows 10, 1809

### Reproduction Link

[App21.zip](https://github.com/xamarin/Xamarin.Forms/files/2868823/App21.zip)

**Comment by StephaneDelcroix** [comment]
I was unable to reproduce this on net47 (unit tests). see this branch 
https://github.com/xamarin/Xamarin.Forms/tree/fix_gh5270 (on top of 3.6.0)

**Comment by StephaneDelcroix** [comment]
but I indeed have an exception (different from yours) on 3.5.0. could you please try if this is fixed in 3.6.0 for your cases ? if it is, we can consider back porting the change to 3.5.0 has it is a potential regression

**Comment by inforithmics** [comment]
The original sample seems to work in Visual Studio 15.9.6 and crashes on Visual Studio 2019.
Maybe during narrowing down it started working in Visual Studio 15.9.6

Can you try the Test with this XAML sample this does not work in Visual Studio 15.9.6 and Visual Studio 2019

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:app21="clr-namespace:App21;assembly=App21"
             x:Class="App21.MainPage"
             x:DataType="app21:TestViewModel">        
    <StackLayout>
        <Entry x:DataType="app21:TestViewModel" IsEnabled="{Binding CanEdit}"/>                                                      
        <Label x:DataType="app21:TestViewModel" Text="{Binding Text}"/>
    </StackLayout>        
</ContentPage>
```

I tried the new sample with the Version 3.6.0 pre1 and it doesn't still not work.

**Comment by inforithmics** [comment]
I downloaded https://github.com/xamarin/Xamarin.Forms/tree/fix_gh5270 and executed the test
for me the test fails.

Maybe it is a problem with Windows 1809 and the latest Service Pack for .NET. On the machine .NET Framework 4.7.2 is installed

**Comment by toomasz** [comment]
I'm also getting ExecutionEngineException on UWP after upgrade from 3.4 to 3.5

**Comment by StephaneDelcroix** [comment]
> The change is that I set the x:DataType on every field explicitly.

this shouldn't have any effect

**Comment by inforithmics** [comment]
You are right it does not have any effect. Was maybe a Visual Studio recompilation issue.

**Comment by inforithmics** [comment]
When I remove the interface from TestViewModel it works I have dissasembled the Code generated and found following differences.

Following Code is generated:

```
 // [64 13 - 64 71]
    IL_000b: ldnull
    IL_000c: ldc.i4.0
    IL_000d: newobj       instance void valuetype [netstandard]System.ValueTuple`2<string, bool>::.ctor(!0/*string*/, !1/*bool*/)
    IL_0012: ret
    IL_0013: nop

    // [65 11 - 65 73]
    IL_0014: callvirt     instance string App21.TestViewModel::get_Text()
    IL_0019: ldc.i4.1
    IL_001a: newobj       instance void valuetype [netstandard]System.ValueTuple`2<string, bool>::.ctor(!0/*string*/, !1/*bool*/)
    IL_001f: ret
```

Without Interface follwing Code is generated

 ```
// [64 13 - 64 71]
    IL_000b: ldnull
    IL_000c: ldc.i4.0
    IL_000d: newobj       instance void valuetype [netstandard]System.ValueTuple`2<string, bool>::.ctor(!0/*string*/, !1/*bool*/)
    IL_0012: ret
    IL_0013: nop

    // [65 11 - 65 73]
    IL_0014: call         instance string App21.TestViewModel::get_Text()
    IL_0019: ldc.i4.1
    IL_001a: newobj       instance void valuetype [netstandard]System.ValueTuple`2<string, bool>::.ctor(!0/*string*/, !1/*bool*/)
    IL_001f: ret
```
The main difference is that a callvirt is made on the property with the interface
[MainPage.interface.txt](https://github.com/xamarin/Xamarin.Forms/files/2886317/MainPage.interface.txt)
[MainPage.withoutInterface.txt](https://github.com/xamarin/Xamarin.Forms/files/2886318/MainPage.withoutInterface.txt)

**Comment by akihikodaki** [comment]
I think the bug fixed by #5309 affects the code in the first comment.

**Comment by inforithmics** [comment]
With your check in https://github.com/xamarin/Xamarin.Forms/pull/5309  you have fixed the bug. Because with the newest nightly nuget package Compiled Binding now works. 
I although have run the unit test of https://github.com/xamarin/Xamarin.Forms/issues/5270 and with this checkin it although works now. Thanks for the fix

**Comment by samhouts** [comment]
Does that mean this issue is resolved and can be closed? Thanks!

**Comment by inforithmics** [comment]
The checkin https://github.com/xamarin/Xamarin.Forms/pull/5309 went to master and not to the 3.5 branch. So this issue is still present in 3.5 and 3.6 branch. So In my opinion when the patch is merged into 3.5 and 3.6 this issue can be closed.

**Comment by samhouts** [comment]
@StephaneDelcroix Should we backport #5309? Thanks!
