### ISSUE TITLE
3.5.0 regression: two-way bindings with nullable types fail to propagate null values back

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#5290]
### Description

Two-way bindings with nullable types no longer work correctly in Xamarin Forms 3.5.0. In particular, null values are not propagated back to the source binding object.

### Steps to Reproduce

1. Run the attached project
2. Click the main page button
3. Note that the text label below never prints "null" with 3.5.0. It works fine with 3.4.0

### Expected Behavior

Two-way bindings works as expected.

### Actual Behavior

Null values are not propagated back to the source binding object.

### Basic Information

- Version with issue: 3.5.0.129452
- Last known good version: 3.4.0.1029999
- IDE: VS 2017
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 28.0.0.1
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[XamarinFormsSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2873649/XamarinFormsSample.zip)

**Comment by StephaneDelcroix** [comment]
might be related to #5255

**Comment by StephaneDelcroix** [comment]
I'm trying to reproduce your issue on top of today's 3.5.0 branch (55110c832) with the following unit-test

```xaml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage
		xmlns="http://xamarin.com/schemas/2014/forms"
		xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
		x:Class="Xamarin.Forms.Xaml.UnitTests.Gh5290"
		NullableTime="{Binding Time, Mode=TwoWay}">	
</ContentPage>
```

```csharp
using System;
using NUnit.Framework;
using Xamarin.Forms.Core.UnitTests;

namespace Xamarin.Forms.Xaml.UnitTests
{
	public class Gh5290VM
	{
		public TimeSpan? Time { get; set; }
	}

	public partial class Gh5290 : ContentPage
	{
		public static readonly BindableProperty NullableTimeProperty =
			BindableProperty.Create("NullableTime", typeof(TimeSpan?), typeof(Gh5290), default(TimeSpan?));

		public TimeSpan? NullableTime {
			get => (TimeSpan?)GetValue(NullableTimeProperty);
			set => SetValue(NullableTimeProperty, value);
		}

		public Gh5290() => InitializeComponent();
		public Gh5290(bool useCompiledXaml)
		{
			//this stub will be replaced at compile time
		}

		[TestFixture]
		class Tests
		{
			[SetUp] public void Setup() => Device.PlatformServices = new MockPlatformServices();
			[TearDown] public void TearDown() => Device.PlatformServices = null;

			[Test]
			public void TwoWayBindingToNullable([Values(false, true)]bool useCompiledXaml)
			{
				var vm = new Gh5290VM { Time = TimeSpan.FromMinutes(42) };
				var layout = new Gh5290(useCompiledXaml) { BindingContext = vm };

				Assert.That(layout.NullableTime, Is.EqualTo(TimeSpan.FromMinutes(42)));

				layout.SetValueFromRenderer(NullableTimeProperty, null);
				Assert.That(layout.NullableTime, Is.Null);
			}
		}
	}
}
```

and that test is passing. am I missing something ?

**Comment by StephaneDelcroix** [comment]
this is indeed fixed by #5255, and will be part of the -sr of 3.5.0

**Comment by mfeingol** [comment]
@StephaneDelcroix: did this make it into `3.5.0.169047`?

I just gave it a spin and I'm still seeing a problem:

```
[0:] Binding:  can not be converted to type 'System.Nullable`1[System.TimeSpan]'
Unhandled Exception:

Java.Lang.IndexOutOfBoundsException: setSpan (851 ... 851) ends beyond length 500
```

**Comment by StephaneDelcroix** [comment]
@mfeingol not part of -sr1. will be part of the next -sr

**Comment by mfeingol** [comment]
This appears to be fixed in the first 3.6.0 release.
