### ISSUE TITLE
CollectionView SelectedItem TwoWay Binding  not working

### ISSUE THREAD

**Issue by psp589** [xamarin/Xamarin.Forms#5601]
### Description
When I Select an item from the collection the selected item doesn't change
### Steps to Reproduce
Having this XAML
```
<ContentPage>
        <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition />
                <ColumnDefinition Width="auto" />
            </Grid.ColumnDefinitions>
            <CollectionView Grid.Column="0" 
                            SelectionMode="Single"
                            SelectedItem="{Binding SelectedItem, Mode=TwoWay}"
                            ItemsSource="{Binding ObservableCollectionTest}">
                <CollectionView.ItemsLayout>
                    <GridItemsLayout Orientation="Vertical" />
                </CollectionView.ItemsLayout>
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <Grid>
                            <Label Text="{Binding}"></Label>
                        </Grid>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
                
            </CollectionView>
            <Label Grid.Column="1"
                   Text="{Binding SelectedItem}" />
        </Grid>
    </ContentPage>
```
With this data in the Model
```
public static string SelectedItemPropertyName() { return nameof(SelectedItem); }
        private string _SelectedItem;
        public string SelectedItem
        {
            get
            {
                return _SelectedItem;
            }
            set
            {
                _SelectedItem = value;
                RaisePropertyChanged();
            }
        }
        public static string ObservableCollectionTestPropertyName() { return nameof(ObservableCollectionTest); }
        private ObservableCollection<string> _ObservableCollectionTest = new ObservableCollection<string>(new List<string>() { "Test1", "test2", "test3" } );
        public ObservableCollection<string> ObservableCollectionTest
        {
            get
            {
                return _ObservableCollectionTest;
            }
            set
            {
                _ObservableCollectionTest = value;
                RaisePropertyChanged();
            }
        }
SelectedItem = ObservableCollectionTest[1];

```

### Expected Behavior
SelectedItem must change its value on each item tap
### Actual Behavior
It doesn't change
### Basic Information

- Version with issue: 4.0.0.232914-pre6 ( not working neither in 4.0 pre-7 neither 4.0 pre-8)
- IDE: Visual Studio Community 2017 version 15.9.9
- Platform Target Frameworks:  
  - UWP:  Windows 10 version 1803 Build 17134

**Comment by Moltroon** [comment]
In Xamarin Forms 4.0 pre-7 it working good for me

**Comment by psp589** [comment]
@Moltroon are you targeting UWP ?  for me it is not working in forms 4.0 pre-7 neither 4.0 pre-8

**Comment by Moltroon** [comment]
Oh sorry, I do not have see the UWP platform precision. I have just test in Android and iOS.

**Comment by saguado69** [comment]
same for me in forms 4.0.0.425677

**Comment by nguyenthanhliemfc** [comment]
Same with me in Forns 4.1

**Comment by nguyenthanhliemfc** [comment]
@psp589  @saguado69  I found solution. Try set SelectionMode="Single"

**Comment by psp589** [comment]
@nguyenthanhliemfc I don't know if the issue is fixed in other version, but for the reported version, if you read the sample code for reproducing the issue, I'm setting SelectionMode="Single"

**Comment by saguado69** [comment]
In my case, the issue is solved. Thanks!

**Comment by ivanicin** [comment]
@saguado69 your case is probably that you are not using UWP, as this is not fixed. I do understand that you wanted to help, but the end effect is that all users subscribed here are getting unnecessary emails, so please take some time to read the bugs properly and act responsibly. It is very unfair to take minutes of many people to save few minutes of yours.

**Comment by saguado69** [comment]
@ivanicin you are right, sorry but I misstyping my answer, as I wanted to wrote that the issue was NOT solved. And thanks for the advise.

**Comment by HeroSpha** [comment]
Its not working even for Android in xamarin forms, didnt test it in iOS

**Comment by hartez** [comment]
This is fixed in 4.2 by (https://github.com/xamarin/Xamarin.Forms/pull/6629).

**Comment by PeterHlavenka** [comment]
Property in your viewModel to which is CollectionView.SelectedItem bounded should be type of object. In the same way CollectionView.SelectedItems should be bouded to ICollection<object>.  Two way mode works for me.

**Comment by ivanicin** [comment]
> 
> 
> Property in your viewModel to which is CollectionView.SelectedItem bounded should be type of object. In the same way CollectionView.SelectedItems should be bouded to ICollection. Two way mode works for me.

@PeterHlavenka While I understand you wanted to help, please note that this issue has been fixed two years ago as displayed above and as such it obviously works, no need to point on that, you are just raising the unnecessary noise.
