### ISSUE TITLE
Xamarin Forms MasterDetailPage button padding issue in UWP

### ISSUE THREAD

**Issue by ZhuMingHao** [xamarin/Xamarin.Forms#5661]
### Description

I'm currently learning Xamarin Forms and I have a small graphic issue. I have to fit the height of all the buttons to 100% (based on Navigation bar). Actually Xamarin cut some pixels in the bottom for the hamburger icon and the "three dots" icon is not set to 100% height.

### Steps to Reproduce

1. Create xamarin form project with  default template Master-Detail
2. Modify UWP target version to 17763
3. Run the app

### Expected Behavior
![image](https://user-images.githubusercontent.com/16216807/54798833-7ea39a80-4c95-11e9-8b27-16a3245bd07f.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/16216807/54798886-ac88df00-4c95-11e9-9b09-7ca1ae8c0f4a.png)

### Basic Information

- Version with issue: UWP target Version 17763
- Last known good version:  UWP target Version 17134
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
 - UWP:  The version of the UWP SDK 17763

### Reproduction Link

[Xamarin Forms MasterDetailPage button padding issue in UWP](https://stackoverflow.com/questions/55265495/xamarin-forms-masterdetailpage-button-padding-issue-in-uwp)

**Comment by kingces95** [comment]
Reproduces as described

**Comment by drossoft** [comment]
Hi, Is there any progress on this issue?

**Comment by RedChops** [comment]
I'm running in to this too. The padding was off as described above directly from the template, with no code modifications on my part.

Is there any sort of workaround?

**Comment by TheGuardianWolf** [comment]
UWP target 18362 also has this issue

**Comment by MitchBomcanhao** [comment]
same here. 
Target Version 18362 (1903)
Min Version 17134 (1803)

When you press the ellipsis button on the side, it moves the content of the entire header to a partially invisible area:

![image](https://user-images.githubusercontent.com/31066938/60596667-63225280-9da1-11e9-8625-8f2c19cfb3ea.png)

**Comment by squeake** [comment]
> I'm running in to this too. The padding was off as described above directly from the template, with no code modifications on my part.
> 
> Is there any sort of workaround?

You could set your UWP target version as 17134 to avoid this behavior.

**Comment by omghb** [comment]
Please, fix this issue. I need to use newer UWP target version.

**Comment by jcmanke** [comment]
Another reproduction. Note that the size of the ToolbarItem icon also changes with the target upgrade from 17134 to 17763.

![uwp_toolbar](https://user-images.githubusercontent.com/6132629/63272382-93468780-c261-11e9-9d4c-b1ab902382e3.png)

**Comment by Capt-Nemo-** [comment]
The listed workaround (setting target SDK to earlier version) no longer works with latest xamarin.forms v4.3. I tried all the SDK's back to fall creators update build 16299, all have menu button cut off now and it looks very unprofessional. Truly a showstopper....

**Comment by velocitysystems** [comment]
@PureWeen Unfortunately this is still an issue for us too.
Do you have any updates on when this will be resolved?

**Comment by velocitysystems** [comment]
We have tested this further, and I don't believe this is related to target SDK version but rather is a regression XF 4.3+. Note: I am unable to reproduce this issue on XF 4.2. Will create a new issue which more accurately describes the problem.

**Comment by velocitysystems** [comment]
@PureWeen @samhouts We note that when using XF 4.2, setting the target version to 1803 or lower resolves this issue. However in XF 4.3, this no longer works.

We noticed that in #7719 you mention the SDK version is being rolled back to 16299.
Will this be available in XF 4.3-sr2?

**Comment by Aculeo** [comment]
I think the priority of this should be increased, as there is currently no workaround available. It looks really bad and I'd rather not release a UWP app with this.

**Comment by velocitysystems** [comment]
@davidortinau David, this is a significant regression for users with apps running on UWP.
Could you please advise if there a timeframe on when we can expect a fix?

We love XF 4.3 and are working on adopting many of the new features available, but this issue is currently blocking us from releasing an update to our production users.

Thanks so much and we appreciate the hard work of the XF team.
--Matthew

**Comment by jfversluis** [comment]
I think you should be able to fix it by adding this to your `App.xaml` in your UWP project

```
<Application.Resources>
    <x:Double x:Key="AppBarThemeCompactHeight">48</x:Double>
</Application.Resources>
```

At least the padding in the regular view disappears. Still something funny seems to be going on when you press the ellipsis button though.

I'm still trying to figure out what is going on with the different combinations of UWP SDKs, XF NuGets, etc.

**Comment by MattRames** [comment]
> 
> 
> I think you should be able to fix it by adding this to your `App.xaml` in your UWP project
> 
> ```
> <Application.Resources>
>     <x:Double x:Key="AppBarThemeCompactHeight">48</x:Double>
> </Application.Resources>
> ```
> 
> At least the padding in the regular view disappears. Still something funny seems to be going on when you press the ellipsis button though.
> 
> I'm still trying to figure out what is going on with the different combinations of UWP SDKs, XF NuGets, etc.

This sort of fixes the problem. Sadly no matter what UWP target I use, toolbar items are still not sized properly on XF 4.3.

**Comment by lordalcol** [comment]
Any news on the status of this issue?

**Comment by morphinapg** [comment]
This seems to be working correctly for me now with XF 4.3.0.991221

**Comment by jfversluis** [comment]
@lordalcol and all this should be fixed with merging #8610 which should be available now in the latest 4.3 and 4.4 package. I'm closing this one, if there is still something wrong, please open a new one referencing this one.

Thanks!

**Comment by omghb** [comment]
I still see this issue with the latest XF Version.
XF: 4.3.0.991221
UWP SDK: 10.0.18362.0

The toolbar button height is wrong:
![image](https://user-images.githubusercontent.com/47421673/70424854-5a305e00-1a70-11ea-97ea-77c05eea0169.png)

**Comment by scriptBoris** [comment]
Hello, is there any progress towards solving this problem?

**Comment by YZahringer** [comment]
@samhouts the issue persists in XF 4.6.0.847 and #8625 is closed. Should this issue be reopened?
