### ISSUE TITLE
[Bug] Data binding an array item of type enum is incorrect

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Xamarin.Forms#5919]
### Description

When binding to a particular index in an array, the result is different that if it was a property.

### Steps to Reproduce

Given an enum:

```csharp
public enum Player {
    Nobody,
    X,
    O
}
```

And 2 properties:

```csharp
public Player[] Board { get; }
public Player CurrentPlayer { get; set; }
```

If I add a databinding:

```xaml
Text="{Binding CurrentPlayer}"
```

The value will either be "X", "O" or "Nobody". If I bind to an array item:

```xaml
Text="{Binding Board[1]}"
```

The value will be "0", "1", or "2".

### Expected Behavior

The array data binding uses `.ToString()`.

### Actual Behavior

The array binding uses some integer representation.

### Basic Information

- Version with issue: 3.6.0.293080
- Last known good version: (not sure)
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by ionixjunior** [comment]
I'd like to work on this.

**Comment by StephaneDelcroix** [comment]
I might have fixed that in the past weeks, need to reevaluate (I fixed something related to binding and string conversions, for sure, but I don't know if it fixes this case)

**Comment by ionixjunior** [comment]
Hi @StephaneDelcroix, I already created a test for this and the problem still happens. My test: https://github.com/ionixjunior/Xamarin.Forms/commit/40f7602d53727f0f87632ed37be6606ec0153225
