### ISSUE TITLE
Xamarin Forms CollectionView SelectionChanged event not firing on UWP

### ISSUE THREAD

**Issue by micrtoeq** [xamarin/Xamarin.Forms#6036]
### Description
When using the SelectionChanged Event in XAML, it does not fire on selection of an item uin UWP. We tried in Android and there it works.

### Steps to Reproduce

            <CollectionView 
                Margin="16"
                SelectionMode="Single"
                ItemsSource="{Binding Items}"
                VerticalOptions="FillAndExpand"
                HorizontalOptions="Center"
                WidthRequest="620"
                SelectionChanged="OnSelectionChanged"
                >
                <CollectionView.ItemTemplate>
                    <DataTemplate >
                        <Grid>
                            <Label Text="Test" />
                        </Grid>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>

        protected virtual void OnSelectionChanged(object sender, SelectionChangedEventArgs args)
        {
        }

### Expected Behavior

Event should fire in UWP when clicking an item in the list.
### Actual Behavior
Nothing happens.
### Basic Information

- Version with issue:

Xamarin Forms 4.0 pre 9

- IDE:
VS 2017

- Platform Target Frameworks: 
  - UWP:  <17763> 
- Affected Devices:
Win 10

**Comment by eclipsed4utoo** [comment]
More than 2 months after this was brought up, it hasn't been fixed yet?

Selection changing does not work on UWP for the CollectionView. Neither the SelectionChanged event nor the SelectionChangedCommand work. I feel that this is a pretty large issue considering that tapping on collection view items is a pretty common thing to do.

**Comment by theescapers** [comment]
I ended up writing by own CollectionView, I'd share the code, but it's a commercial project. If your needs are basic, it's only a few hours work, quicker than waiting for a fix!

**Comment by ivanicin** [comment]
@eclipsed4utoo @theescapers CoolectionView is currently available only as experimental, and there is no need to comment the quality of the feature and spam people here. I am subscribed to many bugs like this one that I need to be fixed and I really don't want to read opinion of every single of thousands of Xamarin developers regarding the problem. If you can help, great, if you can't, don't spam. Switching the platform is always an option. If you want to complain go to forums.

**Comment by Spookenator** [comment]
Commands also do not fire and the SelectedItem binding is also null.
`  <CollectionView ItemsSource="{Binding People}" ItemSizingStrategy="MeasureFirstItem" HorizontalOptions="FillAndExpand" 
                                    SelectionChanged="CollectionView_SelectionChanged" SelectionMode="Single"
                                    SelectionChangedCommand="{Binding PersonSelectedCommand}" SelectedItem="{Binding Person}" >`

**Comment by jsiemens** [comment]
This is in 4.2.

https://github.com/xamarin/Xamarin.Forms/pull/6629

**Comment by EvoPulseGaming** [comment]
Selection changed event works in pre 4.3 using UWP, however behaves wrong see #8203

**Comment by hartez** [comment]
This was fixed by PR #6629.

**Comment by Genfood** [comment]
It's still not working for me under iOS on Xamarin verison 4.4.0.991537.
