### ISSUE TITLE
Xamarin Forms: MemoryLeak Button ImageSource

### ISSUE THREAD

**Issue by KonstantinKellermann** [xamarin/Xamarin.Forms#6260]
**Description**

Since the latest update of Xamarin.Forms (Version 4.0.0.425677) we have a big memory leak using a button with an image insight.
It's a little bit confusing because the issue pops up if we tap an entry field. After that our application is useless.
The issue occures in the combination of a button with ImageSource Property set.

We created a simple testproject with just a label, an entry and a button using ImageSource to reproduce it. The same issue pops up.

After analyzing with Xamarin Profiler it looks like the issue is somewher here at the GetFields()-Method:
[https://github.com/xamarin/Xamarin.Forms/blob/52a2581dfe4bd52f8bcabfb714c63e784735fee3/Xamarin.Forms.Platform.Android/ResourceManager.cs#L379](url)

In the following zip is the data of the Profiler showing that the GetField()-Method is running constantly and hitting 50% of allocations.
[https://github.com/KonstantinKellermann/MemoryLeak_ButtonWithImage/blob/master/MemoryLeak_Button_Image_Android_Entry_ProfilerLog.zip](url)

We didn't test it on IOS.

**Steps to reproduce**

- start the app
- tap in the entry field
- start typing
- you should see Mono Garbage Collector constantly running

**Basic Information**

- Nuget Packages:

  - Xamarin.Essentials: 1.1.0
  - Xamarin.Forms: 4.0.0.425677
  - Xamarin.Android.Support.Core.Utils: 28.0.0.1
  - Xamarin.Android.Support.CustomTabs: 28.0.0.1
  - Xamarin.Android.Support.Design: 28.0.0.1
  - Xamarin.Android.Support.v4: 28.0.0.1
  - Xamarin.Android.Support.v7.AppCompat: 28.0.0.1
  - Xamarin.Android.Support.v7.CardView: 28.0.0.1
  - Xamarin.Android.Support.v7.MediaRouter: 28.0.0.1
  - NETStandard.Library: 2.0.3

- Affected Devices:

  - Samsung Galaxy S7: Android 8.0
  - Samsung Galaxy S9: Android 9.0
  - Nexus 5X: Android 8.1.0

**Code Example**

https://github.com/KonstantinKellermann/MemoryLeak_ButtonWithImage

**Comment by kingces95** [comment]
@KonstantinKellermann Hm, the links are broken. https://github.com/KonstantinKellermann/MemoryLeak_ButtonWithImage links to https://github.com/xamarin/Xamarin.Forms/issues/url which I don't think are the droid we're looking for.

**Comment by PureWeen** [comment]
Verified this one

it looks like anytime the layout changes the image is re-retrieved even though it hasn't changed which is causing an excess of allocations

**Comment by toomasz** [comment]
@PureWeen I have a page with Button with ImageSource and listView with PullToRefresh enabled. Page seems to hang when user pulls to refresh. Do you think it has same root cause? I'm not sure if I should create another issue for it on github.

**Comment by KonstantinKellermann** [comment]
@toomasz I think it should be related.

**Comment by PureWeen** [comment]
@toomasz can you test by reverting back to legacy renderers?

- Enabling the Forms.SetFlags("UseLegacyRenderers") flag in your MainActivity.

When I fixed the issue I found that this behavior only happens when using the fast renderers.

**Comment by toomasz** [comment]
@PureWeen Using legacy renderers doesn't help. Still getting hang. GC messages keep showing in log.

**Comment by PureWeen** [comment]
@toomasz can you test with this nuget

[nuget.zip](https://github.com/xamarin/Xamarin.Forms/files/3213536/nuget.zip)

**Comment by toomasz** [comment]
> nuget.zip

Tried, problem still exists :(

**Comment by PureWeen** [comment]
@toomasz can you send me a reproduction?

**Comment by toomasz** [comment]
@PureWeen Sure, hopefully i will manage to create it

**Comment by toomasz** [comment]
@PureWeen Managed to reproduce it, turned out it hangs when using master detail page and setting detail to page with button that uses image source.

To test, open master page and click on button that is there, app will hang then.
[ImageSourceHang.zip](https://github.com/xamarin/Xamarin.Forms/files/3213949/ImageSourceHang.zip)
Let me know if you got it.

**Comment by PureWeen** [comment]
Aw ok
Needed to fix material button as well :-/ Thank your for the repro!!!

**Comment by PureWeen** [comment]
@toomasz can you test this one please?
[debug(1).zip](https://github.com/xamarin/Xamarin.Forms/files/3215449/debug.1.zip)

**Comment by toomasz** [comment]
@PureWeen Works good now
