### ISSUE TITLE
[Bug] Shell FlowDirection follows Device FlowDirection in all cases.

### ISSUE THREAD

**Issue by aljaiban** [xamarin/Xamarin.Forms#6342]
### Description
When setting the FlowDirection on Shell to RTL, it only take effects if the Device FlowDirection is the same i.e. RTL. When the Device FlowDirection is LTR and you set Shell FlowDirection to RTL, it does not work

### Steps to Reproduce

I tried the following scenario on Android emulator:

Shell: Explicit RightToLeft 
Page: MatchParent

When device region is Arabic/SA (RTL) : The Shell displays correctly and the page too.

When device region is English/US: The Shell displays Incorrectly i.e. LTR and the page displays correctly i.e. RTL.  See snapshot.

### Expected Behavior
Shell should use the direction specified in its FlowDirection attribute regardless of the Device FlowDirection.

### Actual Behavior
Right now it follows the Device FlowDirection.

### Basic Information

- Version with issue: Xamarin Forms 4.0
- Last known good version: None
- IDE: Visual Studio 2019 on Windows
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  
### Screenshots
![image](https://user-images.githubusercontent.com/7361168/58554672-46ce4b80-8220-11e9-995d-48c8cfb316ae.png)

**Comment by samhouts** [comment]
Duplicate of #6227

**Comment by aljaiban** [comment]
@samhouts  Not duplicate. In case of 6227 the Device FlowDirection is the same as the Shell Flow Direction and both are RTL.

In this case, the Shell menu appear LTR  even Shell is specified as RTL (Device is LTR.)

**Comment by samhouts** [comment]
@aljaiban Okay, I'll reopen this. With any luck, we'll be able to fix them both at the same time! Thanks!

**Comment by samhouts** [comment]
@aljaiban  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by aljaiban** [comment]
Attached a sample project and snapshot. Note that you need to run the project on an LTR (English/US for example) device/emulator/simulator for the issue to appear.
![Snapshot](https://user-images.githubusercontent.com/7361168/58752128-333a1380-84b2-11e9-8b82-80702fe6882d.png)

https://1drv.ms/u/s!Anxli5dwfVWNpNcQNeJpj3ZhNKPryw

**Comment by jfversluis** [comment]
Making sure we don't lose access to the reproduction code adding it here: 
[RTLIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3281165/RTLIssue.zip) can confirm this is happening.

**Comment by AmerBakeer** [comment]
Hello, 
Any update regarding this show-stopper? 😔😞
Thanks in advance

**Comment by aljaiban** [comment]
I would appreciate if you have any update here.

**Comment by PureWeen** [comment]
This should be resolved by this PR
https://github.com/xamarin/Xamarin.Forms/pull/9237

**Comment by aljaiban** [comment]
Thank you team. Looking forward to have it with the coming update.

**Comment by UwpDev** [comment]
I can still see this issue in Android even after updating to Xamarin.Forms 4.6.0.800. Is it fixed?

**Comment by UwpDev** [comment]
@PureWeen @samhouts Can you confirm this? I still see this issue in Android at least even with version 4.6.0.800

**Comment by UwpDev** [comment]
> 
> 
> Thank you team. Looking forward to have it with the coming update.

@aljaiban Did this fix solve your issue?

**Comment by MayankPatil-25** [comment]
@samhouts: 
I am facing same issue in Xamarin.Forms Android with Shell Flyout, I have set the Shell property _FlowDirection="RightToLeft"_   and it is working fine in iOS but not in Android

**Issue:**
In Android, The Flyout opening from LTR even after setting this property _FlowDirection="RightToLeft"_ but working fine in iOS.

**Requirement:**
I want the Flyout to open from RTL, in same fashion how it is working in iOS after setting that property.

**Details:**
Xamarin.Form version: 5.0.0.2012
Xamarin.Android version: 11.2.2.1 

Please help.. thanks
