### ISSUE TITLE
[Bug, CollectionView] SelectionChangedCommand invoked before SelectedItem is set

### ISSUE THREAD

**Issue by ArgusMagnus** [xamarin/Xamarin.Forms#6609]
### Description
The `SelectedItem` property on the `CollectionView` is set after the `SelectionChangedCommand` is executed and thus when the command is executed there is no way of knowing, which item was selected, instead `SelectedItem` contains the value of the previous selection.

### Expected Behavior
`SelectedItem` is set before executing `SelectionChangedCommand`.

### Actual Behavior
`SelectedItem` is set after executing `SelectionChangedCommand`.

### Basic Information

- Version with issue: 4.0.0.497661
- Last known good version:
- IDE: VS 2019 (16.1.3)
- Platform Target Frameworks: 
  - iOS:  11.3
  - Android: 9

**Comment by samhouts** [comment]
@ArgusMagnus  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by rpdomingo** [comment]
Upon Navigating to the page that has a CollectionView, it auto fire on this method 

ViewModel
![image](https://user-images.githubusercontent.com/26340099/59993846-50629c00-9684-11e9-9272-26c8152e5693.png)

View
![image](https://user-images.githubusercontent.com/26340099/59993875-696b4d00-9684-11e9-84bd-abe3d42dc02c.png)

Is this the actual Behavior?

**Comment by hartez** [comment]
@rpdomingo Yes, that is the expected behavior. `SelectedItem` is bound to SelectedWholesalerProduct, so setting the binding context is updating `SelectedItem` to the bound value, which will fire the `SelectionChangedCommand`.

**Comment by hartez** [comment]
@ArgusMagnus Can you provide some example code? I'm attempting to reproduce this problem, but I'm not having any success.

**Comment by ArgusMagnus** [comment]
@hartez I was not able to reproduce this with a new project either. I have to check this again with the project I first encountered this issue, but I'm fully absorbed in other project at the moment, so I'll have to get back to this later.

**Comment by ArgusMagnus** [comment]
@hartez I investigated the issue. I was wrong, `SelectedItem` is set as expected. What I actually did was this:

    <CollectionView ItemsSource="{Binding Items}"
                    SelectionMode="Single"
                    SelectionChangedCommand="{Binding SelectionChangedCommand}"
                    SelectionChangedCommandParameter="{Binding SelectedItem, Source={x:Reference MyCollectionView}}"
                    x:Name="MyCollectionView">

In order to avoid an unnecessary additional property in my ViewModel, I tried to pass the `SelectedItem` directly as parameter to the `SelectionChangedCommand`. When I do this, the value I receive as Command parameter is the value of the previous, not the current, selection.

Repro: https://1drv.ms/u/s!AnmEVu7lvXuCb8uLYfz6EayZ6vU?e=TQvx4w

**Comment by rpdomingo** [comment]
@ArgusMagnus  have you tried to select the same item you've selected? example: if i select **item 1** and it will fire the **display alert** and when I click again the item 1 it will not fire as expected. Maybe because of selection = single. This is actually my problem for now. client requirements lol :D

**Comment by ArgusMagnus** [comment]
@rpdomingo I have not tried that, but I would expect the behaviour to be like that, because when reselecting the same item, the selection does not really change. In your place, I would probably go for a custom `ItemTemplate` which contains a `Button` or a `TapGestureRecognizer`.

**Comment by rpdomingo** [comment]
@ArgusMagnus  Yes!! I've implemented that for now. Thanks 👍

**Comment by mikeirvingweb** [comment]
This is still an issue in 2022.. _SelectionChangedCommand_ calls before the items list is updated, and then _SelectionChanged_ runs. I am using _SelectionMode="Multiple"_. I have spent many hours on Friday and Today trying to work around this, but the bug is definitely still there.

**Comment by michaelrinderle** [comment]
This behavior in .Net Maui collection views brought me here.
