### ISSUE TITLE
[Bug] Pull to refresh ListView: empty cells when refreshing list after scrolling on Android

### ISSUE THREAD

**Issue by fhyvrier** [xamarin/Xamarin.Forms#6810]
### Description

When a list view implements the "pull to refresh" feature, refreshing the list after scrolling causes some cells to become empty. The empty cells become visible again after scrolling down so that they disappear from the view port, and then scrolling up.

### Steps to Reproduce

1. Clone the official sample project [Xamarin.Forms ListView Sample: Interactivity](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/ListView/Interactivity)
2. Edit the file `interactiveListViewXaml.xaml.cs` and change the initialization of the static list `items` so that it contains enough elements to allow scrolling.
```cs
// Replace this:
items = new ObservableCollection<string> () { "Speaker", "Pen", "Lamp", "Monitor", "Bag", "Book", "Cap", "Tote", "Floss", "Phone"};

// By this:
items = new ObservableCollection<string>();
for (int i = 0; i < 100; i++)
{
    items.Add($"Item #{i}");
}
```
3. Run the app on a device. The main page appears and displays the list.
4. Scroll down, then scroll up.
5. Pull to refresh the list.
6. Observe that some cells become empty after the list view has been refreshed.

### Expected Behavior

All cells should be visible after the list view has been refreshed.

### Actual Behavior

Some cells are empty after refreshing the list.

### Basic Information

- Version with issue: Xamarin.Forms version 4.1.0.555618
- Last known good version: XF version 3.6.0.539721
- IDE: Visual Studio 2019 16.1.2
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: 9.0 
  - UWP:  N/A 
- Affected Devices: Motorola Moto G3 XT1541 with Android 6.0.1

#### Listview in its initial state
![01-initial-list](https://user-images.githubusercontent.com/37797661/60767112-0c738c00-a0b3-11e9-9107-14576b1b90fd.png)

#### Scroll down
![02-scroll-down](https://user-images.githubusercontent.com/37797661/60767113-0c738c00-a0b3-11e9-8194-fa0c4d21b261.png)

#### Scroll up, then refresh
![03-scroll-up](https://user-images.githubusercontent.com/37797661/60767114-0d0c2280-a0b3-11e9-93d8-603b2b9f2158.png)

#### See the empty cells
![04-list-after-refresh](https://user-images.githubusercontent.com/37797661/60767115-0d0c2280-a0b3-11e9-94b4-78ca4b53876b.png)

**Comment by jfversluis** [comment]
Did you try this on iOS and it didn't occur or did not try iOS at all?

**Comment by fhyvrier** [comment]
Hi Gerald, no I couldn't test this behavior at all on iOS nor UWP.

**Comment by SolitudeSA** [comment]
Phew, I'm glad I'm not the only one. I've been struggling with this the whole morning. We only build for Android so can't test on iOS.

**Comment by scervellera** [comment]
I can confirm that there is no problem compiling for iOs: the lists work correctly! The problem is only for Android. 
I had to go back to 3.6

**Comment by ChrisJAult** [comment]
Same problem here except anything in the listview header dissapears randomly.  Only Android.

**Comment by wimb** [comment]
I'm having a similar problem. Not with pull to refresh, but just by clearing my ObservableCollection (with binding in xaml) and adding new items when returning to the page(in OnAppearing). This results in empty rows like the screenshots posted in this issue.
When scrolling (move row out of screen, and back on screen) makes the item render correctly.
Downgrading to 3.6.0.539721 works.

**Comment by jsuarezruiz** [comment]
I have made some tests with the sample. It has taken several attempts to reproduce the problem.
Can be related to: https://github.com/xamarin/Xamarin.Forms/issues/6721
With Xamarin.Forms 3.6 it does not happen.

**Comment by samhouts** [comment]
This should be resolved in the latest 4.0.0 and 4.1.0 service releases. Thanks!

**Comment by KthProg** [comment]
Still seeing this with list group headers using Xamarin.Forms 4.1.0.5xxx on Android 7. When I change the observable collection some of the headers and cells are not displayed until I scroll the list view a few times.

![image](https://user-images.githubusercontent.com/3527476/64261082-f2f79080-cef9-11e9-8501-9bfb11d0b974.png)

![image](https://user-images.githubusercontent.com/3527476/64261123-04409d00-cefa-11e9-8b5f-8bfa59b713a2.png)

![image](https://user-images.githubusercontent.com/3527476/64261146-0c98d800-cefa-11e9-912a-11492d59e1f8.png)

**Comment by mdmota** [comment]
@samhouts ????

**Comment by KthProg** [comment]
i fixed the above issue by enabling recycling, but that cause a slew of other issues I had to fix. So this is an issue when recycling is off and you have grouping enabled on a list view.

**Comment by HelenMamalaki** [comment]
This is still occurring in Xamarins.Forms 4.2 - I re-assign the ItemSource in order to refresh the list and some items disappear. :( I have set CachingStrategy="RecycleElement" but I think my issue may be related to the use of a DataTemplateSelector as only rows with a specific DataTemplate disappear and reappear.

**Comment by jfversluis** [comment]
Hey @HelenMamalaki and other people that seem to still experience this. If it's not too much trouble could I ask you to try with the very latest 4.2 package or maybe 4.3-pre package and see if this still occurs?

If it does, please create a new issue, you can refer to this one, with a small reproduction project and other info that is relevant.

Thanks!

**Comment by mdmota** [comment]
this bug still not fix in XF4.3.0.778476-pre3

**Comment by mdmota** [comment]
After upgrading XF to 4.3.0 and replacing listivew with colletionView, the problem continues
https://github.com/xamarin/Xamarin.Forms/issues/8199#issuecomment-545937143

**Comment by mdmota** [comment]
Closed in which version?
