### ISSUE TITLE
[Bug] CarouselView not handling GestureRecognizers and ScrollToRequested on swipe

### ISSUE THREAD

**Issue by pierre01** [xamarin/Xamarin.Forms#7036]
CarouselView is not handling GestureRecognizers SwipeGestureRecognizer (IOS and Android)
also PanGestureRecognizer not working in Android (But works on IOS)

### Steps to Reproduce

1. Create a shell application 
2. Create a ContentPage with a CarouselView inside
3. Set the CarouselView.ItemsSource to multiple items
4. Create an event handler (optional) for ScrollToRequested in CarouselView
5. Create CarouselView.GestureRecognizers SwipeGestureRecognizer and PanGestureRecognizer
6. Implement event handler for Swiped in SwipeGestureRecognizer
7. Implement event handler for PanUpdated in PanGestureRecognizer

### Expected Behavior

While swiping right to left 
- ScrollToRequested handler should be called
- Swiped handler should be called
- PanUpdated handler should be called

### Actual Behavior
On Android:
 None of the handlers are called (ScrollToRequested  is only called if you programmatically call ScrollTo(x) in the code behind.

On IOS:
Only PanUpdated is called

### Basic Information

- Version with issue: 4.1.0.618606
- Last known good version: ?
- IDE: Visual studio 2019 Windows 10
- Platform Target Frameworks: 
  - iOS:  8.0
  - Android: Android 9 API 28 

   
- Nuget Packages:
- Affected Devices:

### Screenshots

See animated GIF

![CarouselSwipeBug](https://user-images.githubusercontent.com/2603287/62256736-53edef00-b3b7-11e9-95ee-fda7befcafaa.gif)

**Comment by samhouts** [comment]
@pierre01  Can you please attach a small project that demonstrates this issue? 

Also, does this happen if you do *not* use Shell?

Thanks!

**Comment by pierre01** [comment]
https://github.com/pierre01/CarouselSample
I only added one form (CarouselPage.xaml) to the standard shell project and the app opens it first.
The page contains a CarouselView that illustrate the issues

**Comment by pierre01** [comment]
I have not tested yet whitout the shell

**Comment by PureWeen** [comment]
@pierre01 can you test with the latest 4.2 pre? 

https://www.nuget.org/packages/Xamarin.Forms/4.2.0.673161-pre3

We fixed an issues with Gestures there and I'm curious if it fixes your issue

**Comment by pierre01** [comment]
I tested with 4.2.0.673161-pre3 But the issue is still there see my updated sample at
https://github.com/pierre01/CarouselSample

**Comment by pierre01** [comment]
Actually it is even worse as the PanUpdated event that was working on IOS, is not working anymore now.

**Comment by dpa456** [comment]
I have 3 tested way in CarouselView (Ver-4.2.0.673161) with Android (sorry i don't have mac)

1) ScrollToRequested : Not worked
2) Add PanGestureRecognizer - PanUpdated : Not worked
3) Scrolled : Worked 👍 
![Carsousel 4 2 0 673161-pre3](https://user-images.githubusercontent.com/10584073/62927938-7c7fdb00-bdf2-11e9-9889-0ea6a4131445.png)

Have there function
`Debug.WriteLine(" FirstVisibleItemIndex : " + e.FirstVisibleItemIndex
                + " CenterItemIndex : " + e.CenterItemIndex
                + " LastVisibleItemIndex : " + e.LastVisibleItemIndex
                + " HorizontalOffset : " + e.HorizontalOffset
                + " HorizontalDelta : " + e.HorizontalDelta
                + " VerticalDelta : " + e.VerticalDelta
                + " VerticalOffset : " + e.VerticalOffset);`

I think 'LastVisibleItemIndex' is nextIndex actually what is different FirstVisibleItem & CenterItemIndex? 

Thank you Update :) , very well worked Scrolled!

**Comment by pierre01** [comment]
The Scrolled event works on IOS and Android. This solves my issues. 
I consider it as a good Workaround.
Closing the bug Thanks @dpa456 & @PureWeen

**Comment by pierre01** [comment]
Although the event arguments (e.FirstVisibleItemIndex, e.CenterItemIndex, e.LastVisibleItemIndex) to the scrolled event are inconsistent across platforms 
on Ios: 
   screen 0 = 0,0,1
   screen 1 = 0,1,2   
   screen 2 = 1,2,2
on android:
   screen 0 = 0,0,0
   screen 1 = 1,1,1   
   screen 2 = 2,2,2

**Comment by baselbj** [comment]
I am testing it on UWP when using mouse neither  ScrollToRequested or Scrolled but when I pragmatically scrolled the ScrollToRequested works.

any workaround?

**Comment by chaoyebugao** [comment]
> Although the event arguments (e.FirstVisibleItemIndex, e.CenterItemIndex, e.LastVisibleItemIndex) to the scrolled event are inconsistent across platforms
> on Ios:
> screen 0 = 0,0,1
> screen 1 = 0,1,2
> screen 2 = 1,2,2
> on android:
> screen 0 = 0,0,0
> screen 1 = 1,1,1
> screen 2 = 2,2,2

Problem still exists on iOS， XF version: 4.8.0.1364
