### ISSUE TITLE
[Bug] Scrolling issues in Android 9.0 Pie

### ISSUE THREAD

**Issue by VasenevEA** [xamarin/Xamarin.Forms#7166]
### Description
When Android phone having version 9.0 Pie, the scrolling is stuck and scroll in the wrong direction.
### Steps to Reproduce

1. Create ListView with 50+ items (more than one screen)
2. Set Rotation of ListView  to 180
3. Set Rotation of ItemTemplate to 180
4. Swipe fast ( up -> buttom) , that request Fling action

### Expected Behavior
Typical behavior of scrolling
### Actual Behavior
Scroll direction changed to 180 degrees
### Basic Information

- Version with issue:
Xamarin.Forms v4.1.0
- Last known good version:
Any
- IDE:
Visual Studio Community 19

### Reproduction Code
 [ChatUIXForms](https://github.com/rdelrosario/ChatUIXForms)

**Comment by PureWeen** [comment]
@VasenevEA have you tried this with CollectionView?

**Comment by VasenevEA** [comment]
> @VasenevEA have you tried this with CollectionView?

Yes. Same behavior

**Comment by paleicikas** [comment]
any changes pending?

**Comment by paleicikas** [comment]
Android bugfix: https://android-review.googlesource.com/c/platform/frameworks/native/+/800996/1/libs/input/VelocityTracker.cpp
React bugfix: https://github.com/facebook/react-native/commit/b971c5b

**Comment by Liminiens** [comment]
@paleicikas do you know if it's possible to create a workaraound while this issue is not fixed?

**Comment by mabdollahiasl** [comment]
I have this problem too,

**Comment by Swiftee** [comment]
I've got the same issue too. Are there any workarounds?

**Comment by vshapenko** [comment]
Any updates on issue? This issue makes collection view unusable on some devices with specific android/vendor combination (i.e. samsung/android 9)

**Comment by tvm-anand** [comment]
Any workarounds?

**Comment by taublast** [comment]
Hi from the same same boat, if you have any workarounds for Android while it's not fixed please share any ideas!

**Comment by taublast** [comment]
Hey a very diagnostic sign, could help debugging - the scroll bar position!

Layout:
ListView 
Rotation="180" FlowDirection="RightToLeft", 
Cell Template 
Rotation="180" FlowDirection="LeftToRight"

Result:
case 1:
nice chat list with scroll bar on the right side.

case 2 - android 9 bug:
nice(?) chat list, but.. scroll bar on the left side, and while scroll works as intended when dragging, when you swipe it scrolls to the wrong direction.

**Comment by tvm-anand** [comment]
I dropped the idea of moving with rotation.I implemented the chat according to this repo **(https://github.com/jamesmontemagno/app-monkeychat )**. There is no need to rotate the list

**Comment by taublast** [comment]
Thanks, unfortunately didn't solve what the rotated list does: 
- with list with FillAndExpand and rotated 180 messages start to appear in bottom of the screen, then they are filling the blank space from bottom to top as long as more messages are incoming. With a non rotated list one would have to resize and reposition the list to obtain such effect what would bring more visual artifacts among different os and devices. When it's required by design would prefer to use rotation.. :P

**Comment by mabdollahiasl** [comment]
any updates?

**Comment by mabdollahiasl** [comment]
after a lot of work I could solve the problem.
I Use CollectionView with custom rendrer in android:

```
[assembly: ExportRenderer(typeof(CollectionView), typeof(ExCollectionViewRenderer))]

namespace Healx.Droid.CustomRenderer
{
    public class ExCollectionViewRenderer : CollectionViewRenderer
    {
        public ExCollectionViewRenderer(Context context) : base(context)
        {
            
        }
        private int dy = 0;
        public override void OnScrolled(int dx, int dy)
        {
            this.dy = dy;

            base.OnScrolled(dx, dy);
        }
        public override bool Fling(int velocityX, int velocityY)
        {

            return base.Fling(velocityX, Math.Abs(velocityY) * Math.Sign(dy));

        }

        protected override void OnElementChanged(ElementChangedEventArgs<ItemsView> elementChangedEvent)
        {
            
            base.OnElementChanged(elementChangedEvent);
        }
    }
    
}

```

**Comment by Liminiens** [comment]
Can confirm that fix above works

**Comment by xamiell** [comment]
I have this problem too.
Running on Android 9.0 the same behavior.

**Comment by angelru** [comment]
Any advance?

**Comment by angelru** [comment]
The same issue...
