### ISSUE TITLE
[Bug] Animations are not working in 4.2.0.709249 

### ISSUE THREAD

**Issue by Nullstr1ng** [xamarin/Xamarin.Forms#7291]
### Description
I have some part of my apps that animates. Fading in and out and translating from A to B. They are all working in 4.1.0.673156 but after upgrading to 4.2.0.709249, animations are not working anymore. FadeTo and TranslateTo are getting called when debugging. But no animations are happening. 

### Steps to Reproduce
Use Xamarin.Forms version 4.1.0.673156 and have some small animations like FadeTo and TranslateTo then upgrade to the latest version: 4.2.0.709249

### Expected Behavior
It should animate

### Actual Behavior
It's not animating

### Basic Information

- Version with issue:
- Last known good version: 4.1.0.673156
- IDE: Visual Studio 2019 Preview 2
- Platform Target Frameworks: 
  - iOS:  _I have only tested in Android_
  - Android: 8.1
  - UWP:  _I have only tested in Android_
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
Emulator and Xiaomi Redmi 5 Plus

### Screenshots
n/a

### Reproduction Link
n/a

**Comment by Nullstr1ng** [comment]
In version **4.1.0.709244** - The animations are also working

**Comment by jfversluis** [comment]
Could you please see if #7255 described your issue?

**Comment by Nullstr1ng** [comment]
The same I guess but in my code, I am using these

```
GridCoursePreview.FadeTo(1, 300, Easing.CubicInOut);
await GridCoursePreview.TranslateTo(0, 0, 300, Easing.CubicInOut);
```

That let's my Grid fade in and scroll up fast when previewing a Course full description and same FadeTo and TranslateTo methods are used to close the Grid control.

![anim_prev](https://user-images.githubusercontent.com/260633/63772234-3e62db00-c90b-11e9-8264-016def55d940.gif)

I can only test in my actual device running Android 8.1 API 27 and Emulator which runs the same versions.

**Comment by lassana** [comment]
Same problem, animations are completely broken on Android.

**Comment by hudaIT** [comment]
Same problem for me. Animations completely disappeared at Android 9 with 4.3.0.1099-nightly.

**Comment by KSemenenko** [comment]
Same problem

**Comment by mkieres** [comment]
Yep, not working for me either

**Comment by Nullstr1ng** [comment]
anyone got a workaround for this in version 4.2.0.709249 ? I need the Scrolled event in CollectionView which is only available in 4.2.0.709249

**Comment by jfversluis** [comment]
@Nullstr1ng Not one I'm aware of at this point, sorry. I see the fix is merged into 4.2 so a new release with the fix should be here in a reasonable amount of time.

**Comment by petermajor** [comment]
@Nullstr1ng 

Yes. If you're desperate, you can use reflection:

```
public static class ReflectionExtensions
    {
        static readonly Lazy<FieldInfo> _androidTicker_AnimatorEnabled;

        static ReflectionExtensions()
        {
            _androidTicker_AnimatorEnabled = new Lazy<FieldInfo>(Get_AndroidTicker_AnimatorEnabled);
        }

        static FieldInfo Get_AndroidTicker_AnimatorEnabled()
        {
            var type = Type.GetType("Xamarin.Forms.Platform.Android.AndroidTicker, Xamarin.Forms.Platform.Android", true);
            var fieldInfo = type.GetField("_animatorEnabled", BindingFlags.NonPublic | BindingFlags.Instance);
            return fieldInfo;
        }

        // Fix for https://github.com/xamarin/Xamarin.Forms/issues/7291
        public static void AndroidTicker_SetAnimatorEnabled()
        {
            try
            {
                var fieldInfo = _androidTicker_AnimatorEnabled.Value;
                fieldInfo.SetValue(Ticker.Default, true);
            }
            catch
            {
                Console.WriteLine("Error setting AndroidTicker._animatorEnabled via reflection.");
            }
        }
    }
```

**Comment by mdbill** [comment]
Some animations fixed, but still broken in 4.2.0.778463
I have a visual.Rotateto and visualTranslateto. One or both of those is not working.

**Comment by BioTurboNick** [comment]
@samhouts Animations not working on 4.2.0.778463. It's like they are jumping to their end state and staying there, regardless of the other settings for the animation.

This is on Android 9.0, Samsung Galaxy S9+.

The workaround with developer options doesn't seem to work.

**Comment by jfversluis** [comment]
@mdbill could you confirm that for you it also had to do with the power saving mode?

**Comment by mdbill** [comment]
It's not power saving mode for me.  I downgrade to 4.1 and it works again.
I'm using an 8.1 emulator and android 7 device.

**Comment by maexsp** [comment]
It is fixed with 4.3.0.778476-pre1. I´ve tested it on Samsung tablet and Huawai phone, iPad and UWP! It was not a power saving issue. Thanks for the fix Xamarin-Team.

**Comment by jfversluis** [comment]
That is great to hear @maexsp! Thanks!

@mdbill sorry to bother you once again but would it be possible to try 4.3-pre1 to see if that fixes your issue?

**Comment by mdbill** [comment]
Yes, fixes my issue.  Thanks!

**Comment by DanKyungu** [comment]
I Confirm, it's fixed ! Thx

**Comment by sankar7047** [comment]
I still see issue with **RotateTo** animation in **Samsung** devices running on **Android 9**. I have tried 4.1x, 4.2x, 4.3x and 4.4x-pre1. Does anyone else face the same?
