### ISSUE TITLE
[Bug] Label LineBreakMode not working in CarouselView and probably a CarouselView bug too

### ISSUE THREAD

**Issue by Nullstr1ng** [xamarin/Xamarin.Forms#7368]
### Description
Just thought I'd share this bug I found in Label where LineBreakMode is not working in CarouselView. It also appears in ListView before but I think it was fixed already. I also think there's a bug in CarouselView? But I'm not sure if this is a feature or a bug. It will be more clear in ScreenShot section.

### Steps to Reproduce

1.  Create a CarouselView with items and 
2.  just have the Label as its ItemTemplate

### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version: (unknown)
- IDE: VS 2019 Prev 2
- Platform Target Frameworks: 
  - iOS:  I was only able to test it in Android
  - Android: 8.1 API 27
  - UWP:   I was only able to test it in Android
- Android Support Library Version: 
- Nuget Packages: Alex Rainman's CarouselView
- Affected Devices: So far, I have only tested in Xiaomi Redmi 5 Plus, and Android Emu.

### Screenshots

ss 1 the "Label Inside X.F CarouselView" label below the title is not wrapped even if the LineBreakMode is already set to WordWrap.
![image](https://user-images.githubusercontent.com/260633/64171796-17198a00-ce86-11e9-8982-a6b1fca60069.png)

ss 2 possible CarouselView bug or a feature - here you can see the title that should be on another CarouselItem is showing
![image](https://user-images.githubusercontent.com/260633/64171921-695aab00-ce86-11e9-8e60-8bf4042fc803.png)

### Reproduction Link

https://github.com/Nullstr1ng/XamarinBugCollections/tree/Controls/Label/LineBreakMode

**Comment by hartez** [comment]
Fixed in the latest pre-release (4.3.0.819712-pre2).

**Comment by emanuelecastelli** [comment]
Hi, 
i still have this error in iOS (ok in Android).

My code:
```
<CarouselView.ItemTemplate>
                <DataTemplate x:DataType="onboarding_core:OnboardingItemContent">
                    <StackLayout VerticalOptions="FillAndExpand">
                        <StackLayout VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand">
                            <StackLayout HorizontalOptions="Center" IsVisible="{Binding ShowAppLogo}">
                                <BoxView HorizontalOptions="Start" Style="{StaticResource OnboardingTitleRedMark}" />
                                <Label
                                    HorizontalOptions="Start"
                                    Style="{StaticResource OnboardingTitle}"
                                    Text="{Binding LogoTitle}" />
                            </StackLayout>
                            <Label Style="{StaticResource WelcomeTitle}" Text="{Binding Title}" HorizontalTextAlignment="Center"/>
                            <Label Style="{StaticResource WelcomeDescription}" Text="{Binding Content}" HorizontalTextAlignment="Center" LineBreakMode="WordWrap"/>
                            
                            <ff:CachedImage
			                    Margin="0,60,0,0"
                                HeightRequest="140"
			                    Source="{Binding AnimatedImageName}"/>

                            <Image
                                IsVisible="{Binding IconName, Converter={StaticResource IsNotNullOrEmpty}}"
                                Margin="0,60,0,0">
                                <Image.Source>
                                    <FontImageSource
                                        FontFamily="{Binding IconFont}"
                                        Glyph="{Binding IconName, Mode=OneWay}"
                                        Size="140"
                                        Color="{AppThemeBinding Light={StaticResource ColorGrey90},
                                        Dark={StaticResource ColorGrey20}}" />
                                </Image.Source>
                            </Image>
                        </StackLayout>
                    </StackLayout>
                </DataTemplate>
            </CarouselView.ItemTemplate>
```

Two labels with `Title` and `Content` binding are not wrapped.

Xamarin.Forms version: 5.0.0.2515

Thx
