### ISSUE TITLE
[Bug] Image control fails to load image from URI on Andriod

### ISSUE THREAD

**Issue by chad-ramos** [xamarin/Xamarin.Forms#7684]
### Description

- `<image>` is not loading image from URI on Android
- The issue first happened post VS 16.3.x update on 9/24/19
- Possibly related #7248 
  - Shows closed but if related, a regression might have happened. 

### Steps to Reproduce

1. Create a new Forms project
2. Add an image

```xml
<StackLayout>
    <Image Source="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Galactic_Radiation_and_Background_satellite_%28square_crop%29.jpg/150px-Galactic_Radiation_and_Background_satellite_%28square_crop%29.jpg"
           HeightRequest="300" />
</StackLayout>
```

3. Deploy to emulator or device

### Expected Behavior

- Image to display on the screen as it does in iOS and as it did post VS 16.3.x update

### Actual Behavior

- The image does not display on screen for Android
- The application continues without interruption
- Debug shows an error. 

### Basic Information

- Version with issue: 
  - 4.2.0.778463
- Last known good version:
  - 4.2.0.778463
    - Broke post VS 16.3.x update
- IDE:
  - VS 2019 16.3.1
- Platform Target Frameworks: 
  - Android: 
    - 8.1 or 9.0
- Affected Devices:
  - All emulators and hardware

### Screenshots

![image](https://user-images.githubusercontent.com/3170200/65639800-7f075000-dfae-11e9-8d32-4e740707e281.png)

**Comment by PureWeen** [comment]
This has been fixed on *4.2.0.815419*

**Comment by FetFrumos** [comment]
I use 4.2.0.815419 and have same issue:

ImageLoaderSourceHandler: Could not retrieve image or image data was invalid: myurl
Could not load image named: {0}: delete
but this url open in brouser

**Comment by ddo88** [comment]
i upgrade to the version the version 4.2.0.815419
but still have the problem

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/7751#issuecomment-537156355

**Comment by chad-ramos** [comment]
@FetFrumos @ddo88 For reference, I upgraded to `4.2.0.815419` and it resolved my issues.

**Comment by ddo88** [comment]
I'm sorry, if it worked, I just had to remove the emulator application and deploy again.

thanks
