### ISSUE TITLE
[Bug] Setting CarouselView.CurrentItem to an item doesn't display that item

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7924]
### Description

Setting the `CarouselView.CurrentItem` property, via a data binding, doesn't result in that item being displayed. The code below results in the first item (0) in the collection being displayed, rather than the fourth:

```
        public MonkeysViewModel()
        {
            source = new List<Monkey>();
            CreateMonkeyCollection();

            CurrentItem = Monkeys.Skip(3).FirstOrDefault();
            OnPropertyChanged("CurrentItem");
            //Position = 3;
            //OnPropertyChanged("Position");
        }
```

Note that setting the `Position` property does cause the 4th item in the collection to be displayed.

If you look at the property changed handler for `CurrentItem`, it's meant to cause the `Position` property to be updated:

```
		static void CurrentItemPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			var carouselView = (CarouselView)bindable;
			var args = new CurrentItemChangedEventArgs(oldValue, newValue);
			var command = carouselView.CurrentItemChangedCommand;

			if (command != null)
			{
				var commandParameter = carouselView.CurrentItemChangedCommandParameter;
				if (command.CanExecute(commandParameter))
				{
					command.Execute(commandParameter);
				}
			}

			carouselView.SetValueCore(PositionProperty, GetPositionForItem(carouselView, newValue));
			carouselView.CurrentItemChanged?.Invoke(carouselView, args);
			carouselView.OnCurrentItemChanged(args);
		}
```

Therefore, after setting the `CurrentItem` property I'd expect the `Position` property to be updated and the 4th item in the collection to be displayed, rather than the 1st.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the "Set current item and position" page.

### Expected Behavior

The Squirrel Monkey card is displayed.

### Actual Behavior

The Baboon card is displayed.

### Basic Information

- Version with issue: 4.3-pre3
- Last known good version: N/A
- IDE: VS Mac 8.3.2
- Platform Target Frameworks: 
  - iOS: 13.0
  - Android: API 28 

### Screenshots

![Simulator Screen Shot - iPhone X - 2019-10-10 at 13 26 56](https://user-images.githubusercontent.com/8092460/66569749-27e3ac80-eb64-11e9-9e54-721c0613c134.png)

### Reproduction Link

[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3712578/CarouselViewDemos.zip)

**Comment by jfversluis** [comment]
To make it even more fun:

When you remove the binding on `Position` _or_ you move the declaration for the `Position` binding to **before** the declaration of the `CurrentItem` one it does work. So clearly something in the conjunction of these two properties something is not going right.

**Comment by boris-df** [comment]
Should this be solved in 4.4.991640?
I see exact this problem in my application
I just started looking at CarouselView and i see this behaviour:
- in my ViewModel (where i have the Items and the CurrentItem Property) I have 3 Items
- If i set the CurrentItem Property, the Setter is beeing called 3(!) times in a row: 1. it's set to the item i want it to; 2. called again, now from the PropertyChanged Event i think; still the correct item; Then it's called again (i cannot see a call-stack so i think it's comming from within Xamarin.Forms) and here it's set back to the item it was before.

So on the device i see the CarouselView moving a tiny little bit as it tries to change the CurrentItem but then it stopped/jumped back to where it was

I was on 4.3 when i saw this thread so i updated to 4.4.991640 but still the same behaviour.

**Comment by boris-df** [comment]
Addon: 
If i bind the "Position" Property instead, this happens (3 items are loaded, the first item is visible, no CurrentItem or Position was called in my code before):
- The very first time i set a Position (to 1 for example), the same problem exists (item 0 still beeing displayed; The setter gets called 3 times - the last time it is set back to 0)
- If i set the Position property again to 1, it works! The Setter now is called just 2 times

**Comment by boris-df** [comment]
Same/similar Problem described here: https://www.gitmemory.com/issue/xamarin/Xamarin.Forms/8671/559406993

**Comment by nate123456** [comment]
I can confirm that this is still occurring on the latest stable Xamarin release with iOS. In case this isn't already mentioned, I also noticed that when I set the CurrentItem from my ViewModel, the property gets set 3 times: 

1. When I set it from my code- the new value is what I chose
2. From the View- the new value is what I chose
3. Once again from the View, but this time the new value is the previous Current Item (the value it was before I set it in the ViewModel).

The behavior I see on the view is that it will jump to the item I set it to for a single frame then immediately back to the previous item.

[Here](https://github.com/nate123456/CarouselViewTest) is a demo which reproduces the issue. Run the app with iOS and hit the next button to see the behavior.

A side note- this issue does not occur when setting the Position property from the ViewModel. Also, it does not occur in Android.

**Comment by rmarinho** [comment]
Hi @nate123456  and @boris-df  can you try this nuget and see if it's still a issue.

[debug (9).zip](https://github.com/xamarin/Xamarin.Forms/files/4247288/debug.9.zip)

**Comment by nate123456** [comment]
> Hi @nate123456 and @boris-df can you try this nuget and see if it's still a issue.
> 
> [debug (9).zip](https://github.com/xamarin/Xamarin.Forms/files/4247288/debug.9.zip)

I tried it and it seems to scroll 'correctly', but something is still wrong with the behavior of the associated properties. I have the CurrentItem and Position shown below the CarouselView and they appear to be changing correctly, then going back to the previous value, then changing again to the correct value. See the gif below- watch the values below the CarouselView and notice how the values are updated, then set back to the previous value, then set again.

![example](https://i.imgur.com/3Qt4rus.gif)

My instinct based off the behavior is that the changes made in those packages seem to add a 3rd change to those properties, which results in the correct behavior, but doesn't seem to address the root cause.

If you want to experience the behavior yourself you can use my demo from my previous post- I made a branch called TestPackages that you can checkout and try (you'll need the packages as a package source of course).

**Comment by RonnyBansemer** [comment]
@samhouts The issue continues in XF 4.5.0.356. Setting CurrentItem in ViewModel (even on MainThread) does not change the datatemplate (2-way-binding). Indeed, the CurrentItem updates in ViewModel after changing view through swiping.  
There seems to be a backreport issue. Even IndicatorView does not update after CarouselView view change.

**Comment by samhouts** [comment]
I think this will be resolved by https://github.com/xamarin/Xamarin.Forms/pull/9500.

**Comment by rmarinho** [comment]
This should be fixed on 4.5.0.495 , latest service release we pushed. 

Please open new bug if it's not. 

Thanks

**Comment by lorne-olo** [comment]
still a problem on iOS in 4.8.

**Comment by Saigronas** [comment]
Can confirm this is still a problem on iOS with Xamarin forms 5.0.0.2487. Binding both Position and CurrentItem in a CarouselView broke the view, so that setting the property bound to Position in viewmodel to not work.

Solved by removing binding to CurrentItem.
