### ISSUE TITLE
[Bug] Entry HorizontalTextAlignment does not work

### ISSUE THREAD

**Issue by acaliaro** [xamarin/Xamarin.Forms#8140]
### Description
Setting HorizontalTextAlignment in an Entry does not work
### Steps to Reproduce

1. Add an Entry

```
                <Entry
                    Grid.Row="0"
                    Grid.Column="1"
                    FontSize="Large"
                    HorizontalTextAlignment="Center"
                    Keyboard="Numeric"
                    Placeholder="{utility:Translate Quantita}"
                    Text="{Binding Quantita}" />
```

2. Set HotizontalTextAlignment to "Center"

### Expected Behavior
Text should appear centered
### Actual Behavior
It's left aligned

### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version: 4.2.0.xxxxx
- IDE: Visual Studio 2019
- Platform Target Frameworks: 

  - Android:  

- Affected Devices: Zebra TC51

### Reproduction Link

![image](https://user-images.githubusercontent.com/5759350/67261459-05755b80-f4a1-11e9-95fd-a7b0fc153efd.png)

**Comment by xamarindevelopervietnam** [comment]
related to https://github.com/xamarin/Xamarin.Forms/issues/8137

**Comment by czuvich** [comment]
Is there a workaround?

**Comment by acaliaro** [comment]
I think you can try with a CustomRenderer… @czuvich

**Comment by czuvich** [comment]
> I think you can try with a CustomRenderer… @czuvich

It looks like Forms needs to set the Gravity along with the TextAlignment on the EditText.  I was able to fix it.

**Comment by Adlorem** [comment]
It is working in previous version of Forms.

**Comment by samhouts** [comment]
@acaliaro  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Basti82b** [comment]
> It is working in previous version of Forms.

I can confirm that. It's a bug in XF 4.3.0.908675.

**Comment by acaliaro** [comment]
> @acaliaro  Can you please attach a small project that demonstrates this issue? Thanks!


[HorizontalTextAlignment.zip](https://github.com/xamarin/Xamarin.Forms/files/3767957/HorizontalTextAlignment.zip)

**Comment by rotorgames** [comment]
I have the same issue with 4.3.0.947036. Android only.

**Comment by AdrianoRochedo** [comment]
Same issue for me !

![image](https://user-images.githubusercontent.com/46300640/67918087-b9e64000-fb79-11e9-85a1-f76728c79a94.png)

**Comment by ChaseFlorell** [comment]
add me to the list of users running into this same issue.

**Comment by thomasonb** [comment]
Add me to the list of users as well.

**Comment by akamud** [comment]
Same problem here.

**Comment by veringm** [comment]
Also add me to the list of users as well.

**Comment by Xiokraze** [comment]
Same here

**Comment by thomasgalliker** [comment]
Bug is still present in Xamarin.Forms 4.3.0.991211. Going back to 4.2.0.910310, the Entry texts are aligned again. I wonder how such things can pass a release process? I mean, we all code day and night and mistakes happen - but this one looks like a very fundamental one.

**Comment by czuvich** [comment]
The workaround I posted fixed it for me.

**Comment by thomasgalliker** [comment]
@czuvich thanks. I already have a bunch of custom renderers for such fixes...

**Comment by ChaseFlorell** [comment]
can't roll back, just sold the business on the new CollectionView, and it wasn't quite right in 4.2.
@czuvich if you've been able to successfully resolve this within the renderer, how would you feel about submitting a PR? I'm sure it'd be welcomed by the Forms team.

**Comment by czuvich** [comment]
@ChaseFlorell It's just a temporary "hack".  They will likely fix it differently.  I'm not an Android expert :)

**Comment by nkuznetsov** [comment]
Things breaking here and there after upgrading to newer version of Forms has been a tradition since the beginning.

Here's a fast fix that worked for me - it was suggested elsewhere (can't remember the ticket #). This is for those who already have a thousand renderers fixing other things and don't want to add another. Add the following to manifest (in the application tag):

android:supportsRtl="true"

**Comment by acaliaro** [comment]
> Things breaking here and there after upgrading to newer version of Forms has been a tradition since the beginning.
> Here's a fast fix that worked for me - it was suggested elsewhere (can't remember the ticket #). This is for those who already have a thousand renderers fixing other things and don't want to add another. Add the following to manifest (in the application tag):
> android:supportsRtl="true"

Realy?

**Comment by veringm** [comment]
As suggested by @nkuznetsov, android:supportsRtl="true" work for me

**Comment by gceaser** [comment]
Yeah the manifest update fixed it for me also:

<application android:label="My App Name" android:supportsRtl="true"></application>

**Comment by stoff99** [comment]
Same issue here. Is there a plan to solve it in a Form bugfix version or do we rly need to make some dirty workaround fixes like android:supportsRtl="true" ?

**Comment by akamud** [comment]
This has a 4.3 release label but I don't see any PR linked. Is this actually being fixed?

**Comment by cauefelipe11** [comment]
Works to me with android:supportsRtl="true" workaround.

**Comment by AdrianoRochedo** [comment]
Do not work to me. I am targeting to Android >= 6.

Em ter., 10 de dez. de 2019 às 10:20, cauefelipe11 <notifications@github.com>
escreveu:

**Comment by hartez** [comment]
This is fixed by #8658 and should be in an upcoming service release for 4.3.

**Comment by thomasgalliker** [comment]
@hartez are you sure it's in 4.3? The bug still appears to be present in 4.4.0.991265.

**Comment by hartez** [comment]
> @hartez are you sure it's in 4.3? The bug still appears to be present in 4.4.0.991265.

Yes. The change was merged into the 4.3 branch 8 days ago and the 4.4 branch 6 days ago. 4.4.0.991265 was pushed to NuGet 7 days ago, so if the changes were in that version we'd have bigger problems than text alignment :)

The changes didn't make the last service release for 4.3; they should be in the next one. And an upcoming service release for 4.4.

**Comment by stavroaudi** [comment]
I'm on 4.4.0.991265 and the bug is still present. I'm still using the supportsRtl workaround in the meantime.

**Comment by abhibl** [comment]
Add the following to manifest (in the application tag):
android:supportsRtl="true"

**Comment by thomasgalliker** [comment]
@samhouts will this fix be part of the upcoming stable 4.5.x release? If so, can you assign it the the correct milestone?

**Comment by thomasgalliker** [comment]
Hooray! It seems to be solved in Xamarin.Forms 4.4.0.991537 👍

**Comment by samhouts** [comment]
huzzah!! closed by https://github.com/xamarin/Xamarin.Forms/pull/8658

**Comment by ousspero** [comment]
closed 18 hours ago, so i have to update now !, i hope this will not impacts the other features
