### ISSUE TITLE
[Bug] TextDecorations don't work

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#8272]
# Description

Tested on iOS. I set underline or strikethrough on a label and nothing renders using 4.3.0 stable. 

### Basic Information

- Version with issue: 4.3.0
- Last known good version: ?
- Platform Target Frameworks: 
  - iOS:  12.2, 13.1

### Screenshots

<img width="1201" alt="Screenshot 2019-10-27 20 29 05" src="https://user-images.githubusercontent.com/41873/67683087-af9c2a00-f95e-11e9-8349-b114c18bf6e9.png">

### Reproduction Link

https://github.com/davidortinau/fabriculous/blob/bug/decorations/Fabriculous/Pages/ButtonsPage.xaml#L42

**Comment by alanag13** [comment]
I noticed this while finishing up a different PR and noted the cause here. Definitely a regression, I might be able to fix when I close that PR up soon. https://github.com/xamarin/Xamarin.Forms/pull/4330#issuecomment-545731143

**Comment by davidbritch** [comment]
Other users have also discovered that TextDecorations don't work, so it'd be good to get a fix out in a SR.

**Comment by akamud** [comment]
Just noticed this on my app on 4.3 too.

**Comment by Mikilll94** [comment]
I have the same problem.

**Comment by tomahutbui** [comment]
same issue with 4.3 xf. version 4.2 work fine

**Comment by victorbotamedi** [comment]
@Mikilll94 a working workaround is to use a `Span` insetad. The `TextDecorations` of a span seems to be working fine

**Comment by APopatanasov** [comment]
What is the status of this issue? It's been logged from almost two months. Is a fix expected to be made soon? 

The issue is affecting our image verification tests. The TextDecorations property is a top level property for the Label control and replacing Label with Span in every place we are using TextDecorations is not a very good option according to me.

**Comment by akamud** [comment]
I see this is not In progress anymore, no updates on the related PR or updates here. What's the status for the issue? Should we expect it in a 4.4 SR?

**Comment by davidbritch** [comment]
Also confirming that this still doesn't work on iOS, unless you use a `Span`.

**Comment by xleon** [comment]
Same stuff in 4.4

**Comment by Elinareso** [comment]
Hi everyone! Same issue here!!, We had to release our app with this issue. Is there a expected date to release this fix?

**Comment by BlueCoder77** [comment]
This is still broken in 4.4. When is a fix expected for this?

**Comment by quentinR0bert** [comment]
Any news about a fix in a 4.4 sr or 4.5 ?

**Comment by akamud** [comment]
The lack of ANY kind of support or message from a Xamarin team member in this issue really worries me.

**Comment by samhouts** [comment]
We're here! This should have been given more priority, but it got shuffled around and lost. It's unfortunate, but it happens. Next time, give me a ping, and I'll make sure we've got it appropriately prioritized.

In the meantime, I'll move this BACK to our sprint backlog, and hopefully we can get it resolved soon.

Thanks!

**Comment by PureWeen** [comment]
FYI this PR has fixes for this
https://github.com/xamarin/Xamarin.Forms/pull/4330

So we can finish that one up or extract the parts that at least fix this issue

**Comment by volcano619** [comment]
would this be fixed in the next release ?

**Comment by shidem** [comment]
Also confirming that this still doesn't work on iOS, unless you use a Span. Using Xamarin Forms 4.5.0.356. @samhouts This issue has languished for far too long IMHO.

**Comment by akamud** [comment]
Hi @samhouts, I'm afraid we are getting left in the dark here again. It has been over 1 month since the last update from the team, and again, I have no idea if this is being worked on or not.

**Comment by shidem** [comment]
@samhouts What do I need to do to escalate issue? It needs fixing! Nobody seems to be a paying attention except us. Boss wants answers, not workarounds.

**Comment by shidem** [comment]
I was being polite earlier, but now it's time to shout - "FIX IT NOW!!!!!"

**Comment by xleon** [comment]
@shidem  I agree this should have been fixed already, but shouting with bad manners won't encourage anyone to do their job, but the oposite. This is an open source project and you are free to go and fix it yourself rather than crying like a baby.

**Comment by shidem** [comment]
@xleon @samhouts My humble apologies for shouting. But I do see a large number of PR's that have not been acted on. Also, Microsoft owns this and I appreciate the fact it is open sourced. My expectation is that things would continue improve. I let my frustration get the best of me. However, the frustration remains.

**Comment by Mikilll94** [comment]
@shidem @samhouts 
The problem is that Xamarin team is constantly releasing new versions with new features while ignoring bugs from previous versions.

I prefer less features and more stability than opposite.

**Comment by shidem** [comment]
@xleon @samhouts @Mikilll94 I'm with ya Mikill! Not a buzz kill for me, but others have indicated massive code refactoring to incorporate the workaround @victorbotamedi  proposed. I hope my posts escalate this issue to resolution and incorporation into the code base. A number of pull requests appear to be languishing; I suspect the maintainers/owners are overwhelmed and dealing with high impact issues first and getting those disseminated to the community.

I'd contribute to the effort, but others have already addressed the issue with their PR. I'm trying to reduce the noise and wave my hand to get the attention of the repo owners that issues need to be addressed, and then features.

**Comment by jsuarezruiz** [comment]
Alan's PR #4330 will fix this issue (and others). I will help and review the PR to merge it soon. In the meantime, I have created a fix for this specific issue https://github.com/xamarin/Xamarin.Forms/pull/10066 (only fix TextDecoration issue on iOS, nothing related with triggers and other platforms)

![fix8272](https://user-images.githubusercontent.com/6755973/77409838-380de200-6dba-11ea-94f6-f8941087d773.gif)

**Comment by EnglishDave** [comment]
This is still not working for Spans added to FormattedString and allocated to Label.FormattedText. using XF 4.8.0.1451 or XF 5.0.0.1487-pre1. Please re-open and provide a version estimate for when a fix will be available. Thanks.

**Comment by Cacuci** [comment]
I have same problem in Android. I am using Xamarin.Forms" Version="4.8.0.1364".

**Comment by WanftMoon** [comment]
Confirm, text decoration (strikethrough) for span on iOS not working.

**Comment by pursey** [comment]
> Confirm, text decoration (strikethrough) for span on iOS not working.

I can also confirm this.

**Comment by volcano619** [comment]
This is still pending ??

**Comment by danielroth1** [comment]
For me, if TextDecorations needs to be changed the workaround only works if the labels TextDecorations property is set as well:

```
Label label = new Label();

// The Workaround with FormattedString
FormattedString formattedString = new FormattedString();
formattedString.Spans.Add(new Span
{
    Text = "test"
});
label.FormattedText = formattedString;

// Later changes to TextDecorations
TextDecorations decorations = TextDecorations.Strikethrough;
label.FormattedText.Spans[0].TextDecorations = decorations;
label.TextDecorations = decorations; // needs to be there although label.Text == null
```

haven't tested it with bindings.

**Comment by thomasgalliker** [comment]
Confirming that the problem still exists in Xamarin.Forms 5.0.0.2244. As a workaround (which doesn't work in all scenarios, of course):

**Old code (which causes the problem):**
-                        <Label.FormattedText>
-                            <FormattedString>
-                                <Span Text="{language:Translate Reminders_NextNotificationDate}" />
-                                <Span Text=" " />
-                                <Span Text="{Binding NextNotificationDate, Converter={StaticResource RelativeDateTimeToStringConverter}}" />
-                            </FormattedString>
-                        </Label.FormattedText>

**New code (workaround):**
+                        <Label.Text>
+                            <MultiBinding StringFormat="{}{0} {1}">
+                                <language:Translate Text="Reminders_NextNotificationDate" />
+                                <Binding Path="NextNotificationDate" Converter="{StaticResource RelativeDateTimeToStringConverter}"/>
+                            </MultiBinding>
+                        </Label.Text>

**Comment by irshadka** [comment]
Is there any fix?
