### ISSUE TITLE
[Bug] Xamarin.Forms.Xaml.XamlParseException => StaticResource not found for key

### ISSUE THREAD

**Issue by AbdellahOusrhireDev** [xamarin/Xamarin.Forms#8762]
### Description
I'm trying to show a native popover in Xamarin.Forms, embedding forms view in it, a Xamarin.Forms.Xaml.XamlParseException is thrown.

@davidortinau already made some comments on this subject years ago on this thread https://forums.xamarin.com/discussion/comment/283902/#Comment_283902

<img width="1517" alt="Capture d’écran 2019-12-05 à 12 07 33" src="https://user-images.githubusercontent.com/32442464/70230128-f64c2380-1757-11ea-9020-5a12484ddfe5.png">
### Steps to Reproduce
1. https://gist.github.com/cpboyd/4a34d97985c4808a461acead5365554b (Thanks @cpboyd for the gist)

### Expected Behavior
Forms page is embedded a second time
### Actual Behavior
Xamarin.Forms.Xaml.XamlParseException => StaticResource not found for key
### Basic Information

- Version with issue:
- IDE: Visual Studio Community 2019 for Mac Version 8.3.10 (build 2)
- Platform Target Frameworks: 
  - iOS:  
Xamarin.iOS
Version: 13.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:08-0400
- Nuget Packages: Xamarin.Forms 4.3.0.991221
- Affected Devices: ios simulator/ iPad

### Reproduction Link
https://gist.github.com/cpboyd/4a34d97985c4808a461acead5365554b

**Comment by AbdellahOusrhireDev** [comment]
I've hacked a sample that reproduces the bug
[formsPopover.zip](https://github.com/xamarin/Xamarin.Forms/files/3927236/formsPopover.zip)

**Comment by PureWeen** [comment]
@AbdellahOusrhireDev I feel like this must be fixed with 8.4 because I downloaded your reproduction and it runs without giving me a Xaml exception. 

Is there anything I'm supposed to do other than just run the formsPopover sample?

**Comment by AbdellahOusrhireDev** [comment]
@PureWeen I hope it's fixed with 8.4 but currently, on the stable version that is **8.3.10 (build 2)** it's throwing. One thing I forgot to mention is that on the first time the popover opens nothing bad happen but when you close & reopen it it throws.

Please make sure you **reopen the popover more than once.**

**Comment by samhouts** [comment]
@AbdellahOusrhireDev I'm not seeing the XamlParseException, either. Can you please update Visual Studio and verify that you are still experiencing the issue? Thanks!

**Comment by AbdellahOusrhireDev** [comment]
@samhouts No, I'm **still experiencing the same issue**
Visual Studio For mac is updated to the latest version: **8.3.11 (build 1)**
Xamarin.Forms updated to **4.4.0.991265**

**Comment by samhouts** [comment]
@AbdellahOusrhireDev Checking in again! Are you still experiencing this issue with the latest stable version? Thanks!

**Comment by AbdellahOusrhireDev** [comment]
@samhouts same as before, reopening the popover a second time crashes with the xaml exception
VSmac is updated to the latest version: **8.4.3 (build 12)**
Xamarin.Forms updated to **4.4.0.991537**
