### ISSUE TITLE
[Bug] (UWP) Font Icons disappear after idle interval

### ISSUE THREAD

**Issue by papiermache** [xamarin/Xamarin.Forms#8783]
### Description
UWP app has font icons, which display correctly. Go for a coffee and chat a bit. Come back, the page is all intact and correct **except** all icons have disappeared.

### Steps to Reproduce

1. create a page, sprinkle some font icons on it.
2. wait.
3. observe, they have all disappeared

### Expected Behavior
Not to disappear.

### Actual Behavior
 Disppeared.

NOTE - in screen shots below, the disappeared items are Font Icons, The undisappeared ones are all PNGs - we were in process of converting.

### Basic Information

- Version with issue: 4.2, 4.3
- Last known good version: none
- IDE:
- Platform Target Frameworks:  .NET Standard 2.0
 - UWP:  Windows 10, version 1809 (10.0; Build 17763)

### Screenshots

![normal](https://user-images.githubusercontent.com/5385881/70332300-420dd400-180f-11ea-9c50-dcb7a27af89e.JPG)

![disappeared](https://user-images.githubusercontent.com/5385881/70332303-4639f180-180f-11ea-9cc3-cf28d2ca2a08.JPG)

**Comment by PureWeen** [comment]
@papiermache how long did you wait?

Do you have a repro by chance?

We have a gallery with FontIcon, I've waited a bit, and nothing is disappearing

![image](https://user-images.githubusercontent.com/5375137/70343829-7a181580-1815-11ea-8eb2-517c3d3739e7.png)

**Comment by papiermache** [comment]
Hi Shane,
How long?  I dunno, had the page up, gone for 10 mins or so then come back to find them all missing. Its consistent – all other devs/testers finding same issue.

How are you putting up the icons?  We’re using Image and ImageButton controls – and I think its more oftenon the ImageButton control (but that’s just my impression fwiw).
Regards, Rick.

**Comment by squinn7** [comment]
I would like to add that we have run into this issue as well on UWP. I did a customer meeting the other day and it happen to the app while demonstrating the app. It doesn't come up while developing but it does come up in normal usage. Not sure how long one would have to wait but I have seen the issue several times. Not sure of the exact cause. The life cycle suspend does not seem to trigger it but I tend to see it when I come back to the app from another program.

**Comment by VladislavAntonyuk** [comment]
Why not all icons disappear? Are there some other windows overlap under the current window?

**Comment by papiermache** [comment]
R u referring to the two screen shots?  As I doc’ed, the ones that did not disappear are PNG’s.  All the Font icons (3 on that page) disappeared.
And it’s not just this page .. ALL pages having Font Icons exhibit same behaviour.

**Comment by squinn7** [comment]
My colleague gave me a good hint. You can make the issue happen if you put your computer to sleep and resume it. Any font icon will be gone.

**Comment by rmarinho** [comment]
I can confirm if we test the ControlGallery, set the computer to sleep then wake it up and font's don't show . If you resize the app window they show up again.

**Comment by bmacombe** [comment]
Just a observation in general on UWP, if there is a display issue, like the one I made a PR for in #8214.  Resizing the window seems to always fix it.  Just adding this in case these are all symptoms of a general refresh issue in the UWP platform.  I couldn't find it when working on #8214, I just having a feeling it's lurking somewhere.

**Comment by MhAllan** [comment]
#9249

**Comment by BrayanKhosravian** [comment]
this issue can be reproduced by opening a page with icon and suspend the uwp app and wait for a while.
I waited a few minutes and noticed that the images where missing. 
It is interesting that the images do not disappear when the app is immediately unsuspended after suspending it.

**Comment by BrayanKhosravian** [comment]
So i found that "Font ImageSource" Gallery.
This is how the page looks like right after suspending the app.
After resuming the app it seems like the images or the whole view is not being updated. 
![image](https://user-images.githubusercontent.com/35541212/77904768-60e41a80-7285-11ea-9f73-5ad50faf8f49.png)

**Comment by BrayanKhosravian** [comment]
I think I fixed the issue.
A PR is incoming linked to this issue.

**Comment by LjiljanaKekic** [comment]
I still have a problem with the icons disappearing. I upgraded the Xamarin forms to the latest version and I still have that problem. So when I turn on the app and then minimize it or just open some other window so that my app is in the background, then after 10-15 seconds when I maximize the app again the icons disappear.

**Comment by holecekp** [comment]
I can also confirm that icons still disappear sometimes on UWP (tested in Xamarin.Forms 4.7.0.1080, but the issue was also in 4.6) The problem is hard to reproduce. I am using FontIconsSource for the icons. Some of the icons are in the shell menu and the others are used for ImageButtons. A strange thing is that the same icons disappear all the time.

I selected the second item from the shell menu and I minimized the application. When I restore the application, all icons from the shell menu are gone. When I hover mouse over a menu item, the icon for the item is shown again except for the first two menu items. Hovering mouse over them does not help.

Besides icons in the shell menu, another icon in the ImageButton disappears. Neither hovering mouse nor clicking on the ImageButton does help. Resizing window has no effect either.

**Comment by infinitbis** [comment]
I can also confirm that i have been having this issue on all the version i have run Xamarin forms on. Im currently on the latest one and still getting the same issue. This issue is actually not hard at all to replicated. just leave a page open, go to another page for a bit an come to it - all the icons are gone but if you hover over them with a mouse u can see the box where icons is an can actually click on it too. u just cant see it

**Comment by holecekp** [comment]
The issue has been closed but there are (at least) 3 people confirming that the issue still persists. If somebody from the Xamarin.Forms team is monitoring this discussion, could you please reopen the issue?

**Comment by jfversluis** [comment]
Since the original issue is months old, I think the best thing to do to bring this under the attention is open a new issue with all the info you have and a reproduction project based on the latest stable Xamarin.Forms version and refer to this issue. :)

**Comment by holecekp** [comment]
I have tried to prepare a reproduction project but I cannot reproduce the bug in a simplified project. I have tried both release version and the debug version which I suspended according to the instruction in the Microsoft documentation (https://docs.microsoft.com/en/visualstudio/debugger/how-to-trigger-suspend-resume-and-background-events-for-windows-store-apps-in-visual-studio?view=vs-2019).

**This does not mean that the bug does not exist!** It appears regularly in my full project in the version downloaded from Microsoft Store. I have tried to run the full project in Visual Studio and it works. It seems that only version from Microsoft Store is affected. Both the full project and the simplified one uses the same Xamarin.Forms version (4.7 SP 1).

Does anyone else have reproduction project?

**Comment by BurkusCat** [comment]
I am not experiencing the issue but some of my colleagues are. It happens when the app is minimised for them. It appears to be the same issue as #8293.

A machine where it was failing was running at 1920x1080 @ 125% DPI scale on Windows OS Build 18363.900.

**Comment by BrayanKhosravian** [comment]
Thats interesting. Because this also worked on a laptop from lenovo. Maybe it rly depends on the resolution?

**Comment by holecekp** [comment]
I did more testing. I suspected that it is a laptop issue (maybe some power-saving function) but it was wrong. I tested on three computers - one laptop and two PCs:
-The laptop and one PC is affected by the bug, the other PC is not.
- All of them has Windows version 1909 (build 18363.900).

**Comment by BrayanKhosravian** [comment]
@holecekp do u know the resulution of the pcs which are not affected?

**Comment by holecekp** [comment]
Unfortunately, I do not have access to the not affected PC at the moment. I will write its resolution later.

The affected devices are:
- PC - 1440 x 900 (100% scale)
- laptop - 1920 x 1080 (150% scale)

**Comment by BrayanKhosravian** [comment]
I cannot verify this issue with my new laptop.
This is very weird, as i cans till repro this with my old laptop.

Verification link:
![uwp_suspending](https://user-images.githubusercontent.com/35541212/87768919-28108700-c81d-11ea-9a14-8b7573035fa7.gif)

Project specs:
Taget framework: 1809 build 17763
min version: build 16299
XF version: 4.4.1.5 (**we use a local version of xf and cherry picked my fix**)

Specs of my new laptop: 
Resolution: 1920 x 1200
Scale: 125 %
OS Name	Microsoft Windows 10 Home
Version	10.0.18363 Build 18363
System Manufacturer	Dell Inc.
System Model	XPS 15 9500
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.1.3, 08.05.2020
Installed Physical Memory (RAM)	32,0 GB
gcard	NVIDIA GeForce GTX 1650 Ti

**Comment by holecekp** [comment]
The problem suddenly disappeared in my application. It seems to be OK now. I update Xamarin.Forms regularly, so it was probably fixed in XF 4.8, or in one of the later Service Releases of XF 4.7.
