### ISSUE TITLE
DisplayAlert crashing app

### ISSUE THREAD

**Issue by xpios01** [xamarin/Xamarin.Forms#9031]
### Description

I'm getting an exception that is crashing the Android app when calling DisplayAlert on a release build APK deployed to a Samsung Galaxy S9+, but I believe it will happen on any device... will test. This doesn't happen when a debug version is deployed with Shared Runtime. I've googled and found various suggestions of explicitly trying to ensure it's running on the main thread, but these are not working. 

I'm running xamarin forms 4.4.0.991265 and Xamarin.Android.Support.v7.AppCompat 28.0.0.3

here's the simple method calling display alert. Notice I've tried Device.BeginInvokeOnMainThread below. 

private void btnAgree_Clicked(object sender, EventArgs e)
        {
            // check that the check box is checked
            if (!chkAccept.IsChecked)
            {
                Device.BeginInvokeOnMainThread(() =>
                {
                    DisplayAlert("Agreement Required", "You must click the check box to confirm agreement before using the application.", "OK");
                });

                return;
            }
           
         // other extraneous code should the process continue

        }

Here's the exception:

Exception has been thrown by the target of an invocation.	  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00086] in <77e72d4c9fa2445c802fb0d360ef0cb6>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <77e72d4c9fa2445c802fb0d360ef0cb6>:0 
  at Xamarin.Forms.MessagingCenter+Subscription.InvokeCallback (System.Object sender, System.Object args) [0x00076] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at Xamarin.Forms.MessagingCenter.InnerSend (System.String message, System.Type senderType, System.Type argType, System.Object sender, System.Object args) [0x0006b] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at Xamarin.Forms.MessagingCenter.Xamarin.Forms.IMessagingCenter.Send[TSender,TArgs] (TSender sender, System.String message, TArgs args) [0x00013] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at Xamarin.Forms.MessagingCenter.Send[TSender,TArgs] (TSender sender, System.String message, TArgs args) [0x00005] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at Xamarin.Forms.Page.DisplayAlert (System.String title, System.String message, System.String accept, System.String cancel) [0x00039] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at Xamarin.Forms.Page.DisplayAlert (System.String title, System.String message, System.String cancel) [0x00000] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at GrappleDataTechnology.XpiosMobile.MainPage.b () [0x00000] in <acdd9aa7df984c5cb01c87dd6ef069f4>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d5c8d6e35b5347eebcff2d38e4abae88>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <d5c8d6e35b5347eebcff2d38e4abae88>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.47(intptr,intptr)

**Comment by samhouts** [comment]
@xpios01  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by shape-8** [comment]
Same here! DisplayAlert(..) throws exception, when called in
Android, 4.4.0.991265, Release build!
Debug is fine!
Also in 4.3.0.991250 DisplayAlert(..) works as expected.

**Comment by samhouts** [comment]
@shape-8  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by xpios01** [comment]
I’m busy and fixed it by making my own dialog. You’ll have to repo yourself.

**Comment by hartez** [comment]
Here's my simple repro project - just a button that calls DisplayAlert. I've run it in Release mode on a couple of Samsung devices, and so far it hasn't crashed. Is there a detail I'm missing?

[_9031 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4043766/_9031.Repro.zip)

**Comment by xpios01** [comment]
Yes, obviously you are missing something. I hope you find it. I cannot download and open file open links sent to me as they are a security risk.

 

Thanks,

Chris

**Comment by hartez** [comment]
Well, without a reproduction of the problem we can only go off of the data in the initial report, and when we follow those instructions it does not fail. 

I'm going to close this one as not reproducible for the moment; if someone can upload a sample project which demonstrates the behavior (or point out what's missing with the provided project), we can reopen it and take another look.

**Comment by xpios01** [comment]
You have at least two people reporting it. Why would you close it? You could make it a p3 so it stays on the PM’s radar, but It’s real. I just don’t have the time to repro it for you. Likely, your simple solution isn’t enough to repro it. I can give you the project config files if that will give you a clue.

 

Chris

**Comment by hartez** [comment]
> Likely, your simple solution isn’t enough to repro it.
Yes. That's why I'm asking for more information. 

> I cannot download and open file open links sent to me as they are a security risk.
You can't browse to the GitHub page for this issue and download the attached repro project?

> I can give you the project config files if that will give you a clue.
Yes. That would be helpful. Any information you can give us would be helpful.

**Comment by roman536** [comment]
DisplayAlert crashes on Xamarin-Android (Xamarin-UWP=OK)
since update to Xamarin.Forms 4.4.0.991477 or 4.4.991265
Last OK: 4.3.0.991250
I don't use Application Theme on Android.Manifest (empty).
Error message:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> Java.Lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
Do you need an example?

**Comment by haiduong741** [comment]
My app crash when running release mode by DisplayAlert. I spent one week for looking the cause.
await .DisplayAlert(message.Title, message.Message, new Utility().GetPreferences("language") == "V" ? "NHẬN" : "OK");

**Comment by laur1208** [comment]
I solved the problem by disabling the linking property before making the apk.
![image](https://user-images.githubusercontent.com/9104509/72597409-64b70080-3916-11ea-863e-a19c60c464c9.png)

**Comment by haiduong741** [comment]
@hartez Run it in release mode. You will see crash

**Comment by laur1208** [comment]
> @hartez Run it in release mode. You will see crash

It worked for me. The problem with the crash when the alert was showing was after downloading the app from play store, and i solved it by disabling linking and re-uploading it.

**Comment by roman536** [comment]
I've described my issue on new thread:
[https://github.com/xamarin/Xamarin.Forms/issues/9214](url)
Can you solve it?

**Comment by hartez** [comment]
@roman536 I was able to reproduce your issue with your example project, thank you. Your issue is in the queue and we'll be working on it soon. The issue has to do with using `FormsApplicationActivity` instead of `FormsAppCompatActivity`; the former is broken in 4.4.

@xpios01 Does your application use `FormsApplicationActivity`? Perhaps that's the missing detail.

**Comment by hartez** [comment]
> @hartez Run it in release mode. You will see crash

I just tried that, and no crash.

> I solved the problem by disabling the linking property before making the apk.

I've tried the repro app with linking turned all the way up (Sdk and User Assemblies), and still no crash.

**Comment by xpios01** [comment]
Here’s what my MainActivity implements

 

public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity

**Comment by haiduong741** [comment]
> @roman536 I was able to reproduce your issue with your example project, thank you. Your issue is in the queue and we'll be working on it soon. The issue has to do with using `FormsApplicationActivity` instead of `FormsAppCompatActivity`; the former is broken in 4.4.
> 
> @xpios01 Does your application use `FormsApplicationActivity`? Perhaps that's the missing detail.

Yes. My app had been used by `FormsAppCompatActivity`. It crashed when release. Xamarin Form version 4.4

**Comment by Paul-GolfingScribe** [comment]
FYI - I experience the same crash on Android with Xamarin.Forms 4.4.0.991477.  Problem was resolved when I upgraded to Xamarin.Forms 4.4.0.991537

**Comment by roman536** [comment]
DisplayAlert works for me again on Android after update to Xamarin.Forms 4.4.0.991537 (published Thursday, January 23, 2020)

**Comment by mphill** [comment]
> DisplayAlert works for me again on Android after update to Xamarin.Forms 4.4.0.991537 (published Thursday, January 23, 2020)

I'm still seeing this on 4.4.0.991537.

Are your linker settings set to none on Android?  I'm getting a crash with DisplayAlert when the linker is set to SDK and user assemblies or just SDK.

**Comment by mphill** [comment]
> Here's my simple repro project - just a button that calls DisplayAlert. I've run it in Release mode on a couple of Samsung devices, and so far it hasn't crashed. Is there a detail I'm missing?
> 
> [_9031 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4043766/_9031.Repro.zip)

I've spend the last day trying to figure this out, thanks @xpios01 for reporting and thanks @hartez for the sample app.

 I can get _9031.Repro.zip to crash when DisplayAlert is called turning by on ProGuard

This should be reopened.

**Comment by PureWeen** [comment]
@mphill what's the exception you are getting?

Can you check logcat?

**Comment by mphill** [comment]
``
Time	Device Name	Type	PID	Tag	Message
01-24 10:58:44.839	pixel_2_pie_9_0_api_28	Error	8003	AndroidRuntime	android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Java.Lang.RuntimeException: Binary XML file line #18: Binary XML file line #18: Error inflating class android.support.v7.widget.AlertDialogLayout ---> Java.Lang.RuntimeException: Binary XML file line #18: Error inflating class android.support.v7.widget.AlertDialogLayout ---> Java.Lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.AlertDialogLayout" on path: DexPathList[[zip file "/data/app/com.companyname.x_9031-4e3uA_IzBbXACmC_rYy9UQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.x_9031-4e3uA_IzBbXACmC_rYy9UQ==/lib/x86, /data/app/com.companyname.x_9031-4e3uA_IzBbXACmC_rYy9UQ==/base.apk!/lib/x86, /system/lib]]
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <c6f0ba1f5c52470c91ddde49f9e2d619>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <c6f0ba1f5c52470c91ddde49f9e2d619>:0 
  at Android.App.Dialog.Show () [0x0000a] in <db6e8a0b2ed84ae99961a42fdc3f0abc>:0 
  at Xamarin.Forms.Platform.Android.PopupManager+PopupRequestHelper.OnAlertRequested (Xamarin.Forms.Page sender, Xamarin.Forms.Internals.AlertArguments arguments) [0x000a6] in <039dc6f9f40c4a668399f93931013d38>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5144070969b04bebab89ce369b8b3986>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00086] in <5144070969b04bebab89ce369b8b3986>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <5144070969b04bebab89ce369b8b3986>:0 
  at Xamarin.Forms.MessagingCenter+Subscription.InvokeCallback (System.Object sender, System.Object args) [0x00076] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at Xamarin.Forms.MessagingCenter.InnerSend (System.String message, System.Type senderType, System.Type argType, System.Object sender, System.Object args) [0x0006b] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at Xamarin.Forms.MessagingCenter.Xamarin.Forms.IMessagingCenter.Send[TSender,TArgs] (TSender sender, System.String message, TArgs args) [0x00013] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at Xamarin.Forms.MessagingCenter.Send[TSender,TArgs] (TSender sender, System.String message, TArgs args) [0x00005] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at Xamarin.Forms.Page.DisplayAlert (System.String title, System.String message, System.String accept, System.String cancel) [0x00039] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at Xamarin.Forms.Page.DisplayAlert (System.String title, System.String message, System.String cancel) [0x00000] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
  at _9031.MainPage.Button_Clicked (System.Object sender, System.EventArgs e) [0x00000] in <4ed8dacd14d54059888e8de78675c1c5>:0 
  at Xamarin.Forms.Button.Xamarin.Forms.Internals.IButtonElement.PropagateUpClicked () [0x0000a] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0 
``

**Comment by hartez** [comment]
@xpios01 Do you have ProGuard enabled for your application?

**Comment by xpios01** [comment]
I believe so. Will check when I get to my computer.

**Comment by PureWeen** [comment]
We added the androidx version of this class to proguard

https://github.com/xamarin/Xamarin.Forms/blob/master/.nuspec/proguard.cfg#L8

So just need to add the non androidx one

**Comment by PureWeen** [comment]
This should fix

https://github.com/xamarin/Xamarin.Forms/pull/9318

If you want to workaround the issue then create a proguard.cfg file and add these three classes

https://github.com/xamarin/Xamarin.Forms/pull/9318/files#diff-dfaf7d70f2606938f80a8f92c2a066adR8-R10

**Comment by MathewLC** [comment]
This is solving when code shrinker is R8? Could you guys give an example on how to put this in linker.xml (Linker Description File)?

**Comment by PureWeen** [comment]
Because this is proguard related you can only solve it by adding the class to a proguard file

**Comment by wutever0** [comment]
Just want to say that this is happening to me even on Xamarin v4.4.0.991537 (some have noted that it works with them after a Xamarin update but I am already using the latest version).

Also this only seems to be happening on newer Android phones. One of our testers reported the app crash on Android 9 even though no one else experiences this issue on lower Android versions (mostly we've been using Android 6 for development).

Even when I got my hands on an Android 9 to test this only happened on the Release build like others have reported and that is because the difference between the Release and the Debug builds was that Debug was setting the Linker options to "None" which I believe is the root cause.

It's also worth noting that there was no Code Shrinker option selected in either build. So I don't know if this is specifically related to ProGruard or not but it's definitely related to the Linker Options. After setting the Linker Options to None the app worked fine.

**Comment by wutever0** [comment]
UPDATE:
I've also tried explicitly setting the Code Shrinker option to r8 while the Linking Option was set to Sdk Assemblies Only and it still crashed. So I don't know if this is only proguard related as you mentioned @PureWeen . But it does seem to be related to the Linking options on newer Android.

**Comment by wutever0** [comment]
Adding a proguard.cfg file like @PureWeen suggested worked even when selecting "d8" as the Code Shrinker and "Sdk Assemblies Only" as the Linking option. Thanks

**Comment by divyesh008** [comment]
I have Xamarin.Forms version - 4.7.0.968 and still I am getting this exception:

## `How to reproduce error?`

<hr/>

```c#
var action = await App.Current.MainPage.DisplayAlert("Exit?", "Are you sure to close", "Yes", "No");
if (action)
{
    Debug.WriteLine($"Action - {action}");
}
else
{
    Debug.WriteLine($"Action - {action}");
}
```
<hr/>

Exception:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Java.Lang.RuntimeException: Can't create handler inside thread Thread[pool-3-thread-1,5,main] that has not called Looper.prepare()
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <42748fcc36b74733af2d9940a8f3cc8e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <42748fcc36b74733af2d9940a8f3cc8e>:0 
  at AndroidX.AppCompat.App.AlertDialog+Builder.Create () [0x00000] in D:\a\1\s\generated\androidx.appcompat.appcompat\obj\Release\monoandroid90\generated\src\AndroidX.AppCompat.App.AlertDialog.cs:129 
  at Xamarin.Forms.Platform.Android.PopupManager+PopupRequestHelper+DialogBuilder.Create () [0x00008] in D:\a\1\s\Xamarin.Forms.Platform.Android\PopupManager.cs:293 
  at Xamarin.Forms.Platform.Android.PopupManager+PopupRequestHelper.OnAlertRequested (Xamarin.Forms.Page sender, Xamarin.Forms.Internals.AlertArguments arguments) [0x00017] in D:\a\1\s\Xamarin.Forms.Platform.Android\PopupManager.cs:128 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00081] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:409 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Reflection/MethodBase.cs:53 
  at Xamarin.Forms.MessagingCenter+Subscription.InvokeCallback (System.Object sender, System.Object args) [0x00064] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:94 
  at Xamarin.Forms.MessagingCenter.InnerSend (System.String message, System.Type senderType, System.Type argType, System.Object sender, System.Object args) [0x0006b] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:217 
  at Xamarin.Forms.MessagingCenter.Xamarin.Forms.IMessagingCenter.Send[TSender,TArgs] (TSender sender, System.String message, TArgs args) [0x00013] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:115 
  at Xamarin.Forms.MessagingCenter.Send[TSender,TArgs] (TSender sender, System.String message, TArgs args) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:108 
  at Xamarin.Forms.Page.DisplayAlert (System.String title, System.String message, System.String accept, System.String cancel) [0x00039] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:205 
  at Xamarin.Forms.Page.DisplayAlert (System.String title, System.String message, System.String cancel) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:195 
  at Coeqwety.App+<>c.<OnStart>b__105_1 (System.Object s, Plugin.PushNotification.Abstractions.PushNotificationDataEventArgs p) [0x006be] in /Users/differenz159/Documents/Sourcetree/Coeqwety_git/Coeqwety/Coeqwety/App.xaml.cs:563 
```
<hr/>

## **Android Build Settings**

![Screenshot 2020-11-07 at 3 01 32 PM](https://user-images.githubusercontent.com/10617244/98437721-9d74d000-210a-11eb-9272-774690bf7ea5.png)

**Comment by divyesh008** [comment]
It's not fixed yet: https://github.com/xamarin/Xamarin.Forms/issues/12772

**Comment by angelru** [comment]
The same issue...

**Comment by OliverONeillNG** [comment]
Same issue, I solved it by calling my DisplayAlert inside this:

```
Device.BeginInvokeOnMainThread(async () =>
{ 
//display alert here
}
```
