### ISSUE TITLE
[Bug] DatePicker theming issues with Android dark mode

### ISSUE THREAD

**Issue by streviranus** [xamarin/Xamarin.Forms#9033]
### Description
When using an Android device that supports dark mode (i.e. Android 10) and styles inheriting from Theme.AppCompat.DayNight, the DatePicker dialog box has a white background instead of dark gray when the device is in dark mode, resulting in unreadable text.

Related to: (https://github.com/xamarin/Xamarin.Forms/issues/8029)

### Steps to Reproduce

1. Define a theme in your Android project that inherits from Theme.AppCompat.DayNight
2. Make a datepicker theme that inherits from Theme.AppCompat.DayNight.Dialog
3. Add the datepicker dialog style to the application theme like so:
     <item name="android:datePickerDialogTheme">@style/AppCompatDialogStyle</item>
5. Set the theme of your MainActivity to the application theme defined above.
6. Run the app on a device in dark mode and click on a DatePicker

### Expected Behavior
The DatePicker is styled according to the theme, with white text on a dark background.

### Actual Behavior
The DatePicker style is only partially applied, resulting in white text on a white background.

### Basic Information

- Version with issue: 4.4.0
- Last known good version: Unknown
- IDE: Visual Studio Professional 2019, version 16.4.2
- Platform Target Frameworks: 
  - Android: 10.0
- Android Support Library Version: 28.0.0.3
- Affected Devices: Pixel 2 with Android 10.0

### Screenshots

![Screenshot_20191227-151204](https://user-images.githubusercontent.com/8270323/71533511-bdb6ea00-28be-11ea-97b7-a173d38b88a8.png)
![Screenshot_20191227-151031](https://user-images.githubusercontent.com/8270323/71533514-c0194400-28be-11ea-8477-5107a57505c4.png)

### Reproduction Link

[DisplayAlertTheming 2.zip](https://github.com/xamarin/Xamarin.Forms/files/4006313/DisplayAlertTheming.2.zip)

**Comment by kingces95** [comment]
Investigating

**Comment by jfversluis** [comment]
Same seems to happen to the normal picker dialog. Also in the Gallery app. But only when you apply customizations. If you take out the custom styles in the `styles.xml` everything will fall in line.

**Comment by DennisWelu** [comment]
Related to Jan6 comment by @jfversluis, removing this line from "styles.xml" cleared up the problem with the "blank" date picker.

`<item name="android:datePickerDialogTheme">@style/AppCompatDialogStyle</item>`

**Comment by streviranus** [comment]
@DennisWelu the whole point of this ticket is to customize the datePickerDialogTheme.

**Comment by MathewLC** [comment]
@jfversluis normal picker has this problem too with the dialog. You guys have plan on fixing? Should I open another issue for that? I'm didn't found any other open about this.

**Comment by jfversluis** [comment]
No need for a new issue! It’s clear that this happens for all the picker variations. We’re aware and hopefully get around to this soon

**Comment by MathewLC** [comment]
I didn't spent too much time looking at it, but I'll definitely do it soon and if I found something I'll let you guys know. Best Regards.

**Comment by sebfrie** [comment]
Are there any updates on this one? A fix is highly appreciated.

**Comment by kazo0** [comment]
Is there currently a workaround for this to get the DatePicker dialog to properly show in dark mode?

**Comment by stefanbogaard86** [comment]
> 
> 
> Is there currently a workaround for this to get the DatePicker dialog to properly show in dark mode?

The workaround I used was to add the Xamarin.Forms.Visual.Material package to my project and set the Visual property to "Material" on my datepickers.

**Comment by BurkusCat** [comment]
When trying to use as spinner picker in DayNight mode, a similar issue occurs in Dark mode:
![image](https://user-images.githubusercontent.com/7528322/103156840-f37a0180-47a4-11eb-992d-67483e03a7d8.png)

``` xml
    <item name="android:datePickerDialogTheme">@style/SpinnerDatePickerStyle</item>
  </style>
    
  <style name="SpinnerDatePickerStyle" parent="Theme.AppCompat.DayNight.Dialog">
    <item name="android:datePickerStyle">@style/SpinnerDatePicker</item>
  </style>

  <style name="SpinnerDatePicker" parent="android:Widget.Material.DatePicker">
      <item name="android:datePickerMode">spinner</item>
  </style>
```

**Comment by Qythyx** [comment]
This is a super-ugly hack, but it solved the problem for me. Based on what @stefanbogaard86 suggested, I tried using Visual="Material", but the problem I ran into was that the DatePicker entry box didn't match the rest of the form. But, he's right that using Material did fix the issue with the picker rendering. So, I found this to get the best of both visuals:
```xaml
<AbsoluteLayout>
	<DatePicker
		AbsoluteLayout.LayoutBounds="0,0,1,1"
		AbsoluteLayout.LayoutFlags="All"
		Date="{Binding Birthdate}"
		Format="yyyy-MM-dd"
		Style="{DynamicResource DatePicker}" />
	<DatePicker
		AbsoluteLayout.LayoutBounds="0,0,1,1"
		AbsoluteLayout.LayoutFlags="All"
		Date="{Binding Birthdate}"
		Format="yyyy-MM-dd"
		Opacity="0"
		Style="{DynamicResource DatePicker}"
		Visual="Material" />
</AbsoluteLayout>
```
The first picker is what we want to show in the form. The second one is what we want to be clickable and show the full date picker. They're both bound to the same property, so when you change the value they both work.

Like I said, this is super-ugly, but it works.

**Comment by giuseppenovielli** [comment]
@jfversluis  Fix this issue into Android's dark mode!! Visual="Material" as workaround

**Comment by giuseppenovielli** [comment]
???

**Comment by jfversluis** [comment]
@giuseppenovielli thanks for the ping and even more thanks for the workaround!

I'm unfortunately no longer involved in the Forms team for my day job so I don't think I can find the time to fix this. Hope this gets resolved soon!

**Comment by giuseppenovielli** [comment]
@jfversluis thanks! For feedback!

**Comment by Johanna-Victoria** [comment]
I would like this bug to be prioritized. I have done non styling changes and get's the same issue in the latest version.

**Comment by BjornVanslembrouck** [comment]
For anyone who is interested. It does seem to work on XF4.5.0.356 (That is the version our project was on)
Upgrading to 5 broke it...

**Comment by Johanna-Victoria** [comment]
Any updates on this for 5?

**Comment by scriptBoris** [comment]
Hello, any updates on this for 5???

**Comment by theadin** [comment]
I really hope this is fixed in MAUI cuz it is still not fixed :-(

**Comment by Hollywood25201** [comment]
Any update on this? It's quite a breaking bug.

**Comment by brimbon** [comment]
I guess there is still not an update for this bug :/

**Comment by MNADEEMCH** [comment]
still no fixes.

**Comment by Jon2G** [comment]
Android 11 still no fix

**Comment by Hooterr** [comment]
Is that going to be fixed eventually?

**Comment by mina5500** [comment]
any update

**Comment by mina5500** [comment]
@samhouts can you please provide us with any updates regarding this issue ... note that timepicker is working fine ... only datepicker is having this isuue ?

**Comment by jfversluis** [comment]
@streviranus, @mina5500, @Hooterr and others, a [PR](https://github.com/xamarin/Xamarin.Forms/pull/14591) for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by mina5500** [comment]
@jfversluis will this solve the datepicker in both Light/Dark mode?

**Comment by jfversluis** [comment]
From my testing: yes. But that is why I'm asking you to test :)

**Comment by Johanna-Victoria** [comment]
This is still not solved! 
Also introduce properties to actually style the Date time picker dialog

**Comment by jfversluis** [comment]
This has been solved but is not released yet. It is set to release with the next service release which is targeted at around October 13th. You can use the nightly feed if you need it today.

There won't be any new properties added for Xamarin.Forms. If this is something you want, please open an issue with all the details of your request on the .NET MAUI repository.

**Comment by daniel-leinweber** [comment]
The nightly feed with Xamarin.Forms version 5.0.1.1876 does not fix the issue for me.

**Comment by jfversluis** [comment]
I see the nightly didn't run correctly over the weekend, sorry about that. Looking into it now :)

**Comment by jfversluis** [comment]
Could you try 5.0.0.2151 from the nightly feed (note, no nightly suffix) please? :)

**Comment by daniel-leinweber** [comment]
The version you mention is not available to me. I guess you meant 5.0.1.2151 and not 5.0.0.2151.

Do I need to add a different package source than https://aka.ms/xf-ci/index.json?

**Comment by jfversluis** [comment]
Interesting. There is more than one nightly feed it's pushed to 😅  It's Monday, sorry! Let me dig a bit deeper.

**Comment by jfversluis** [comment]
Hey there! Could you try [this feed](https://pkgs.dev.azure.com/xamarin/public/_packaging/xf-nightly%40Local/nuget/v3/index.json) please? :)

**Comment by jfversluis** [comment]
YAY YAY YAY! Thanks for confirming! This will be in the next Service Release that should be out next week if everything goes well :)

**Comment by jfversluis** [comment]
@Jorel254 let's try the other way around; what is styles you have? :D

I had to remove this to make it work: https://github.com/xamarin/Xamarin.Forms/pull/14591/files#diff-ad6ba5549da76edd8ee1934f53d44907391c58a5c8fa7071b8fd7a7e47408c9aL49

**Comment by Jon2G** [comment]
@Jorel254 @jfversluis @daniel-leinweber

Our team just tested both ways. I can confirm this is working.
I appreciate the time you took to help me with this issue.
However, the time picker appears to have the same theming issue 
¿Should we create a new ticket about time picker?
I'm much obliged
![image](https://user-images.githubusercontent.com/24820069/136681459-1c384eaf-9fa6-4c39-a0e3-0b43bd657640.png)

**Comment by Jorel254** [comment]
@daniel-leinweber, @jfversluis
I appreciate the time you took to help me with this issue.
I'm much obliged.

**Comment by Jon2G** [comment]
Of course:
https://github.com/Jon2G/Xamarin-9033 
While making this reproduction I noticed the problem is that the accent color remains to be hotpink even after changing it on styles.xml.
Maybe I'm missing something

**Comment by sammacdougall** [comment]
I used this and it has reverted to pink accent on the dialog.
I have after much experimentation found a solution to this.  I have added a values-night folder to android resources and added a style sheet in here.
With in the style sheet I have added my styling for night mode.
I have added my code for light mode in the default style sheet under the values folder.
If there is a site to share this info others may be interested.
Night mode code below in style sheet.
<resources>
  <style name="Theme.Splash" parent="android:Theme">
    <item name="android:windowBackground">@xml/splash_screen_night</item>
    <item name="android:windowNoTitle">true</item>
  </style>
  <style name="MainTheme" parent="MainTheme.Base">
    
    
    
    
    
    
    
    
    
    <item name="colorAccent">#2196F3</item>
    <item name="android:datePickerDialogTheme">@style/CustomDatePickerDialog</item>
  </style>
  <style name="CustomDatePickerDialog" parent="ThemeOverlay.AppCompat.Dialog">
    <item name="colorAccent">#2196F3</item>
    
    <item name="android:textColorPrimaryInverse">#FFFFFF</item>
    
    <item name="android:windowBackground">#292929</item>
    
    <item name="android:colorControlActivated">#2196F3</item>
    
    <item name="android:textColorPrimary">#FFFFFF</item>/item>
    
    <item name="android:textColorSecondary">#FFFFFF</item>
    
    <item name="android:textColor">#2196F3</item>
  </style>
</resources> (edited)

**Comment by sammacdougall** [comment]
Well if you remember then please share. I have spent to much time trying to
find a solution for this. If I have no styling it has hot pink as the
accent. Even with the xamarin forms latest library. My testers are very
pedantic and do not like this so this is the best I can come up with.

**Comment by mina5500** [comment]
Issue fixed with appcompat theme ... but issue with ok cancel colors always pink ... was able to set colors before.
However it does not work with material theme ... white background unreadable popup
@jfversluis
