### ISSUE TITLE
[Bug] UWP Button BackgroundColor turns gray when hovering

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#9123]
### Description
UWP Button BackgroundColor turns gray when hovering ono it while targetting builds: 17763 and 18362, problem doesn't appear in creators update (16299)

### Steps to Reproduce

1. Create a XF button with background color
2. target UWP 17763 or 18362
3. hover on the button

### Expected Behavior
Button preserves its background color (similar to what we get when targetting version 16299)

### Actual Behavior
Button turns to gray (or whatever default theme)

### Basic Information
  - UWP: SDK versions: 17763 and 18362

**Comment by juanmalm** [comment]
Is this issue planned to be fixed?

**Comment by mnxamdev** [comment]
We are having this issue too. We're trying to get get a Windows release out using shared code from our Android and iOS apps. Please help Xamarin! I'd be happy with a workaround.

**Comment by MhAllan** [comment]
@mnxamdev  I updated the issue with my workaround, hope it works for you.

**Comment by holecekp** [comment]
@MhAllan Thank you very much for your workaround. It works also for ImageButton.

**Comment by jfversluis** [comment]
I see some workarounds and I think we did some fixes in this area, closing this one for now, let me know if this is still an issue to anyone! Thanks!

**Comment by dag23** [comment]
@jfversluis It was fixed in 5.0.0.2083 but it's a problem again in 5.0.0.2244.

**Comment by snakebytetech** [comment]
This is still a problem for me as well as other layout issues when I upgraded Xamarin.Forms from 5.0.0.2012 to 5.0.0.2291. I'm targeting UWP for now, Minimum version = 17763 and target = 18362. I also updated a handful of other Nugets.  

This latest update messed up the layout for multiple objects. 

- Switches (hover them and they disappear because of white-on-white and there's a huge gap between the switch and a label I have next to it which wasn't there before.
- Buttons as explained above.
- Stacklayouts center everything and won't recognize when I explicitly give it the default HorizontalOption of "Start".  
- Labels which didn't wrap before now wrap making things look horrible.

Before the upgrade to the latest Xamarin.Forms, this screenshot below looked nice and well layed out. You can see how labels are scrunched with a bunch of space between switches and labels. Note, I have a custom renderer for the switch to hide the on/off text because the words on/off are redundant. I tried removing my renderer and that didn't help. The words to the right of the switches are supposed to be what is right next to the switch. Instead, there is a big gap between the switch and the label now. That wasn't there before.

![2021-12-20_16-03-33](https://user-images.githubusercontent.com/30606156/146842455-8e587f24-a973-4ab2-be99-e6e7c7ed427d.jpg)

Since this thread is about the button, I'm not only experiencing the same as above, but I use buttons as a navigation so I can use Windows shortcut keys and when you click one, it'll make the text color of that button "active". Now, when you hover that button, the "active" color goes away. The only way to get it back is to click it again.

It's as though you forgot about light themes and UWP apps and only tested your releases with dark themes on Android and iOS.

Please help. I don't want to have to go back into every one of my pages to re-design them and change my background so the hover "feature" doesn't ghost out my controls. At this point, if there's not a fix/suggestion soon, I'm probably going to downgrade my Xamarin.Forms and cross my fingers you fix it with the next release because I don't have the time to mess with something like this right now.

**Comment by snakebytetech** [comment]
Another update.  It seems the spacing problem was caused by my Switch Renderer is no longer supported. I like the new version better and perhaps it's how I should have originally written it. Hopefully it helps someone else experiencing similar problems.

![image](https://user-images.githubusercontent.com/30606156/146938110-47f130a1-f291-4eaf-8147-86543bc79ef5.png)


![image](https://user-images.githubusercontent.com/30606156/146937720-0dc8d8d2-ea2d-418f-b9de-df611f5c3e2a.png)

**Comment by dag23** [comment]
I have investigated and the template of the FormsButton does not contain a Grid.
https://github.com/xamarin/Xamarin.Forms/commit/b85c28e530eff581c6fa48742e07cd84cca7dd3e#diff-489c1b3b032afaa3b926f0420f2d644b2faabe1d5008d278e10b6fb5feccbd28
The ButtonRenderer is searching for one to use the InterceptVisualStateManager.
https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.UAP/ButtonRenderer.cs
So it doesn't hook the InterceptVisualStateManager and we can't override the Visual States for the Button in Xamarin.Forms styles.

**Comment by jfversluis** [comment]
Hey everyone, thanks for all the input here. I see a lot of things that might or might not be related, but just to be sure; this is still (or again) an issue in the latest stable version 5.0.0.2291? But it was fixed in an earlier version?

Seems like this PR #13148 might have something to do with it? 

@dag23 besides doing the research do you also have a proposal on how to fix it?

**Comment by bobwhitten** [comment]
I have this issue, and I've not had success yet with a workaround.   I'm running 5.0.0.2478 (latest, as of this writing), and target version is build 19041 (Win 10, version 2004).   For me, this is difficult because I have a dark background, and some white buttons with black text.  So, it almost disappears.  Disabled is even more.  

The iOS behavior for this is just fine (changes opacity, I think, of text). 

I don't want to spend too long on this -- this latecomer app will probably move over to MAUI pretty soon.
