### ISSUE TITLE
[Crash][Compatibility][Android][4.4][KitKat] SwipeView application crash

### ISSUE THREAD

**Issue by SDKexplorer** [xamarin/Xamarin.Forms#9296]
### Description
Application crashes upon loading view if a SlideView component is used.

**Please note: That this issue has been tested an emulated Pixel 2 device with Android 9.0 and it works as expected**

### Steps to Reproduce

1. Set the expiremental flag in MainActivity:

`            
global::Xamarin.Forms.Forms.SetFlags("SwipeView_Experimental");
 global::Xamarin.Forms.Forms.Init(this, bundle);
`

2. Add the following SwipeView in the first view
`
                            <SwipeView>
                                <SwipeView.LeftItems>
                                    <SwipeItems>
                                        <SwipeItem Text="JustASwipe"/>
                                    </SwipeItems>
                                </SwipeView.LeftItems>
                                <StackLayout>
                                    <Label Text="TEST"/>
                                </StackLayout>
                            </SwipeView>
`

3. Notice that the application crashes upon loading the view with the following error message.
   
**System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.**

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: Unknown
- IDE: Visual Studio 2019 v16.3.1
- Platform Target Frameworks: 
  - Android:  4.4 KitKat
- Affected Devices:
 - Zebra TC55
 - Emulated nexus 4 with Android 4.4

**Comment by samhouts** [comment]
[Issue9296.zip](https://github.com/xamarin/Xamarin.Forms/files/4141821/Issue9296.zip)

**Comment by samhouts** [comment]
might be related to #9175

**Comment by samhouts** [comment]
@SDKexplorer I'm having trouble getting my API 19 emulator to work at the moment. Would you mind testing with 4.4.0.991640 to see if we fixed this by chance? Thanks!

**Comment by SDKexplorer** [comment]
@samhouts 

I'm still receiving 

> System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

![image](https://user-images.githubusercontent.com/24542530/74003793-871fc500-497c-11ea-82f6-1c0e6bc54ed5.png)

Exception message: 

> "no method with name='setClipToOutline' signature='(Z)V' in class Lcom/xamarin/forms/platform/android…"

StackTrace: 

> "  at Java.Interop.JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, …"

I've updated the manifest file to target API 19 on this [GitRepo](https://github.com/SDKexplorer/SwipeViewIssue) you might be able to test it with an Nexus 4 emulator that's running the 4.4 OS version

**Comment by jsuarezruiz** [comment]
I've been testing and I can reproduce the problem in 4.4 but not in 4.5. As Samantha has commented it seems that it was related with #9175 that is already merged (fixed).

I also have done tests on the 4.5.0 and master branches using Android 4.4:
![issue9296](https://user-images.githubusercontent.com/6755973/75688256-79b9da00-5c9f-11ea-9c0e-2e282ef17738.gif)
