### ISSUE TITLE
[Bug] UWP WebView custom Font not working

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#9438]
### Description
Using a `font-face` from a file on `UWP` in a `WebView` does not work. The `ttf` font file is not loaded.

### Steps to Reproduce
1. Add `WebView` with custom `font-face` of lo
2. Set html with `font-face` of local file with `ms-appx-web:///`, see [documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows#universal-windows-platform) and [sample](https://github.com/MADSENSE/Madsense.XamarinForms.Sample/blob/c03890ddf66b4497b5540a721734d50e28bc9875/src/Madsense.XamarinForms.Sample/ViewModels/MainPageViewModel.cs#L14)
3. Launch on `UWP`

### Expected Behavior
Custom font works on `WebView`

### Actual Behavior
Custom font not working or not loaded

### Basic Information

- Version with issue: 4.4.0.991537
- Last known good version: -
- IDE: Visual Studio 2019 16.4.3
- Platform Target Frameworks: 
  - UWP: 18362

### Reproduction Link
https://github.com/MADSENSE/Madsense.XamarinForms.Sample/tree/uwp-webview-custom-font

**Comment by PureWeen** [comment]
@YZahringer it looks like people have success with this

https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/customrenderers-hybridwebview/

**Comment by YZahringer** [comment]
@PureWeen Thank you for the answer. I don't think it should be fixed with a custom renderer or custom behavior of `WebView`. Loading custom local Fonts on `WebView` works on iOS and Android. 

Loading local files on the `WebView` also works on UWP, but not the Font. I have updated the reproduction project, with local Font and local Image loading in `WebView` for iOS, Android and UWP.

Loading the image works on all platforms, loading the Font does not work on UWP.
![image](https://user-images.githubusercontent.com/4254116/75112089-be5ec900-5640-11ea-97a3-ce9a1eedf5d0.png)

**Comment by huangjinshe** [comment]
Can I ask when it would be fix?   the problem seems to still exists on v4.8.
