### ISSUE TITLE
[Bug] macOS: 4.4->4.5 regression, labels are invisible (same TextColor as background)

### ISSUE THREAD

**Issue by knocte** [xamarin/Xamarin.Forms#9526]
### Description

A simple page with a simple label becomes invisible in macOS when upgrading from the latest v4.4 to the first v4.5 pre-release.

### Steps to Reproduce

1. Create a XamarinForms app with a macOS frontend; e.g. I created a very simple one here: https://github.com/nblockchain/geewallet/tree/bugreport/invisibleLabelsInMac
2. Run the macOS frontend (if you cloned my testcase, don't forget to switch to the branch `bugreport/invisibleLabelsInMac`)

### Actual Behavior in macOS v.4.5
Label is not visible

### Expected Beheaviour (current behaviour in any other non-macOS frontend, or if you downgrade to v.4.4)
You should see a label with text.

### Basic Information

- Version with issue: 4.5.0.142-pre1 (also the last 4.5 prerelease, pre4)
- Last known good version: 4.4.0.991640
- IDE: VS4Mac 8.4.4.91
- Affected Devices: running macOS catalina (Mac OS X 10.15.2, Darwin 19.2.0 Darwin Kernel Version 19.2.0 Sat Nov  9 03:47:04 PST 2019, root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64)

### Reproduction Link

https://github.com/knocte/geewallet/tree/bugreport/invisibleLabelsInMac

**Comment by SeRgI1982** [comment]
I have noticed also that TextColor change his value to Black - no matter if it is fixed value in XAML (for ex. TextColor="White") or TextColor is changed in code behind.

![Screenshot 2020-02-27 at 12 57 19](https://user-images.githubusercontent.com/9572525/75444697-3a6c5000-5964-11ea-925d-a4aa0e8964dd.png)

**Comment by knocte** [comment]
> I have noticed also that TextColor change his value to Black - no matter if it is fixed value in XAML (for ex. TextColor="White") or TextColor is changed in code behind.

@SeRgI1982  Then this looks like a regression caused by https://github.com/xamarin/Xamarin.Forms/commit/667c1cc7167b3275ee84f748177ed7dc0d70a9c3, I guess you should file a new bug.

**Comment by ffgiraldez** [comment]
I facing the same problem, no matter if change the color, just update the Label (change the Text, for example) and will reset the color to default. as workarround I apply a Effect
```
public class LabelEffect : PlatformEffect
    {
        protected override void OnAttached() { }

        protected override void OnDetached(){ }

        protected override void OnElementPropertyChanged(PropertyChangedEventArgs args)
        {
            base.OnElementPropertyChanged(args);
            if (args.PropertyName == Label.TextColorProperty.PropertyName ||
                args.PropertyName == Label.TextProperty.PropertyName)
            {
                UpdateTextColor();
            }
        }

        private void UpdateTextColor()
        {
            if (!(Control is NSTextField field)) return;
            var color = (Color) Element.GetValue(Label.TextColorProperty);
            field.TextColor = color.ToNSColor();
        }
    }
```

**Comment by jfversluis** [comment]
@ffgiraldez would you be able to try the NuGet available here: https://dev.azure.com/xamarin/public/_build/results?buildId=15995&view=artifacts&type=publishedArtifacts

Which is part of PR #10120 I think that should fix this problem and it would be awesome to verify that :)

**Comment by ffgiraldez** [comment]
@kjversluis I will check it asap

**Comment by SeRgI1982** [comment]
The issue still exists in Xamarin Forms 4.6.0.726
[XFMacSample.zip](https://github.com/xamarin/Xamarin.Forms/files/4592418/XFMacSample.zip)
