### ISSUE TITLE
[Bug] Grouped CollectionView breaks (NSInternalInconsistencyException) on iOS

### ISSUE THREAD

**Issue by MookieFumi** [xamarin/Xamarin.Forms#9817]
### Description

Since the last update of Xamarin Forms 4.5 the app breaks on a Grouped CollectionView but let me said the error was happening before with the previous XF version but only in iOS 12.4. Now it's exploiting on any iOS version.

If i remove the line 43 in MainPageViewModel.cs file the app works properly, but a i need to recover here some info before the service method has been called.

### Steps to Reproduce

1. Add a breakpoint on MainPageViewModel line 82
2. Run the attached repo

### Expected Behavior

No break

### Actual Behavior

Breaks the app with the following exception

{Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (1) must be equal to the number of sections contained in the collection view before the update (1), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).}

### Basic Information

- Version with issue: Xamarin Forms 4.5
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  12.4, 13.3
- Affected Devices: iOS devices

### Screenshots

![image](https://user-images.githubusercontent.com/4056557/75753627-71a77c00-5d2b-11ea-9a4e-e80c0b9b970f.png)

### Reproduction Link

I have upload a new [GitHub repo](https://github.com/MookieFumi/CollectionView_Exception)

### Workaround

No workaround

**Comment by Reveon** [comment]
I am having the same issue after update to Xamarin.Forms 4.5.0.356. I am using iOS 13.3 and Grouped CollectionView. For me it's crashing on .Add method of the ObservableCollection

`Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (2) must be equal to the number of sections contained in the collection view before the update (2), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).
Native stack trace:
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c70ff8 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff256e9b51 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff47886dd0 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 17849
	5   UIKitCore                           0x00007fff47881d49 -[UICollectionView _updateSections:updateAction:] + 449
	6   UIKitCore                           0x00007fff47881e65 -[UICollectionView insertSections:] + 64
	7   App.iOS               0x000000010dc02bf9 xamarin_dyn_objc_msgSend + 217
	8   ???                                 0x000000011d659710 0x0 + 4788164368`

**Comment by Depechie** [comment]
hey @Reveon maybe you could try my suggestion I posted on a similar issue here : https://github.com/xamarin/Xamarin.Forms/issues/6011#issuecomment-559017278 it should fix the add problem.

**Comment by agat366** [comment]
Yeah, the suggested fix seem have helped to someone, but in my case:
a) I need to have Insert, not Add (which is kind of solvable because if the index which can be found out) (I suppose), but the example from #6011 haven't worked for me anyways. (Still receiving the exception on AddRange called.

**Comment by NunoBem** [comment]
Had the same issue before, now in XF 4.5 the same.

```
2020-03-25 15:18:20.338 Xamarin.PreBuilt.iOS[452:67117] *** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3901.4.5/UICollectionView.m:6772
[0:] Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (2) must be equal to the number of sections contained in the collection view before the update (2), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).
Native stack trace:
	0   CoreFoundation                      0x000000019a0d6a5c 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 1227356
	1   libobjc.A.dylib                     0x0000000199dfdfa4 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000199fd8e88 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 188040
	3   Foundation                          0x000000019a40e654 7B1733B1-74C9-3A33-8A58-853B0A029826 + 554580
	4   UIKitCore                           0x000000019d9d9894 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 2623636
	5   UIKitCore                           0x000000019d9d581c D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 2607132
	6   UIKitCore                           0x000000019d9d5930 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 2607408
	7   Xamarin.PreBuilt.iOS                0x00000001022c7328 do_icall + 360
	8   Xamarin.PreBuilt.iOS                0x00000001022c5944 do_icall_wrapper + 296
	9   Xamarin.PreBuilt.iOS                0x00000001022be718 interp_exec_method_full + 1660
	10  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	11  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	12  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	13  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	14  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	15  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	16  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	17  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	18  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	19  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	20  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	21  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	22  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	23  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	24  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	25  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	26  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	27  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	28  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	29  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	30  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	31  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	32  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	33  Xamarin.PreBuilt.iOS                0x00000001022be968 interp_exec_method_full + 2252
	34  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	35  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	36  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	37  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	38  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	39  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	40  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	41  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	42  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	43  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	44  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	45  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	46  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	47  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	48  Xamarin.PreBuilt.iOS                0x00000001022be968 interp_exec_method_full + 2252
	49  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	50  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	51  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	52  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	53  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	54  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	55  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	56  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	57  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	58  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	59  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	60  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	61  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	62  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	63  Xamarin.PreBuilt.iOS                0x00000001022be968 interp_exec_method_full + 2252
	64  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	65  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	66  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	67  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	68  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	69  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	70  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	71  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	72  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	73  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	74  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	75  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	76  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	77  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	78  Xamarin.PreBuilt.iOS                0x00000001022be968 interp_exec_method_full + 2252
	79  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	80  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	81  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	82  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	83  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	84  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	85  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	86  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	87  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	88  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	89  Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	90  Xamarin.PreBuilt.iOS                0x00000001022bd264 interp_runtime_invoke + 352
	91  Xamarin.PreBuilt.iOS                0x000000010211f7b0 mono_jit_runtime_invoke + 904
	92  Xamarin.PreBuilt.iOS                0x00000001021d4400 mono_runtime_try_invoke + 156
	93  Xamarin.PreBuilt.iOS                0x00000001021d60a0 mono_runtime_invoke + 100
	94  Xamarin.PreBuilt.iOS                0x0000000102083000 _ZL31native_to_managed_trampoline_35P11objc_objectP13objc_selectorPP11_MonoMethodj + 236
	95  Xamarin.PreBuilt.iOS                0x000000010208769c -[__MonoMac_NSAsyncSynchronizationContextDispatcher xamarinApplySelector] + 48
	96  Foundation                          0x000000019a4bf224 7B1733B1-74C9-3A33-8A58-853B0A029826 + 1278500
	97  CoreFoundation                      0x000000019a054a00 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 694784
	98  CoreFoundation                      0x000000019a054958 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 694616
	99  CoreFoundation                      0x000000019a0540f0 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 692464
	100 CoreFoundation                      0x000000019a04f23c 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 672316
	101 CoreFoundation                      0x000000019a04eadc CFRunLoopRunSpecific + 464
	102 GraphicsServices                    0x00000001a3fef328 GSEventRunModal + 104
	103 UIKitCore                           0x000000019e15c63c UIApplicationMain + 1936
	104 Xamarin.PreBuilt.iOS                0x00000001022c729c do_icall + 220
	105 Xamarin.PreBuilt.iOS                0x00000001022c5944 do_icall_wrapper + 296
	106 Xamarin.PreBuilt.iOS                0x00000001022be718 interp_exec_method_full + 1660
	107 Xamarin.PreBuilt.iOS                0x00000001022be968 interp_exec_method_full + 2252
	108 Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	109 Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	110 Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	111 Xamarin.PreBuilt.iOS                0x00000001022bd264 interp_runtime_invoke + 352
	112 Xamarin.PreBuilt.iOS                0x000000010211f7b0 mono_jit_runtime_invoke + 904
	113 Xamarin.PreBuilt.iOS                0x00000001021d2be4 mono_runtime_invoke_checked + 148
	114 Xamarin.PreBuilt.iOS                0x00000001021d9450 mono_runtime_try_invoke_array + 1284
	115 Xamarin.PreBuilt.iOS                0x000000010217cb44 ves_icall_InternalInvoke + 1036
	116 Xamarin.PreBuilt.iOS                0x000000010218f508 ves_icall_InternalInvoke_raw + 108
	117 Xamarin.PreBuilt.iOS                0x00000001022c7228 do_icall + 104
	118 Xamarin.PreBuilt.iOS                0x00000001022c5944 do_icall_wrapper + 296
	119 Xamarin.PreBuilt.iOS                0x00000001022be718 interp_exec_method_full + 1660
	120 Xamarin.PreBuilt.iOS                0x00000001022be968 interp_exec_method_full + 2252
	121 Xamarin.PreBuilt.iOS                0x00000001022be968 interp_exec_method_full + 2252
	122 Xamarin.PreBuilt.iOS                0x00000001022be968 interp_exec_method_full + 2252
	123 Xamarin.PreBuilt.iOS                0x00000001022be9e0 interp_exec_method_full + 2372
	124 Xamarin.PreBuilt.iOS                0x00000001022bd264 interp_runtime_invoke + 352
	125 Xamarin.PreBuilt.iOS                0x000000010211f7b0 mono_jit_runtime_invoke + 904
	126 Xamarin.PreBuilt.iOS                0x00000001021d2be4 mono_runtime_invoke_checked + 148
	127 Xamarin.PreBuilt.iOS                0x00000001021d7fcc mono_runtime_exec_main_checked + 128
	128 Xamarin.PreBuilt.iOS                0x0000000102103bfc mono_jit_exec + 376
	129 Xamarin.PreBuilt.iOS                0x00000001022baf88 xamarin_main + 2176
	130 Xamarin.PreBuilt.iOS                0x00000001020cbd20 main + 84
	131 libdyld.dylib                       0x0000000199ed8360 7B531A15-3E73-3185-90E2-B88D9476DA5E + 4960
: Error - GetUsefulList - : {0}

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x102118bb0 - /private/var/containers/Bundle/Application/B85F0E7B-EC9C-4B1A-8AE4-591EF0582F33/ToGuests.iOS.app/Xamarin.PreBuilt.iOS : mono_dump_native_crash_info
	0x10210f550 - /private/var/containers/Bundle/Application/B85F0E7B-EC9C-4B1A-8AE4-591EF0582F33/ToGuests.iOS.app/Xamarin.PreBuilt.iOS : mono_handle_native_crash
	0x10211c4e8 - /private/var/containers/Bundle/Application/B85F0E7B-EC9C-4B1A-8AE4-591EF0582F33/ToGuests.iOS.app/Xamarin.PreBuilt.iOS : mono_sigsegv_signal_handler_debug
	0x199de4894 - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x1022be9e0 - /private/var/containers/Bundle/Application/B85F0E7B-EC9C-4B1A-8AE4-591EF0582F33/ToGuests.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full
	0x199fab000 - /System/Library/Frameworks/CoreFoundation.fr
amework/CoreFoundation : __dso_handle

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1022be978):0x1022be968  a8 83 58 f8 08 01 40 f9 68 87 00 f8 a8 03 57 f8  ..X...@.h
.....W.
0x1022be978  08 01 40 b9 a8 26 03 35 a8 02 40 79 c8 7a 68 f8  ..@..&.5..@y.zh.
.).@y

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x000b0>
	  at UIKit.UIApplication:Main <0x0001e>
	  at UIKit.UIApplication:Main <0x00034>
	  at ToGuests.iOS.Application:Main <0x00012>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00090>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00034>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x000f6>
	  at System.Reflection.MethodBase:Invoke <0x0001a>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x0022c>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00090>
=================================================================
0x1022be988  f9 03 15 aa 00 01 1f d6 35 13 00 91 a8 83 56 f8  ........5.....V.
0x1022be998  19 15 00 f9 08 05 40 f9 08 25 40 f9 29 07 40 79  ......@..%@

```

**Comment by NunoBem** [comment]
Regressed to "latest" Xamarin Forms 4.4 > 4.4.0.991864 and it works with no errors. 
Had migrated the Android nuggets to AndroidX already, have to evaluate how to arrange this.

**Comment by NunoBem** [comment]
@hartez just to coordinate with our team. We have feature branches with latest XF4.5, we want to launch. Should we regress everything to XF4.4? Is there a workaround? Do you have an ETA for this issue?

Thanks in advance.

**Comment by winterdouglas** [comment]
I face this issue for a while already, since the first versions of XF 4.4, updated to the latest XF 4.5 yesterday and it's still happening.

**Comment by hartez** [comment]
This is fixed in 4.6.0.

**Comment by winterdouglas** [comment]
@hartez, I just checked here and it's indeed more stable on iOS, but I still face an internal inconsistency exception after updating to XF 4.6.
```
Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: attempt to delete item 9 from section 3 which only contains 9 items before the update
Native stack trace:
	0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e39c88 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff258a3cd2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff4838ee5b -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 6475
	5   UIKitCore                           0x00007fff4839b0e6 -[UICollectionView _endUpdatesWithInvalidationContext:tentativelyForReordering:animator:] + 71
	6   UIKitCore                           0x00007fff4839b445 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:] + 462
	7   UIKitCore                           0x00007fff4839b254 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 90
	8   UIKitCore                           0x00007fff4839b1d7 -[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 74
	9   UIKitCore                           0x00007fff4839b12c -[UICollectionView performBatchUpdates:completion:] + 53
```

Now idk whether that's the exact same issue... On Android the exact same code works perfectly.

**Comment by MookieFumi** [comment]
I’ve been doing some tests with **XF 4.6.0** and it’s working properly with iOS 12.4 & 13.4 but I should test it with more data. Maybe tomorrow I’ll update the attached repo.

Thank you in advance.

**Comment by hartez** [comment]
> @hartez, I just checked here and it's indeed more stable on iOS, but I still face an internal inconsistency exception after updating to XF 4.6.
> 
> ```
> Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: attempt to delete item 9 from section 3 which only contains 9 items before the update
> 
> Now idk whether that's the exact same issue... 

It looks like a different issue; the Reason part of the exception is different.

Please open a separate issue for your particular problem, along with a description of what you're doing when the exception is thrown (and your stack trace), and we'll look into it.

**Comment by winterdouglas** [comment]
@hartez, yeah, I'll have to find clear reproduction steps for that. I'll take my time during the week to find out the exact conditions that are making that happen.
Thanks anyway!

**Comment by samirgcofficial** [comment]
Xamarin Forms : 5.0.0.2012
Resolved bug by add await Task.Delay(500); 
Here is a sample code : 
            MyProductItems.Clear(); // My ProductItems is a  Observable Collection Binded to the UI. 
            foreach (var item in headergroup) // Loops through the headers  //Add your implmenetations
            {
                var productGroup = new GroupedProductItemModel();
                var contents = subList.Where(i => i.SubGroupIdentifier == item).ToList();
                if (contents.Count != 0)
                {
                    foreach (var groupitems in contents)
                    {
                        //Your operations
                    }
         
                    await Task.Delay(500); 
                    MyProductItems.Add(productGroup);

**Comment by GV1072** [comment]
Hi,
 I am using Xamarin Forms latest version 5.0.0.2515 but still I am getting same issue. Please let me know if there is any solution from framework without using delay 500.

Thank you in advance.

**Comment by Jakar510** [comment]
@GV1072 
I was able to get to work with `await Task.Delay(15)` 
Shorter delay times seem to be hit or miss.

**Comment by mrobraven** [comment]
Placing a delay is not a proper fix, any chance this will be looked into on SR13?

**Comment by LouwrensP** [comment]
Any solution yet? I am using the AddRange() from MVVMHelpers but still doesn't work.

**Comment by donatellijl12** [comment]
I'm also having this issue now in .NET MAUI with .NET 8. The issue is only on iOS. A delay does not fix it for me, nor is it an acceptable fix.
