### ISSUE TITLE
[Bug] System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer'. or JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)

### ISSUE THREAD

**Issue by SneWs** [xamarin/Xamarin.Forms#9845]
### Description
We are seeing sporadic crashes specifically on Android where we get System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer'. in a ListView.

### Steps to Reproduce
No known repro steps currently, we're seeing this in crash analytics. 

### Expected Behavior
Should not crash

### Actual Behavior
Crashes for customers and end users

### Basic Information

- Version with issue: 4.5.0.282-pre4

- Last known good version: None

- IDE: N/A

- Platform Target Frameworks: 
  - iOS: 8.0
  - Android: 7.0 to 10.0
  - UWP:  N/A
- Android Support Library Version: N/A
- Affected Devices:
 Random Android devices

### Workaround
No known workarounds currently.

### Stack traces from crash analytics
```
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
TextView.set_TextFormatted (Java.Lang.ICharSequence value)
TextView.set_Text (System.String value)
LabelRenderer.UpdateText ()
LabelRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
BindableObject.OnPropertyChanged (System.String propertyName)
Element.OnPropertyChanged (System.String propertyName)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
TypedBinding`2[TSource,TProperty].ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget)
TypedBinding`2[TSource,TProperty].Apply (System.Object context, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty, System.Boolean fromBindingContextChanged)
BindableObject.ApplyBindings (System.Boolean skipBindingContext, System.Boolean fromBindingContextChanged)
BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value)
Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context)
Element.<OnBindingContextChanged>b__82_0 (Xamarin.Forms.BindableObject child, System.Object bc)
BindableObjectExtensions.PropagateBindingContext[T] (Xamarin.Forms.BindableObject self, System.Collections.Generic.IList`1[T] children, System.Action`2[T1,T2] setChildBindingContext)
Element.OnBindingContextChanged ()
VisualElement.OnBindingContextChanged ()
View.OnBindingContextChanged ()
Grid.OnBindingContextChanged ()
BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value)
Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context)
Element.<OnBindingContextChanged>b__82_0 (Xamarin.Forms.BindableObject child, System.Object bc)
BindableObjectExtensions.PropagateBindingContext[T] (Xamarin.Forms.BindableObject self, System.Collections.Generic.IList`1[T] children, System.Action`2[T1,T2] setChildBindingContext)
Element.OnBindingContextChanged ()
Cell.OnBindingContextChanged ()
BindableObject.BindingContextPropertyChanged (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess)
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value)
BindableObject.set_BindingContext (System.Object value)
TemplatedItemsList`2[TView,TItem].UnhookItem (TItem item)
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.58(intptr,intptr)
```

**Comment by SneWs** [comment]
And one more similar crash but from a different part of the application.

```
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
TextView.set_TextFormatted (Java.Lang.ICharSequence value)
TextView.set_Text (System.String value)
LabelRenderer.UpdateText ()
LabelRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
BindableObject.OnPropertyChanged (System.String propertyName)
Element.OnPropertyChanged (System.String propertyName)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
TypedBinding`2[TSource,TProperty].ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget)
TypedBinding`2[TSource,TProperty].Apply (System.Boolean fromTarget)
TypedBinding`2+PropertyChangedProxy[TSource,TProperty].<OnPropertyChanged>b__16_0 ()
DispatcherExtensions.Dispatch (Xamarin.Forms.IDispatcher dispatcher, System.Action action)
TypedBinding`2+PropertyChangedProxy[TSource,TProperty].OnPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
BindingExpression+WeakPropertyChangedProxy.OnPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
BindableBase.OnPropertyChanged (System.ComponentModel.PropertyChangedEventArgs args)
BindableBase.OnPropertyChanged (System.String propertyName)
BindableBase.RaisePropertyChanged (System.String propertyName)
BindableBase.SetProperty[T] (T& storage, T value, System.String propertyName)
CurrentAirportViewModel.set_DisplayName (System.String value)
CurrentAirportViewModel.AirportChangedTo (SwedishAirports.WebApi.Models.Airport airport)
ConfigurationService.ChangeAirport (System.String newICAO)
SelectAirportPageViewModel.AirportSelected (SwedishAirports.ViewModels.Airports.SelectAirportItemViewModel obj)
DelegateCommand`1[T].Execute (T parameter)
DelegateCommand`1[T].Execute (System.Object parameter)
ICommand.Execute (System.Object parameter)
EventToCommandBehavior.OnEventRaised (System.Object sender, System.EventArgs eventArgs)
(wrapper dynamic-method) System.Object.lambda_method(System.Runtime.CompilerServices.Closure,object,Xamarin.Forms.SelectedItemChangedEventArgs)
(wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.SelectedItemChangedEventArgs].invoke_void_object_TEventArgs(object,Xamarin.Forms.SelectedItemChangedEventArgs)
ListView.OnSelectedItemChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes)
ListView.NotifyRowTapped (System.Int32 groupIndex, System.Int32 inGroupIndex, Xamarin.Forms.Cell cell)
ListView.NotifyRowTapped (System.Int32 index, Xamarin.Forms.Cell cell)
ListViewAdapter.HandleItemClick (Android.Widget.AdapterView parent, Android.Views.View view, System.Int32 position, System.Int64 id)
CellAdapter.OnItemClick (Android.Widget.AdapterView parent, Android.Views.View view, System.Int32 position, System.Int64 id)
AdapterView+IOnItemClickListenerInvoker.n_OnItemClick_Landroid_widget_AdapterView_Landroid_view_View_IJ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_parent, System.IntPtr native_view, System.Int32 position, System.Int64 id)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.106(intptr,intptr,intptr,intptr,int,long)
```

**Comment by hartez** [comment]
This should be fixed by #9764.

**Comment by SneWs** [comment]
As a FYI, I'm seeing this in 4.6.0.379-pre1 as well.

**Comment by matteopiccioni** [comment]
This is really a huge problem for our Android apps.
is not only related to listview
This is my stack traces

> JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer'.

> JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
TextView.set_TextFormatted (Java.Lang.ICharSequence value)
TextView.set_Text (System.String value)
LabelRenderer.UpdateText ()
LabelRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
BindableObject.OnPropertyChanged (System.String propertyName)
Element.OnPropertyChanged (System.String propertyName)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
TypedBinding`2[TSource,TProperty].ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget)
TypedBinding`2[TSource,TProperty].Apply (System.Object context, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty, System.Boolean fromBindingContextChanged)
BindableObject.ApplyBindings (System.Boolean skipBindingContext, System.Boolean fromBindingContextChanged)
BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value)
Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context)
Element.<OnBindingContextChanged>b__82_0 (Xamarin.Forms.BindableObject child, System.Object bc)
BindableObjectExtensions.PropagateBindingContext[T] (Xamarin.Forms.BindableObject self, System.Collections.Generic.IList`1[T] children, System.Action`2[T1,T2] setChildBindingContext)
Element.OnBindingContextChanged ()
VisualElement.OnBindingContextChanged ()
View.OnBindingContextChanged ()
BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value)
Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context)
Element.<OnBindingContextChanged>b__82_0 (Xamarin.Forms.BindableObject child, System.Object bc)
BindableObjectExtensions.PropagateBindingContext[T] (Xamarin.Forms.BindableObject self, System.Collections.Generic.IList`1[T] children, System.Action`2[T1,T2] setChildBindingContext)
Element.OnBindingContextChanged ()
VisualElement.OnBindingContextChanged ()
View.OnBindingContextChanged ()
BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value)
Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context)
Element.<OnBindingContextChanged>b__82_0 (Xamarin.Forms.BindableObject child, System.Object bc)
BindableObjectExtensions.PropagateBindingContext[T] (Xamarin.Forms.BindableObject self, System.Collections.Generic.IList`1[T] children, System.Action`2[T1,T2] setChildBindingContext)
Element.OnBindingContextChanged ()
Cell.OnBindingContextChanged ()
BindableObject.BindingContextPropertyChanged (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess)
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value)
BindableObject.set_BindingContext (System.Object value)
TemplatedItemsList`2[TView,TItem].UnhookItem (TItem item)
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.55(intptr,intptr)

**Comment by hartez** [comment]
> As a FYI, I'm seeing this in 4.6.0.379-pre1 as well.

Should be fixed in 4.6.0 pre2.

**Comment by Reveon** [comment]
I am still occasionally getting ObjectDisposedException even with 4.6 pre2 on Android 10 emulator.

`System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer'.`

`    JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
    JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
    View.get_Context ()
    Platform.GetNativeSize (Xamarin.Forms.VisualElement view, System.Double widthConstraint, System.Double heightConstraint)
    Forms+AndroidPlatformServices.GetNativeSize (Xamarin.Forms.VisualElement view, System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.OnSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.OnMeasure (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)
    Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region)
    Grid.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height)
    Layout.UpdateChildrenLayout ()
    Layout.OnSizeAllocated (System.Double width, System.Double height)
    VisualElement.SizeAllocated (System.Double width, System.Double height)
    Layout.ResolveLayoutChanges ()
    Thread+RunnableImplementor.Run ()
    IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
    (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.20(intptr,intptr)`

**Comment by SneWs** [comment]
Yeah, same here, still seeing the occasional object disposed exception using 4.6.0 pre2

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <5c01cc23b53949bca33fa3e8371e1af3>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <5c01cc23b53949bca33fa3e8371e1af3>:0
  at Android.Views.View.get_Context () [0x0000a] in <9208d5fd0c8c43b7a00f304ba0f7c041>:0
  at Xamarin.Forms.Platform.Android.Platform.GetNativeSize (Xamarin.Forms.VisualElement view, System.Double widthConstraint, System.Double heightConstraint) [0x00019] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:1332
  at Xamarin.Forms.Forms+AndroidPlatformServices.GetNativeSize (Xamarin.Forms.VisualElement view, System.Double widthConstraint, System.Double heightConstraint) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\Forms.cs:855
  at Xamarin.Forms.VisualElement.OnSizeRequest (System.Double widthConstraint, System.Double heightConstraint) [0x00025] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:787
  at Xamarin.Forms.VisualElement.OnMeasure (System.Double widthConstraint, System.Double heightConstraint) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:770
  at Xamarin.Forms.VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint) [0x00053] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:646
  at Xamarin.Forms.VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags) [0x00054] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:704
  at Xamarin.Forms.Grid.CalculateAutoCells (System.Double width, System.Double height) [0x000e5] in D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:133
  at Xamarin.Forms.Grid.MeasureGrid (System.Double width, System.Double height, System.Boolean requestSize) [0x0000c] in D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:485
  at Xamarin.Forms.Grid.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x0000e] in D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:18
  at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x00158] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:266
  at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:224
  at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:792
  at Xamarin.Forms.Layout.ResolveLayoutChanges () [0x0005c] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:392
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <9208d5fd0c8c43b7a00f304ba0f7c041>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <9208d5fd0c8c43b7a00f304ba0f7c041>:0
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.51(intptr,intptr)
```

**Comment by hartez** [comment]
@Reveon and @SneWs You are both seeing a different bug from a different cause. Notice that the original bug stack trace includes a call to OnElementPropertyChanged; neither of your post-4.6.0-pre2 stack traces include that. 

It looks like you're both seeing an issue from Layout.ResolveLayoutChanges. Please open a new issue (and include your stack traces and any other relevant info) so we can track and fix this bug.

**Comment by SneWs** [comment]
Ah, yes, you are correct, sorry about that. I will create a new bug around this. Thx for you effort and time!

**Comment by SneWs** [comment]
Bug #10159 filed

**Comment by samhouts** [comment]
closed by #9764

**Comment by kiran-nel** [comment]
OnPropertyChanged (System.String propertyName)
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer'


I'm using Xamarin 4.8 but still facing above issue.Any help.

Thanks in advance.

**Comment by rodrigotristany** [comment]
Same problem with Xamarin.Forms.Platform.Android.FastRenderers.FrameRenderer

**Comment by kiran-nel** [comment]
I have solved the issue while setting below flag in android (Xamarin.form>4.8V)

Forms.SetFlags("UseLegacyRenderers"); in MainActivity class before calling Forms.Init:

if we need to solve  issue <4.8 try to replace Listview with bindableLayout.

**Comment by rodrigotristany** [comment]
In my case the problem was a view model that I didn't unsubscribe from an event, so the it was trying to update a disposed view.
