### ISSUE TITLE
[Bug] Setting CharacterSpacing on Button leads to crash on iOS

### ISSUE THREAD

**Issue by gata-bah** [xamarin/Xamarin.Forms#9906]
### Steps to Reproduce

1. Change the text of a button with CharacterSpacing set to 1 while the button is displayed.
2. Crash!

### Expected Behavior
Text is updated. No crash.

**Foundation.MonoTouchException: 'Objective-C exception thrown. Name: NSRangeException Reason: NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds**

### Actual Behavior
App freezes shortly. Then crashes.

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.908675
- Last known good version: -
- IDE: Visual Studio 2019 16.4.3
- Platform Target Frameworks: iOS
  - xcode version 11.3.1
  - mono version 6.6.0.155
  - MacOS version 10.14.6
  - Xamarin.iOS version 13.10.0.17

### Reproduction Link
Open app, click second button to update text of first button. Then it should crash.

[CharacterSpacing.zip](https://github.com/xamarin/Xamarin.Forms/files/4307533/CharacterSpacing.zip)

**Comment by yurkinh** [comment]
This issue also relates to Label, Entry, Editor, Picker.

**Comment by rmarinho** [comment]
This was fixed on main

**Comment by lavanyatankasala** [comment]
Hi @samhouts @gata-bah - Is the setting character spacing on button issue  included in Xamarin Forms 5.0.0?. I have updated to XF 5.0.0 but still the app is crashing. If its not included, Can you please let me know the time line for this and in which it might be included. Thanks in advance!!.

**Comment by andrrrr** [comment]
in Jan 2021, I'm still having this issue (updated to forms5.0.0)

**Comment by jigneshbodarya** [comment]
Still issue exist in Xamarin forms version 5.0.0.2012

**Comment by jimiatnymbl** [comment]
We just upgraded to XF5 and are now experience this crash (on iOS only) as well.

I'm not familiar with the Xamarin.Forms structure, but as far as I can tell the fix is not in any of the latest releases.  I cloned the repo and also looked through the code on Github (including the latest release tags of SR-1, SR-2 and SR-3) and the change to Extensions.cs is not there.

Because we experience this crash on the exact same view, I'm wondering if there is something we can do to work around it (and if anyone else has found a work-around)?

**Comment by jimiatnymbl** [comment]
I believe I have fixed this in my local copy of Xamarin.Forms.  I'll try to submit a PR.

**Comment by jimiatnymbl** [comment]
Sorry for all the updates on a Closed issue.  Just wanted to add some info here for anyone else that might come across this issue.

After fixing the Xamarin Forms code I had a better understanding of why it was crashing.  I realized that this could be fixed in my code instead.  So if anyone else is getting a crash **_with_**:

* XF5
* iOS
* Custom Renderer with Kerning
* when changing an existing button's text

Adding this to your OnElementPropertyChanged() fixes the crash:

```
        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs args)
        {
            if (!string.IsNullOrEmpty(Element?.Text) && Control != null &&
                Control.GetAttributedTitle(UIControlState.Normal)?.Value != Element.Text)
            {
                Control.SetAttributedTitle(new NSAttributedString(Element.Text), UIControlState.Normal);
                Control.SetAttributedTitle(new NSAttributedString(Element.Text), UIControlState.Selected);
                Control.SetAttributedTitle(new NSAttributedString(Element.Text), UIControlState.Disabled);
                Control.SetAttributedTitle(new NSAttributedString(Element.Text), UIControlState.Highlighted);
            }
            
            base.OnElementPropertyChanged(sender, args);

(rest of your code here)
```
